// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPython.h"

#include "vtkSystemIncludes.h"
#include <string.h>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings 

extern  "C" {PyObject *PyVTKAddFile_vtkAbstractContextItem(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAxis(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBlockItem(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBrush(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkChart(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkChartLegend(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkChartHistogram2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkChartParallelCoordinates(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkChartXY(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkChartPie(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkColorLegend(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPlotPie(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkColorSeries(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkColorTransferFunctionItem(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkColorTransferControlPointsItem(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCompositeControlPointsItem(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCompositeTransferFunctionItem(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkContext2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkContextActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkContextClip(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkContextDevice2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkContextInteractorStyle(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkContextItem(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkContextMapper2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkContextScene(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkContextTransform(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkContextView(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkControlPointsItem(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageItem(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLookupTableItem(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPen(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPiecewiseControlPointsItem(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPiecewiseFunctionItem(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPlot(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPlotBar(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPlotGrid(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPlotHistogram2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPlotLine(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPlotStacked(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPlotParallelCoordinates(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPlotPoints(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkScalarsToColorsItem(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTooltipItem(PyObject *, const char *); }

static PyMethodDef PyvtkChartsPython_ClassMethods[] = {
{NULL, NULL, 0, NULL}};

static void real_initvtkChartsPython(const char *modulename);

extern  "C" { void initvtkChartsPython(); }

void initvtkChartsPython()
{
  static const char modulename[] = "vtkChartsPython";
  real_initvtkChartsPython(modulename);
}

extern  "C" { void initlibvtkChartsPython(); }

void initlibvtkChartsPython()
{
  static const char modulename[] = "libvtkChartsPython";
  real_initvtkChartsPython(modulename);
}

void real_initvtkChartsPython(const char *modulename)
{
  PyObject *m, *d;

  m = Py_InitModule((char*)modulename, PyvtkChartsPython_ClassMethods);
  d = PyModule_GetDict(m);
  if (!d)
    {
    Py_FatalError((char*)"can't get dictionary for module vtkChartsPython");
    }
  PyVTKAddFile_vtkAbstractContextItem(d, modulename);
  PyVTKAddFile_vtkAxis(d, modulename);
  PyVTKAddFile_vtkBlockItem(d, modulename);
  PyVTKAddFile_vtkBrush(d, modulename);
  PyVTKAddFile_vtkChart(d, modulename);
  PyVTKAddFile_vtkChartLegend(d, modulename);
  PyVTKAddFile_vtkChartHistogram2D(d, modulename);
  PyVTKAddFile_vtkChartParallelCoordinates(d, modulename);
  PyVTKAddFile_vtkChartXY(d, modulename);
  PyVTKAddFile_vtkChartPie(d, modulename);
  PyVTKAddFile_vtkColorLegend(d, modulename);
  PyVTKAddFile_vtkPlotPie(d, modulename);
  PyVTKAddFile_vtkColorSeries(d, modulename);
  PyVTKAddFile_vtkColorTransferFunctionItem(d, modulename);
  PyVTKAddFile_vtkColorTransferControlPointsItem(d, modulename);
  PyVTKAddFile_vtkCompositeControlPointsItem(d, modulename);
  PyVTKAddFile_vtkCompositeTransferFunctionItem(d, modulename);
  PyVTKAddFile_vtkContext2D(d, modulename);
  PyVTKAddFile_vtkContextActor(d, modulename);
  PyVTKAddFile_vtkContextClip(d, modulename);
  PyVTKAddFile_vtkContextDevice2D(d, modulename);
  PyVTKAddFile_vtkContextInteractorStyle(d, modulename);
  PyVTKAddFile_vtkContextItem(d, modulename);
  PyVTKAddFile_vtkContextMapper2D(d, modulename);
  PyVTKAddFile_vtkContextScene(d, modulename);
  PyVTKAddFile_vtkContextTransform(d, modulename);
  PyVTKAddFile_vtkContextView(d, modulename);
  PyVTKAddFile_vtkControlPointsItem(d, modulename);
  PyVTKAddFile_vtkImageItem(d, modulename);
  PyVTKAddFile_vtkLookupTableItem(d, modulename);
  PyVTKAddFile_vtkPen(d, modulename);
  PyVTKAddFile_vtkPiecewiseControlPointsItem(d, modulename);
  PyVTKAddFile_vtkPiecewiseFunctionItem(d, modulename);
  PyVTKAddFile_vtkPlot(d, modulename);
  PyVTKAddFile_vtkPlotBar(d, modulename);
  PyVTKAddFile_vtkPlotGrid(d, modulename);
  PyVTKAddFile_vtkPlotHistogram2D(d, modulename);
  PyVTKAddFile_vtkPlotLine(d, modulename);
  PyVTKAddFile_vtkPlotStacked(d, modulename);
  PyVTKAddFile_vtkPlotParallelCoordinates(d, modulename);
  PyVTKAddFile_vtkPlotPoints(d, modulename);
  PyVTKAddFile_vtkScalarsToColorsItem(d, modulename);
  PyVTKAddFile_vtkTooltipItem(d, modulename);
}

