// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPython.h"

#include "vtkSystemIncludes.h"
#include <string.h>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings 

extern  "C" {PyObject *PyVTKAddFile_vtkAnnotationLink(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAppendCompositeDataLeaves(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAppendFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAppendPolyData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAppendSelection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkApproximatingSubdivisionFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArcSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAreaContourSpectrumFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArrayCalculator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArrowSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAssignAttribute(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAttributeDataToFieldDataFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAxes(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBandedPolyDataContourFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBlankStructuredGrid(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBlankStructuredGridWithImage(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBlockIdScalars(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBoxClipDataSet(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBrownianPoints(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkButterflySubdivisionFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkButtonSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCellCenters(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCellDataToPointData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCellDerivatives(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCellLocatorInterpolatedVelocityField(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCellQuality(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCleanPolyData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkClipClosedSurface(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkClipConvexPolyData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkClipDataSet(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkClipHyperOctree(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkClipPolyData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkClipVolume(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCoincidentPoints(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCompositeDataGeometryFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCompositeDataProbeFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkConeSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkConnectivityFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkContourFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkContourGrid(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkConvertSelection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCubeSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCursor2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCursor3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCurvatures(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCutter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCylinderSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDashedStreamLine(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataObjectGenerator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataObjectToDataSetFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetEdgeSubdivisionCriterion(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetGradient(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetGradientPrecompute(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetSurfaceFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetToDataObjectFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetTriangleFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDecimatePolylineFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDecimatePro(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDelaunay2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDelaunay3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDensifyPolyData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDicer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDijkstraGraphGeodesicPath(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDijkstraImageGeodesicPath(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDiscreteMarchingCubes(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDiskSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEdgePoints(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEdgeSubdivisionCriterion(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkElevationFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEllipticalButtonSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractArraysOverTime(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractBlock(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractCells(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractDataOverTime(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractDataSets(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractEdges(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractGeometry(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractGrid(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractLevel(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractPolyDataGeometry(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractRectilinearGrid(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractSelectedBlock(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractSelectedFrustum(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractSelectedIds(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractSelectedLocations(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractSelectedPolyDataIds(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractSelectedRows(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractSelectedThresholds(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractSelectionBase(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractSelection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractTemporalFieldData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractTensorComponents(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractUnstructuredGrid(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractVectorComponents(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFeatureEdges(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFieldDataToAttributeDataFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFillHolesFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFrustumSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGeodesicPath(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGeometryFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGlyph2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGlyph3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGlyphSource2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGradientFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGraphGeodesicPath(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGraphLayoutFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGraphToPoints(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGraphToPolyData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGridSynchronizedTemplates3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHedgeHog(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHierarchicalDataExtractDataSets(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHierarchicalDataExtractLevel(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHierarchicalDataLevelFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHierarchicalDataSetGeometryFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHull(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHyperOctreeClipCutPointsGrabber(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHyperOctreeContourFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHyperOctreeCutter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHyperOctreeDepth(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHyperOctreeDualGridContourFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHyperOctreeFractalSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHyperOctreeLimiter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHyperOctreeSampleFunction(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHyperOctreeSurfaceFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHyperOctreeToUniformGridFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHyperStreamline(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkIconGlyphFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkIdFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageDataGeometryFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageMarchingCubes(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImplicitTextureCoords(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInterpolateDataSetAttributes(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInterpolatingSubdivisionFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkKdTreeSelector(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLevelIdScalars(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLinearExtrusionFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLinearSubdivisionFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLineSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLinkEdgels(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLoopSubdivisionFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMarchingContourFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMarchingCubes(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMarchingSquares(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMaskFields(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMaskPoints(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMaskPolyData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMassProperties(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMatrixMathFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMergeCells(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMergeDataObjectFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMergeFields(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMergeFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMeshQuality(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkModelMetadata(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkModifiedBSPTree(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMultiBlockDataGroupFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMultiBlockMergeFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMultiThreshold(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOBBDicer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOBBTree(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOutlineCornerFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOutlineCornerSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOutlineFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOutlineSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParametricFunctionSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPlaneSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPlatonicSolidSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPointDataToCellData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPointSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyDataConnectivityFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyDataNormals(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyDataPointSampler(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyDataStreamer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyDataToReebGraphFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProbeFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProbePolyhedron(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProbeSelectedLocations(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProgrammableAttributeDataFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProgrammableDataObjectSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProgrammableFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProgrammableGlyphFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProgrammableSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProjectedTexture(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuadraturePointInterpolator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuadraturePointsGenerator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuadratureSchemeDictionaryGenerator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuadricClustering(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuadricDecimation(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuantizePolyDataPoints(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRandomAttributeGenerator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRearrangeFields(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRectangularButtonSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRectilinearGridClip(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRectilinearGridGeometryFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRectilinearGridToTetrahedra(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRectilinearSynchronizedTemplates(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRecursiveDividingCubes(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkReebGraphSimplificationFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkReebGraphSurfaceSkeletonFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkReebGraphVolumeSkeletonFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkReflectionFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRegularPolygonSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkReverseSense(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRibbonFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRotationalExtrusionFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRotationFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRuledSurfaceFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSectorSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSelectEnclosedPoints(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSelectionSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSelectPolyData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkShrinkFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkShrinkPolyData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSimpleElevationFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSliceCubes(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSmoothPolyDataFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSpatialRepresentationFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSpherePuzzleArrows(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSpherePuzzle(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSphereSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSplineFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSplitField(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStreamer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStreamingTessellator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStreamLine(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStreamPoints(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStreamTracer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStripper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredGridClip(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredGridGeometryFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredGridOutlineFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredPointsGeometryFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSubdivideTetra(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSubPixelPositionEdgels(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSuperquadricSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSynchronizedTemplates2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSynchronizedTemplates3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSynchronizedTemplatesCutter3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTableBasedClipDataSet(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTableToPolyData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTableToStructuredGrid(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTemporalPathLineFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTemporalStatistics(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTensorGlyph(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTessellatorFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTessellatedBoxSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTextSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTexturedSphereSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTextureMapToCylinder(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTextureMapToPlane(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTextureMapToSphere(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkThreshold(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkThresholdPoints(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkThresholdTextureCoords(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTimeSourceExample(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTransformCoordinateSystems(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTransformFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTransformPolyDataFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTransformTextureCoords(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTriangleFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTriangularTCoords(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTubeFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUncertaintyTubeFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridGeometryFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridToReebGraphFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVectorDot(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVectorNorm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVertexGlyphFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumeContourSpectrumFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVoxelContoursToSurfaceFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkWarpLens(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkWarpScalar(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkWarpTo(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkWarpVector(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkWindowedSincPolyDataFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkYoungsMaterialInterface(PyObject *, const char *); }

static PyMethodDef PyvtkGraphicsPython_ClassMethods[] = {
{NULL, NULL, 0, NULL}};

static void real_initvtkGraphicsPython(const char *modulename);

extern  "C" { void initvtkGraphicsPython(); }

void initvtkGraphicsPython()
{
  static const char modulename[] = "vtkGraphicsPython";
  real_initvtkGraphicsPython(modulename);
}

extern  "C" { void initlibvtkGraphicsPython(); }

void initlibvtkGraphicsPython()
{
  static const char modulename[] = "libvtkGraphicsPython";
  real_initvtkGraphicsPython(modulename);
}

void real_initvtkGraphicsPython(const char *modulename)
{
  PyObject *m, *d;

  m = Py_InitModule((char*)modulename, PyvtkGraphicsPython_ClassMethods);
  d = PyModule_GetDict(m);
  if (!d)
    {
    Py_FatalError((char*)"can't get dictionary for module vtkGraphicsPython");
    }
  PyVTKAddFile_vtkAnnotationLink(d, modulename);
  PyVTKAddFile_vtkAppendCompositeDataLeaves(d, modulename);
  PyVTKAddFile_vtkAppendFilter(d, modulename);
  PyVTKAddFile_vtkAppendPolyData(d, modulename);
  PyVTKAddFile_vtkAppendSelection(d, modulename);
  PyVTKAddFile_vtkApproximatingSubdivisionFilter(d, modulename);
  PyVTKAddFile_vtkArcSource(d, modulename);
  PyVTKAddFile_vtkAreaContourSpectrumFilter(d, modulename);
  PyVTKAddFile_vtkArrayCalculator(d, modulename);
  PyVTKAddFile_vtkArrowSource(d, modulename);
  PyVTKAddFile_vtkAssignAttribute(d, modulename);
  PyVTKAddFile_vtkAttributeDataToFieldDataFilter(d, modulename);
  PyVTKAddFile_vtkAxes(d, modulename);
  PyVTKAddFile_vtkBandedPolyDataContourFilter(d, modulename);
  PyVTKAddFile_vtkBlankStructuredGrid(d, modulename);
  PyVTKAddFile_vtkBlankStructuredGridWithImage(d, modulename);
  PyVTKAddFile_vtkBlockIdScalars(d, modulename);
  PyVTKAddFile_vtkBoxClipDataSet(d, modulename);
  PyVTKAddFile_vtkBrownianPoints(d, modulename);
  PyVTKAddFile_vtkButterflySubdivisionFilter(d, modulename);
  PyVTKAddFile_vtkButtonSource(d, modulename);
  PyVTKAddFile_vtkCellCenters(d, modulename);
  PyVTKAddFile_vtkCellDataToPointData(d, modulename);
  PyVTKAddFile_vtkCellDerivatives(d, modulename);
  PyVTKAddFile_vtkCellLocatorInterpolatedVelocityField(d, modulename);
  PyVTKAddFile_vtkCellQuality(d, modulename);
  PyVTKAddFile_vtkCleanPolyData(d, modulename);
  PyVTKAddFile_vtkClipClosedSurface(d, modulename);
  PyVTKAddFile_vtkClipConvexPolyData(d, modulename);
  PyVTKAddFile_vtkClipDataSet(d, modulename);
  PyVTKAddFile_vtkClipHyperOctree(d, modulename);
  PyVTKAddFile_vtkClipPolyData(d, modulename);
  PyVTKAddFile_vtkClipVolume(d, modulename);
  PyVTKAddFile_vtkCoincidentPoints(d, modulename);
  PyVTKAddFile_vtkCompositeDataGeometryFilter(d, modulename);
  PyVTKAddFile_vtkCompositeDataProbeFilter(d, modulename);
  PyVTKAddFile_vtkConeSource(d, modulename);
  PyVTKAddFile_vtkConnectivityFilter(d, modulename);
  PyVTKAddFile_vtkContourFilter(d, modulename);
  PyVTKAddFile_vtkContourGrid(d, modulename);
  PyVTKAddFile_vtkConvertSelection(d, modulename);
  PyVTKAddFile_vtkCubeSource(d, modulename);
  PyVTKAddFile_vtkCursor2D(d, modulename);
  PyVTKAddFile_vtkCursor3D(d, modulename);
  PyVTKAddFile_vtkCurvatures(d, modulename);
  PyVTKAddFile_vtkCutter(d, modulename);
  PyVTKAddFile_vtkCylinderSource(d, modulename);
  PyVTKAddFile_vtkDashedStreamLine(d, modulename);
  PyVTKAddFile_vtkDataObjectGenerator(d, modulename);
  PyVTKAddFile_vtkDataObjectToDataSetFilter(d, modulename);
  PyVTKAddFile_vtkDataSetEdgeSubdivisionCriterion(d, modulename);
  PyVTKAddFile_vtkDataSetGradient(d, modulename);
  PyVTKAddFile_vtkDataSetGradientPrecompute(d, modulename);
  PyVTKAddFile_vtkDataSetSurfaceFilter(d, modulename);
  PyVTKAddFile_vtkDataSetToDataObjectFilter(d, modulename);
  PyVTKAddFile_vtkDataSetTriangleFilter(d, modulename);
  PyVTKAddFile_vtkDecimatePolylineFilter(d, modulename);
  PyVTKAddFile_vtkDecimatePro(d, modulename);
  PyVTKAddFile_vtkDelaunay2D(d, modulename);
  PyVTKAddFile_vtkDelaunay3D(d, modulename);
  PyVTKAddFile_vtkDensifyPolyData(d, modulename);
  PyVTKAddFile_vtkDicer(d, modulename);
  PyVTKAddFile_vtkDijkstraGraphGeodesicPath(d, modulename);
  PyVTKAddFile_vtkDijkstraImageGeodesicPath(d, modulename);
  PyVTKAddFile_vtkDiscreteMarchingCubes(d, modulename);
  PyVTKAddFile_vtkDiskSource(d, modulename);
  PyVTKAddFile_vtkEdgePoints(d, modulename);
  PyVTKAddFile_vtkEdgeSubdivisionCriterion(d, modulename);
  PyVTKAddFile_vtkElevationFilter(d, modulename);
  PyVTKAddFile_vtkEllipticalButtonSource(d, modulename);
  PyVTKAddFile_vtkExtractArraysOverTime(d, modulename);
  PyVTKAddFile_vtkExtractBlock(d, modulename);
  PyVTKAddFile_vtkExtractCells(d, modulename);
  PyVTKAddFile_vtkExtractDataOverTime(d, modulename);
  PyVTKAddFile_vtkExtractDataSets(d, modulename);
  PyVTKAddFile_vtkExtractEdges(d, modulename);
  PyVTKAddFile_vtkExtractGeometry(d, modulename);
  PyVTKAddFile_vtkExtractGrid(d, modulename);
  PyVTKAddFile_vtkExtractLevel(d, modulename);
  PyVTKAddFile_vtkExtractPolyDataGeometry(d, modulename);
  PyVTKAddFile_vtkExtractRectilinearGrid(d, modulename);
  PyVTKAddFile_vtkExtractSelectedBlock(d, modulename);
  PyVTKAddFile_vtkExtractSelectedFrustum(d, modulename);
  PyVTKAddFile_vtkExtractSelectedIds(d, modulename);
  PyVTKAddFile_vtkExtractSelectedLocations(d, modulename);
  PyVTKAddFile_vtkExtractSelectedPolyDataIds(d, modulename);
  PyVTKAddFile_vtkExtractSelectedRows(d, modulename);
  PyVTKAddFile_vtkExtractSelectedThresholds(d, modulename);
  PyVTKAddFile_vtkExtractSelectionBase(d, modulename);
  PyVTKAddFile_vtkExtractSelection(d, modulename);
  PyVTKAddFile_vtkExtractTemporalFieldData(d, modulename);
  PyVTKAddFile_vtkExtractTensorComponents(d, modulename);
  PyVTKAddFile_vtkExtractUnstructuredGrid(d, modulename);
  PyVTKAddFile_vtkExtractVectorComponents(d, modulename);
  PyVTKAddFile_vtkFeatureEdges(d, modulename);
  PyVTKAddFile_vtkFieldDataToAttributeDataFilter(d, modulename);
  PyVTKAddFile_vtkFillHolesFilter(d, modulename);
  PyVTKAddFile_vtkFrustumSource(d, modulename);
  PyVTKAddFile_vtkGeodesicPath(d, modulename);
  PyVTKAddFile_vtkGeometryFilter(d, modulename);
  PyVTKAddFile_vtkGlyph2D(d, modulename);
  PyVTKAddFile_vtkGlyph3D(d, modulename);
  PyVTKAddFile_vtkGlyphSource2D(d, modulename);
  PyVTKAddFile_vtkGradientFilter(d, modulename);
  PyVTKAddFile_vtkGraphGeodesicPath(d, modulename);
  PyVTKAddFile_vtkGraphLayoutFilter(d, modulename);
  PyVTKAddFile_vtkGraphToPoints(d, modulename);
  PyVTKAddFile_vtkGraphToPolyData(d, modulename);
  PyVTKAddFile_vtkGridSynchronizedTemplates3D(d, modulename);
  PyVTKAddFile_vtkHedgeHog(d, modulename);
  PyVTKAddFile_vtkHierarchicalDataExtractDataSets(d, modulename);
  PyVTKAddFile_vtkHierarchicalDataExtractLevel(d, modulename);
  PyVTKAddFile_vtkHierarchicalDataLevelFilter(d, modulename);
  PyVTKAddFile_vtkHierarchicalDataSetGeometryFilter(d, modulename);
  PyVTKAddFile_vtkHull(d, modulename);
  PyVTKAddFile_vtkHyperOctreeClipCutPointsGrabber(d, modulename);
  PyVTKAddFile_vtkHyperOctreeContourFilter(d, modulename);
  PyVTKAddFile_vtkHyperOctreeCutter(d, modulename);
  PyVTKAddFile_vtkHyperOctreeDepth(d, modulename);
  PyVTKAddFile_vtkHyperOctreeDualGridContourFilter(d, modulename);
  PyVTKAddFile_vtkHyperOctreeFractalSource(d, modulename);
  PyVTKAddFile_vtkHyperOctreeLimiter(d, modulename);
  PyVTKAddFile_vtkHyperOctreeSampleFunction(d, modulename);
  PyVTKAddFile_vtkHyperOctreeSurfaceFilter(d, modulename);
  PyVTKAddFile_vtkHyperOctreeToUniformGridFilter(d, modulename);
  PyVTKAddFile_vtkHyperStreamline(d, modulename);
  PyVTKAddFile_vtkIconGlyphFilter(d, modulename);
  PyVTKAddFile_vtkIdFilter(d, modulename);
  PyVTKAddFile_vtkImageDataGeometryFilter(d, modulename);
  PyVTKAddFile_vtkImageMarchingCubes(d, modulename);
  PyVTKAddFile_vtkImplicitTextureCoords(d, modulename);
  PyVTKAddFile_vtkInterpolateDataSetAttributes(d, modulename);
  PyVTKAddFile_vtkInterpolatingSubdivisionFilter(d, modulename);
  PyVTKAddFile_vtkKdTreeSelector(d, modulename);
  PyVTKAddFile_vtkLevelIdScalars(d, modulename);
  PyVTKAddFile_vtkLinearExtrusionFilter(d, modulename);
  PyVTKAddFile_vtkLinearSubdivisionFilter(d, modulename);
  PyVTKAddFile_vtkLineSource(d, modulename);
  PyVTKAddFile_vtkLinkEdgels(d, modulename);
  PyVTKAddFile_vtkLoopSubdivisionFilter(d, modulename);
  PyVTKAddFile_vtkMarchingContourFilter(d, modulename);
  PyVTKAddFile_vtkMarchingCubes(d, modulename);
  PyVTKAddFile_vtkMarchingSquares(d, modulename);
  PyVTKAddFile_vtkMaskFields(d, modulename);
  PyVTKAddFile_vtkMaskPoints(d, modulename);
  PyVTKAddFile_vtkMaskPolyData(d, modulename);
  PyVTKAddFile_vtkMassProperties(d, modulename);
  PyVTKAddFile_vtkMatrixMathFilter(d, modulename);
  PyVTKAddFile_vtkMergeCells(d, modulename);
  PyVTKAddFile_vtkMergeDataObjectFilter(d, modulename);
  PyVTKAddFile_vtkMergeFields(d, modulename);
  PyVTKAddFile_vtkMergeFilter(d, modulename);
  PyVTKAddFile_vtkMeshQuality(d, modulename);
  PyVTKAddFile_vtkModelMetadata(d, modulename);
  PyVTKAddFile_vtkModifiedBSPTree(d, modulename);
  PyVTKAddFile_vtkMultiBlockDataGroupFilter(d, modulename);
  PyVTKAddFile_vtkMultiBlockMergeFilter(d, modulename);
  PyVTKAddFile_vtkMultiThreshold(d, modulename);
  PyVTKAddFile_vtkOBBDicer(d, modulename);
  PyVTKAddFile_vtkOBBTree(d, modulename);
  PyVTKAddFile_vtkOutlineCornerFilter(d, modulename);
  PyVTKAddFile_vtkOutlineCornerSource(d, modulename);
  PyVTKAddFile_vtkOutlineFilter(d, modulename);
  PyVTKAddFile_vtkOutlineSource(d, modulename);
  PyVTKAddFile_vtkParametricFunctionSource(d, modulename);
  PyVTKAddFile_vtkPlaneSource(d, modulename);
  PyVTKAddFile_vtkPlatonicSolidSource(d, modulename);
  PyVTKAddFile_vtkPointDataToCellData(d, modulename);
  PyVTKAddFile_vtkPointSource(d, modulename);
  PyVTKAddFile_vtkPolyDataConnectivityFilter(d, modulename);
  PyVTKAddFile_vtkPolyDataNormals(d, modulename);
  PyVTKAddFile_vtkPolyDataPointSampler(d, modulename);
  PyVTKAddFile_vtkPolyDataStreamer(d, modulename);
  PyVTKAddFile_vtkPolyDataToReebGraphFilter(d, modulename);
  PyVTKAddFile_vtkProbeFilter(d, modulename);
  PyVTKAddFile_vtkProbePolyhedron(d, modulename);
  PyVTKAddFile_vtkProbeSelectedLocations(d, modulename);
  PyVTKAddFile_vtkProgrammableAttributeDataFilter(d, modulename);
  PyVTKAddFile_vtkProgrammableDataObjectSource(d, modulename);
  PyVTKAddFile_vtkProgrammableFilter(d, modulename);
  PyVTKAddFile_vtkProgrammableGlyphFilter(d, modulename);
  PyVTKAddFile_vtkProgrammableSource(d, modulename);
  PyVTKAddFile_vtkProjectedTexture(d, modulename);
  PyVTKAddFile_vtkQuadraturePointInterpolator(d, modulename);
  PyVTKAddFile_vtkQuadraturePointsGenerator(d, modulename);
  PyVTKAddFile_vtkQuadratureSchemeDictionaryGenerator(d, modulename);
  PyVTKAddFile_vtkQuadricClustering(d, modulename);
  PyVTKAddFile_vtkQuadricDecimation(d, modulename);
  PyVTKAddFile_vtkQuantizePolyDataPoints(d, modulename);
  PyVTKAddFile_vtkRandomAttributeGenerator(d, modulename);
  PyVTKAddFile_vtkRearrangeFields(d, modulename);
  PyVTKAddFile_vtkRectangularButtonSource(d, modulename);
  PyVTKAddFile_vtkRectilinearGridClip(d, modulename);
  PyVTKAddFile_vtkRectilinearGridGeometryFilter(d, modulename);
  PyVTKAddFile_vtkRectilinearGridToTetrahedra(d, modulename);
  PyVTKAddFile_vtkRectilinearSynchronizedTemplates(d, modulename);
  PyVTKAddFile_vtkRecursiveDividingCubes(d, modulename);
  PyVTKAddFile_vtkReebGraphSimplificationFilter(d, modulename);
  PyVTKAddFile_vtkReebGraphSurfaceSkeletonFilter(d, modulename);
  PyVTKAddFile_vtkReebGraphVolumeSkeletonFilter(d, modulename);
  PyVTKAddFile_vtkReflectionFilter(d, modulename);
  PyVTKAddFile_vtkRegularPolygonSource(d, modulename);
  PyVTKAddFile_vtkReverseSense(d, modulename);
  PyVTKAddFile_vtkRibbonFilter(d, modulename);
  PyVTKAddFile_vtkRotationalExtrusionFilter(d, modulename);
  PyVTKAddFile_vtkRotationFilter(d, modulename);
  PyVTKAddFile_vtkRuledSurfaceFilter(d, modulename);
  PyVTKAddFile_vtkSectorSource(d, modulename);
  PyVTKAddFile_vtkSelectEnclosedPoints(d, modulename);
  PyVTKAddFile_vtkSelectionSource(d, modulename);
  PyVTKAddFile_vtkSelectPolyData(d, modulename);
  PyVTKAddFile_vtkShrinkFilter(d, modulename);
  PyVTKAddFile_vtkShrinkPolyData(d, modulename);
  PyVTKAddFile_vtkSimpleElevationFilter(d, modulename);
  PyVTKAddFile_vtkSliceCubes(d, modulename);
  PyVTKAddFile_vtkSmoothPolyDataFilter(d, modulename);
  PyVTKAddFile_vtkSpatialRepresentationFilter(d, modulename);
  PyVTKAddFile_vtkSpherePuzzleArrows(d, modulename);
  PyVTKAddFile_vtkSpherePuzzle(d, modulename);
  PyVTKAddFile_vtkSphereSource(d, modulename);
  PyVTKAddFile_vtkSplineFilter(d, modulename);
  PyVTKAddFile_vtkSplitField(d, modulename);
  PyVTKAddFile_vtkStreamer(d, modulename);
  PyVTKAddFile_vtkStreamingTessellator(d, modulename);
  PyVTKAddFile_vtkStreamLine(d, modulename);
  PyVTKAddFile_vtkStreamPoints(d, modulename);
  PyVTKAddFile_vtkStreamTracer(d, modulename);
  PyVTKAddFile_vtkStripper(d, modulename);
  PyVTKAddFile_vtkStructuredGridClip(d, modulename);
  PyVTKAddFile_vtkStructuredGridGeometryFilter(d, modulename);
  PyVTKAddFile_vtkStructuredGridOutlineFilter(d, modulename);
  PyVTKAddFile_vtkStructuredPointsGeometryFilter(d, modulename);
  PyVTKAddFile_vtkSubdivideTetra(d, modulename);
  PyVTKAddFile_vtkSubPixelPositionEdgels(d, modulename);
  PyVTKAddFile_vtkSuperquadricSource(d, modulename);
  PyVTKAddFile_vtkSynchronizedTemplates2D(d, modulename);
  PyVTKAddFile_vtkSynchronizedTemplates3D(d, modulename);
  PyVTKAddFile_vtkSynchronizedTemplatesCutter3D(d, modulename);
  PyVTKAddFile_vtkTableBasedClipDataSet(d, modulename);
  PyVTKAddFile_vtkTableToPolyData(d, modulename);
  PyVTKAddFile_vtkTableToStructuredGrid(d, modulename);
  PyVTKAddFile_vtkTemporalPathLineFilter(d, modulename);
  PyVTKAddFile_vtkTemporalStatistics(d, modulename);
  PyVTKAddFile_vtkTensorGlyph(d, modulename);
  PyVTKAddFile_vtkTessellatorFilter(d, modulename);
  PyVTKAddFile_vtkTessellatedBoxSource(d, modulename);
  PyVTKAddFile_vtkTextSource(d, modulename);
  PyVTKAddFile_vtkTexturedSphereSource(d, modulename);
  PyVTKAddFile_vtkTextureMapToCylinder(d, modulename);
  PyVTKAddFile_vtkTextureMapToPlane(d, modulename);
  PyVTKAddFile_vtkTextureMapToSphere(d, modulename);
  PyVTKAddFile_vtkThreshold(d, modulename);
  PyVTKAddFile_vtkThresholdPoints(d, modulename);
  PyVTKAddFile_vtkThresholdTextureCoords(d, modulename);
  PyVTKAddFile_vtkTimeSourceExample(d, modulename);
  PyVTKAddFile_vtkTransformCoordinateSystems(d, modulename);
  PyVTKAddFile_vtkTransformFilter(d, modulename);
  PyVTKAddFile_vtkTransformPolyDataFilter(d, modulename);
  PyVTKAddFile_vtkTransformTextureCoords(d, modulename);
  PyVTKAddFile_vtkTriangleFilter(d, modulename);
  PyVTKAddFile_vtkTriangularTCoords(d, modulename);
  PyVTKAddFile_vtkTubeFilter(d, modulename);
  PyVTKAddFile_vtkUncertaintyTubeFilter(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridGeometryFilter(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridToReebGraphFilter(d, modulename);
  PyVTKAddFile_vtkVectorDot(d, modulename);
  PyVTKAddFile_vtkVectorNorm(d, modulename);
  PyVTKAddFile_vtkVertexGlyphFilter(d, modulename);
  PyVTKAddFile_vtkVolumeContourSpectrumFilter(d, modulename);
  PyVTKAddFile_vtkVoxelContoursToSurfaceFilter(d, modulename);
  PyVTKAddFile_vtkWarpLens(d, modulename);
  PyVTKAddFile_vtkWarpScalar(d, modulename);
  PyVTKAddFile_vtkWarpTo(d, modulename);
  PyVTKAddFile_vtkWarpVector(d, modulename);
  PyVTKAddFile_vtkWindowedSincPolyDataFilter(d, modulename);
  PyVTKAddFile_vtkYoungsMaterialInterface(d, modulename);
}

