// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPython.h"

#include "vtkSystemIncludes.h"
#include <string.h>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings 

extern  "C" {PyObject *PyVTKAddFile_vtkBranchExtentTranslator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCachingInterpolatedVelocityField(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkClientServerSynchronizedRenderers(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCollectGraph(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCollectPolyData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCollectTable(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCommunicator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCompositedSynchronizedRenderers(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCompositer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCompressCompositer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCutMaterial(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDistributedDataFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDistributedStreamTracer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDummyCommunicator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDummyController(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDuplicatePolyData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEnSightWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractCTHPart(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractPiece(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractPolyDataPiece(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractUnstructuredGridPiece(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractUserDefinedPiece(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMPIImageReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMultiProcessController(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParallelFactory(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPassThroughFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPCellDataToPointData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPChacoReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPCosmoHaloFinder(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPCosmoReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPDataSetReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPDataSetWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPExtractArraysOverTime(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPHardwareSelector(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPieceRequestFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPieceScalars(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPKdTree(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPLinearExtrusionFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPNrrdReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPOPReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPOpenFOAMReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPOutlineCornerFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPOutlineFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPPolyDataNormals(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPProbeFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProcess(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProcessGroup(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProcessIdScalars(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPReflectionFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPSLACReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPSphereSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPStreamTracer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPTableToStructuredGrid(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRectilinearGridOutlineFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSocketCommunicator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSocketController(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSubCommunicator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSubGroup(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTemporalFractal(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTemporalInterpolatedVelocityField(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTemporalStreamTracer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTransmitImageDataPiece(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTransmitPolyDataPiece(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTransmitRectilinearGridPiece(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTransmitStructuredGridPiece(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTransmitUnstructuredGridPiece(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVPICReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkWindBladeReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPHierarchicalBoxDataWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPMultiBlockDataWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkClientServerCompositePass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCompositeRenderManager(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageRenderManager(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMemoryLimitImageDataStreamer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParallelRenderManager(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPImageWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPipelineSize(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSynchronizedRenderers(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSynchronizedRenderWindows(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTreeCompositer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExodusIIWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMPICommunicator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMPIController(PyObject *, const char *); }

static PyMethodDef PyvtkParallelPython_ClassMethods[] = {
{NULL, NULL, 0, NULL}};

static void real_initvtkParallelPython(const char *modulename);

extern  "C" { void initvtkParallelPython(); }

void initvtkParallelPython()
{
  static const char modulename[] = "vtkParallelPython";
  real_initvtkParallelPython(modulename);
}

extern  "C" { void initlibvtkParallelPython(); }

void initlibvtkParallelPython()
{
  static const char modulename[] = "libvtkParallelPython";
  real_initvtkParallelPython(modulename);
}

void real_initvtkParallelPython(const char *modulename)
{
  PyObject *m, *d;

  m = Py_InitModule((char*)modulename, PyvtkParallelPython_ClassMethods);
  d = PyModule_GetDict(m);
  if (!d)
    {
    Py_FatalError((char*)"can't get dictionary for module vtkParallelPython");
    }
  PyVTKAddFile_vtkBranchExtentTranslator(d, modulename);
  PyVTKAddFile_vtkCachingInterpolatedVelocityField(d, modulename);
  PyVTKAddFile_vtkClientServerSynchronizedRenderers(d, modulename);
  PyVTKAddFile_vtkCollectGraph(d, modulename);
  PyVTKAddFile_vtkCollectPolyData(d, modulename);
  PyVTKAddFile_vtkCollectTable(d, modulename);
  PyVTKAddFile_vtkCommunicator(d, modulename);
  PyVTKAddFile_vtkCompositedSynchronizedRenderers(d, modulename);
  PyVTKAddFile_vtkCompositer(d, modulename);
  PyVTKAddFile_vtkCompressCompositer(d, modulename);
  PyVTKAddFile_vtkCutMaterial(d, modulename);
  PyVTKAddFile_vtkDistributedDataFilter(d, modulename);
  PyVTKAddFile_vtkDistributedStreamTracer(d, modulename);
  PyVTKAddFile_vtkDummyCommunicator(d, modulename);
  PyVTKAddFile_vtkDummyController(d, modulename);
  PyVTKAddFile_vtkDuplicatePolyData(d, modulename);
  PyVTKAddFile_vtkEnSightWriter(d, modulename);
  PyVTKAddFile_vtkExtractCTHPart(d, modulename);
  PyVTKAddFile_vtkExtractPiece(d, modulename);
  PyVTKAddFile_vtkExtractPolyDataPiece(d, modulename);
  PyVTKAddFile_vtkExtractUnstructuredGridPiece(d, modulename);
  PyVTKAddFile_vtkExtractUserDefinedPiece(d, modulename);
  PyVTKAddFile_vtkMPIImageReader(d, modulename);
  PyVTKAddFile_vtkMultiProcessController(d, modulename);
  PyVTKAddFile_vtkParallelFactory(d, modulename);
  PyVTKAddFile_vtkPassThroughFilter(d, modulename);
  PyVTKAddFile_vtkPCellDataToPointData(d, modulename);
  PyVTKAddFile_vtkPChacoReader(d, modulename);
  PyVTKAddFile_vtkPCosmoHaloFinder(d, modulename);
  PyVTKAddFile_vtkPCosmoReader(d, modulename);
  PyVTKAddFile_vtkPDataSetReader(d, modulename);
  PyVTKAddFile_vtkPDataSetWriter(d, modulename);
  PyVTKAddFile_vtkPExtractArraysOverTime(d, modulename);
  PyVTKAddFile_vtkPHardwareSelector(d, modulename);
  PyVTKAddFile_vtkPieceRequestFilter(d, modulename);
  PyVTKAddFile_vtkPieceScalars(d, modulename);
  PyVTKAddFile_vtkPKdTree(d, modulename);
  PyVTKAddFile_vtkPLinearExtrusionFilter(d, modulename);
  PyVTKAddFile_vtkPNrrdReader(d, modulename);
  PyVTKAddFile_vtkPOPReader(d, modulename);
  PyVTKAddFile_vtkPOpenFOAMReader(d, modulename);
  PyVTKAddFile_vtkPOutlineCornerFilter(d, modulename);
  PyVTKAddFile_vtkPOutlineFilter(d, modulename);
  PyVTKAddFile_vtkPPolyDataNormals(d, modulename);
  PyVTKAddFile_vtkPProbeFilter(d, modulename);
  PyVTKAddFile_vtkProcess(d, modulename);
  PyVTKAddFile_vtkProcessGroup(d, modulename);
  PyVTKAddFile_vtkProcessIdScalars(d, modulename);
  PyVTKAddFile_vtkPReflectionFilter(d, modulename);
  PyVTKAddFile_vtkPSLACReader(d, modulename);
  PyVTKAddFile_vtkPSphereSource(d, modulename);
  PyVTKAddFile_vtkPStreamTracer(d, modulename);
  PyVTKAddFile_vtkPTableToStructuredGrid(d, modulename);
  PyVTKAddFile_vtkRectilinearGridOutlineFilter(d, modulename);
  PyVTKAddFile_vtkSocketCommunicator(d, modulename);
  PyVTKAddFile_vtkSocketController(d, modulename);
  PyVTKAddFile_vtkSubCommunicator(d, modulename);
  PyVTKAddFile_vtkSubGroup(d, modulename);
  PyVTKAddFile_vtkTemporalFractal(d, modulename);
  PyVTKAddFile_vtkTemporalInterpolatedVelocityField(d, modulename);
  PyVTKAddFile_vtkTemporalStreamTracer(d, modulename);
  PyVTKAddFile_vtkTransmitImageDataPiece(d, modulename);
  PyVTKAddFile_vtkTransmitPolyDataPiece(d, modulename);
  PyVTKAddFile_vtkTransmitRectilinearGridPiece(d, modulename);
  PyVTKAddFile_vtkTransmitStructuredGridPiece(d, modulename);
  PyVTKAddFile_vtkTransmitUnstructuredGridPiece(d, modulename);
  PyVTKAddFile_vtkVPICReader(d, modulename);
  PyVTKAddFile_vtkWindBladeReader(d, modulename);
  PyVTKAddFile_vtkXMLPHierarchicalBoxDataWriter(d, modulename);
  PyVTKAddFile_vtkXMLPMultiBlockDataWriter(d, modulename);
  PyVTKAddFile_vtkClientServerCompositePass(d, modulename);
  PyVTKAddFile_vtkCompositeRenderManager(d, modulename);
  PyVTKAddFile_vtkImageRenderManager(d, modulename);
  PyVTKAddFile_vtkMemoryLimitImageDataStreamer(d, modulename);
  PyVTKAddFile_vtkParallelRenderManager(d, modulename);
  PyVTKAddFile_vtkPImageWriter(d, modulename);
  PyVTKAddFile_vtkPipelineSize(d, modulename);
  PyVTKAddFile_vtkSynchronizedRenderers(d, modulename);
  PyVTKAddFile_vtkSynchronizedRenderWindows(d, modulename);
  PyVTKAddFile_vtkTreeCompositer(d, modulename);
  PyVTKAddFile_vtkExodusIIWriter(d, modulename);
  PyVTKAddFile_vtkMPICommunicator(d, modulename);
  PyVTKAddFile_vtkMPIController(d, modulename);
}

