# CMake generated Testfile for 
# Source directory: /home/lakers/Downloads/VTK/Infovis/Testing/Cxx
# Build directory: /home/lakers/Downloads/VTK/Infovis/Testing/Cxx
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(TestParallelRandomStatisticsMPI "/usr/bin/mpiexec" "-np" "256" "/home/lakers/Downloads/VTK/bin/./TestParallelRandomStatisticsMPI")
ADD_TEST(TestRandomPContingencyStatisticsMPI "/usr/bin/mpiexec" "-np" "256" "/home/lakers/Downloads/VTK/bin/./TestRandomPContingencyStatisticsMPI")
ADD_TEST(TestRandomPOrderStatisticsMPI "/usr/bin/mpiexec" "-np" "256" "/home/lakers/Downloads/VTK/bin/./TestRandomPOrderStatisticsMPI")
ADD_TEST(TestParallelKMeansStatisticsMPI "/usr/bin/mpiexec" "-np" "256" "/home/lakers/Downloads/VTK/bin/./TestParallelKMeansStatisticsMPI")
ADD_TEST(Infovis-TestArcEdges "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestArcEdges")
ADD_TEST(Infovis-TestAssignCoordinates "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestAssignCoordinates")
ADD_TEST(Infovis-TestCollapseVerticesByArray "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestCollapseVerticesByArray")
ADD_TEST(Infovis-TestContingencyStatistics "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestContingencyStatistics")
ADD_TEST(Infovis-TestCorrelativeStatistics "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestCorrelativeStatistics")
ADD_TEST(Infovis-TestCosmicTreeLayoutStrategy "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestCosmicTreeLayoutStrategy")
ADD_TEST(Infovis-TestDataObjectToTable "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestDataObjectToTable")
ADD_TEST(Infovis-TestDescriptiveStatistics "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestDescriptiveStatistics")
ADD_TEST(Infovis-TestExtractSelectedGraph "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestExtractSelectedGraph")
ADD_TEST(Infovis-TestGraph "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestGraph")
ADD_TEST(Infovis-TestGraphAttributes "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestGraphAttributes")
ADD_TEST(Infovis-TestGraphAlgorithms "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestGraphAlgorithms")
ADD_TEST(Infovis-TestGraphHierarchicalBundle "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestGraphHierarchicalBundle")
ADD_TEST(Infovis-TestGraphLayoutStrategy "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestGraphLayoutStrategy")
ADD_TEST(Infovis-TestGroupLeafVertices "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestGroupLeafVertices")
ADD_TEST(Infovis-TestKdTreeBoxSelection "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestKdTreeBoxSelection")
ADD_TEST(Infovis-TestKMeansStatistics "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestKMeansStatistics")
ADD_TEST(Infovis-TestMergeGraphs "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestMergeGraphs")
ADD_TEST(Infovis-TestMultiCorrelativeStatistics "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestMultiCorrelativeStatistics")
ADD_TEST(Infovis-TestOrderStatistics "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestOrderStatistics")
ADD_TEST(Infovis-TestPassArrays "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestPassArrays")
ADD_TEST(Infovis-TestPassThrough "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestPassThrough")
ADD_TEST(Infovis-TestPCAStatistics "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestPCAStatistics")
ADD_TEST(Infovis-TestPruneTreeFilter "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestPruneTreeFilter")
ADD_TEST(Infovis-TestRandomGraphSource "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestRandomGraphSource")
ADD_TEST(Infovis-TestRemoveIsolatedVertices "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestRemoveIsolatedVertices")
ADD_TEST(Infovis-TestSimple3DCirclesStrategy "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestSimple3DCirclesStrategy")
ADD_TEST(Infovis-TestStreamGraph "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestStreamGraph")
ADD_TEST(Infovis-TestStringToCategory "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestStringToCategory")
ADD_TEST(Infovis-TestTable "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestTable")
ADD_TEST(Infovis-TestTableSplitColumnComponents "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestTableSplitColumnComponents")
ADD_TEST(Infovis-TestTreeMapLayoutStrategy "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestTreeMapLayoutStrategy")
ADD_TEST(Infovis-TestThresholdTable "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestThresholdTable")
ADD_TEST(Infovis-TestVariantArray "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestVariantArray")
ADD_TEST(Infovis-TestVariant "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestVariant")
ADD_TEST(Infovis-TestSQLGraphReader "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestSQLGraphReader")
ADD_TEST(Infovis-TestTimePoint "/home/lakers/Downloads/VTK/bin/InfovisCxxTests" "TestTimePoint")
ADD_TEST(Array-ArrayAPIDenseCoordinates "/home/lakers/Downloads/VTK/bin/InfovisArrayCxxTests" "ArrayAPIDenseCoordinates")
ADD_TEST(Array-ArrayDiagonalMatrixSource "/home/lakers/Downloads/VTK/bin/InfovisArrayCxxTests" "ArrayDiagonalMatrixSource")
ADD_TEST(Array-ArrayDotProductSimilarity "/home/lakers/Downloads/VTK/bin/InfovisArrayCxxTests" "ArrayDotProductSimilarity")
ADD_TEST(Array-ArrayExtractFactoredArray "/home/lakers/Downloads/VTK/bin/InfovisArrayCxxTests" "ArrayExtractFactoredArray")
ADD_TEST(Array-ArrayMatricizeArray "/home/lakers/Downloads/VTK/bin/InfovisArrayCxxTests" "ArrayMatricizeArray")
ADD_TEST(Array-TestArrayNorm "/home/lakers/Downloads/VTK/bin/InfovisArrayCxxTests" "TestArrayNorm")
ADD_TEST(Array-ArrayNormalizeMatrixVectors "/home/lakers/Downloads/VTK/bin/InfovisArrayCxxTests" "ArrayNormalizeMatrixVectors")
ADD_TEST(Array-ArraySparseArrayToTable "/home/lakers/Downloads/VTK/bin/InfovisArrayCxxTests" "ArraySparseArrayToTable")
ADD_TEST(Array-ArrayTableToSparseArray "/home/lakers/Downloads/VTK/bin/InfovisArrayCxxTests" "ArrayTableToSparseArray")
ADD_TEST(Array-ArrayToTable "/home/lakers/Downloads/VTK/bin/InfovisArrayCxxTests" "ArrayToTable")
ADD_TEST(Array-ArrayTransposeMatrix "/home/lakers/Downloads/VTK/bin/InfovisArrayCxxTests" "ArrayTransposeMatrix")
ADD_TEST(Array-TestTableToArray "/home/lakers/Downloads/VTK/bin/InfovisArrayCxxTests" "TestTableToArray")
