// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPython.h"

#include "vtkSystemIncludes.h"
#include <string.h>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings 

extern  "C" {PyObject *PyVTKAddFile_vtkAbstractArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAbstractTransform(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAmoebaMinimizer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAnimationCue(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAnimationScene(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArrayIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAssemblyNode(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAssemblyPath(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAssemblyPaths(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBitArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBitArrayIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBox(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBoxMuellerRandomSequence(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkByteSwap(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCharArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkClientSocket(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCollectionIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkColor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCommand(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkConditionVariable(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkContourValues(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCriticalSection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCylindricalTransform(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataArrayCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataArrayCollectionIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataArraySelection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDebugLeaks(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDirectory(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDoubleArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDynamicLoader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEdgeTable(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtentSplitter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtentTranslator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFastNumericConversion(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFileOutputWindow(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFloatArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFunctionParser(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFunctionSet(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGarbageCollector(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGaussianRandomSequence(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGeneralTransform(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHeap(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHomogeneousTransform(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkIdList(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkIdListCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkIdTypeArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkIdentityTransform(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImplicitFunction(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImplicitFunctionCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformation(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationDataObjectKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationDoubleKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationDoubleVectorKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationIdTypeKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationInformationKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationInformationVectorKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationIntegerKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationIntegerPointerKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationIntegerVectorKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationKeyVectorKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationObjectBaseKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationObjectBaseVectorKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationQuadratureSchemeDefinitionVectorKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationRequestKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationStringKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationStringVectorKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationUnsignedLongKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationVector(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInitialValueProblemSolver(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInstantiator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkIntArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLinearTransform(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLogLookupTable(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLongArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLookupTable(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLookupTableWithEnabling(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMath(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMatrix3x3(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMatrix4x4(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMatrixToHomogeneousTransform(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMatrixToLinearTransform(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMinimalStandardRandomSequence(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMultiThreader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMutexLock(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkObject(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkObjectBase(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkObjectFactory(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkObjectFactoryCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOnePieceExtentTranslator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOutputWindow(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOverrideInformation(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOverrideInformationCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParametricBoy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParametricConicSpiral(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParametricCrossCap(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParametricDini(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParametricEllipsoid(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParametricEnneper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParametricFigure8Klein(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParametricFunction(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParametricKlein(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParametricMobius(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParametricRandomHills(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParametricRoman(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParametricSuperEllipsoid(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParametricSuperToroid(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParametricTorus(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPerspectiveTransform(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPlane(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPlaneCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPlanes(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPoints(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPoints2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolynomialSolversUnivariate(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPriorityQueue(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProp(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPropCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProperty2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuadratureSchemeDefinition(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuadric(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRandomSequence(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRect(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkReferenceCount(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRungeKutta2(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRungeKutta4(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRungeKutta45(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkScalarsToColors(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkServerSocket(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkShortArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSignedCharArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSocket(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSocketCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSortDataArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSphericalTransform(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStringArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredExtent(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredVisibilityConstraint(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTableExtentTranslator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTensor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkThreadMessager(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTimePointUtility(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTimeStamp(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTimerLog(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTransform2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTransform(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTransformCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnicodeStringArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnsignedCharArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnsignedIntArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnsignedLongArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnsignedShortArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVariant(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVariantArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVector(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVersion(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVoidArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkWarpTransform(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkWindow(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkWindowLevelLookupTable(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLDataElement(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLFileOutputWindow(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLongLongArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnsignedLongLongArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTypeInt8Array(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTypeInt16Array(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTypeInt32Array(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTypeInt64Array(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTypeUInt8Array(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTypeUInt16Array(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTypeUInt32Array(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTypeUInt64Array(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTypeFloat32Array(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTypeFloat64Array(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArrayCoordinates(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArrayExtents(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArrayExtentsList(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArrayRange(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArraySort(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArrayWeights(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDenseArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSparseArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTypedArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTypeTemplate(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSystemIncludes(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkType(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMathConfigure(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkConfigure(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_mutable(PyObject *, const char *); }

static PyMethodDef PyvtkCommonPython_ClassMethods[] = {
{NULL, NULL, 0, NULL}};

static void real_initvtkCommonPython(const char *modulename);

extern  "C" { void initvtkCommonPython(); }

void initvtkCommonPython()
{
  static const char modulename[] = "vtkCommonPython";
  real_initvtkCommonPython(modulename);
}

extern  "C" { void initlibvtkCommonPython(); }

void initlibvtkCommonPython()
{
  static const char modulename[] = "libvtkCommonPython";
  real_initvtkCommonPython(modulename);
}

void real_initvtkCommonPython(const char *modulename)
{
  PyObject *m, *d;

  m = Py_InitModule((char*)modulename, PyvtkCommonPython_ClassMethods);
  d = PyModule_GetDict(m);
  if (!d)
    {
    Py_FatalError((char*)"can't get dictionary for module vtkCommonPython");
    }
  PyVTKAddFile_vtkAbstractArray(d, modulename);
  PyVTKAddFile_vtkAbstractTransform(d, modulename);
  PyVTKAddFile_vtkAmoebaMinimizer(d, modulename);
  PyVTKAddFile_vtkAnimationCue(d, modulename);
  PyVTKAddFile_vtkAnimationScene(d, modulename);
  PyVTKAddFile_vtkArrayIterator(d, modulename);
  PyVTKAddFile_vtkAssemblyNode(d, modulename);
  PyVTKAddFile_vtkAssemblyPath(d, modulename);
  PyVTKAddFile_vtkAssemblyPaths(d, modulename);
  PyVTKAddFile_vtkBitArray(d, modulename);
  PyVTKAddFile_vtkBitArrayIterator(d, modulename);
  PyVTKAddFile_vtkBox(d, modulename);
  PyVTKAddFile_vtkBoxMuellerRandomSequence(d, modulename);
  PyVTKAddFile_vtkByteSwap(d, modulename);
  PyVTKAddFile_vtkCharArray(d, modulename);
  PyVTKAddFile_vtkClientSocket(d, modulename);
  PyVTKAddFile_vtkCollection(d, modulename);
  PyVTKAddFile_vtkCollectionIterator(d, modulename);
  PyVTKAddFile_vtkColor(d, modulename);
  PyVTKAddFile_vtkCommand(d, modulename);
  PyVTKAddFile_vtkConditionVariable(d, modulename);
  PyVTKAddFile_vtkContourValues(d, modulename);
  PyVTKAddFile_vtkCriticalSection(d, modulename);
  PyVTKAddFile_vtkCylindricalTransform(d, modulename);
  PyVTKAddFile_vtkDataArray(d, modulename);
  PyVTKAddFile_vtkDataArrayCollection(d, modulename);
  PyVTKAddFile_vtkDataArrayCollectionIterator(d, modulename);
  PyVTKAddFile_vtkDataArraySelection(d, modulename);
  PyVTKAddFile_vtkDebugLeaks(d, modulename);
  PyVTKAddFile_vtkDirectory(d, modulename);
  PyVTKAddFile_vtkDoubleArray(d, modulename);
  PyVTKAddFile_vtkDynamicLoader(d, modulename);
  PyVTKAddFile_vtkEdgeTable(d, modulename);
  PyVTKAddFile_vtkExtentSplitter(d, modulename);
  PyVTKAddFile_vtkExtentTranslator(d, modulename);
  PyVTKAddFile_vtkFastNumericConversion(d, modulename);
  PyVTKAddFile_vtkFileOutputWindow(d, modulename);
  PyVTKAddFile_vtkFloatArray(d, modulename);
  PyVTKAddFile_vtkFunctionParser(d, modulename);
  PyVTKAddFile_vtkFunctionSet(d, modulename);
  PyVTKAddFile_vtkGarbageCollector(d, modulename);
  PyVTKAddFile_vtkGaussianRandomSequence(d, modulename);
  PyVTKAddFile_vtkGeneralTransform(d, modulename);
  PyVTKAddFile_vtkHeap(d, modulename);
  PyVTKAddFile_vtkHomogeneousTransform(d, modulename);
  PyVTKAddFile_vtkIdList(d, modulename);
  PyVTKAddFile_vtkIdListCollection(d, modulename);
  PyVTKAddFile_vtkIdTypeArray(d, modulename);
  PyVTKAddFile_vtkIdentityTransform(d, modulename);
  PyVTKAddFile_vtkImplicitFunction(d, modulename);
  PyVTKAddFile_vtkImplicitFunctionCollection(d, modulename);
  PyVTKAddFile_vtkInformation(d, modulename);
  PyVTKAddFile_vtkInformationDataObjectKey(d, modulename);
  PyVTKAddFile_vtkInformationDoubleKey(d, modulename);
  PyVTKAddFile_vtkInformationDoubleVectorKey(d, modulename);
  PyVTKAddFile_vtkInformationIdTypeKey(d, modulename);
  PyVTKAddFile_vtkInformationInformationKey(d, modulename);
  PyVTKAddFile_vtkInformationInformationVectorKey(d, modulename);
  PyVTKAddFile_vtkInformationIntegerKey(d, modulename);
  PyVTKAddFile_vtkInformationIntegerPointerKey(d, modulename);
  PyVTKAddFile_vtkInformationIntegerVectorKey(d, modulename);
  PyVTKAddFile_vtkInformationIterator(d, modulename);
  PyVTKAddFile_vtkInformationKey(d, modulename);
  PyVTKAddFile_vtkInformationKeyVectorKey(d, modulename);
  PyVTKAddFile_vtkInformationObjectBaseKey(d, modulename);
  PyVTKAddFile_vtkInformationObjectBaseVectorKey(d, modulename);
  PyVTKAddFile_vtkInformationQuadratureSchemeDefinitionVectorKey(d, modulename);
  PyVTKAddFile_vtkInformationRequestKey(d, modulename);
  PyVTKAddFile_vtkInformationStringKey(d, modulename);
  PyVTKAddFile_vtkInformationStringVectorKey(d, modulename);
  PyVTKAddFile_vtkInformationUnsignedLongKey(d, modulename);
  PyVTKAddFile_vtkInformationVector(d, modulename);
  PyVTKAddFile_vtkInitialValueProblemSolver(d, modulename);
  PyVTKAddFile_vtkInstantiator(d, modulename);
  PyVTKAddFile_vtkIntArray(d, modulename);
  PyVTKAddFile_vtkLinearTransform(d, modulename);
  PyVTKAddFile_vtkLogLookupTable(d, modulename);
  PyVTKAddFile_vtkLongArray(d, modulename);
  PyVTKAddFile_vtkLookupTable(d, modulename);
  PyVTKAddFile_vtkLookupTableWithEnabling(d, modulename);
  PyVTKAddFile_vtkMath(d, modulename);
  PyVTKAddFile_vtkMatrix3x3(d, modulename);
  PyVTKAddFile_vtkMatrix4x4(d, modulename);
  PyVTKAddFile_vtkMatrixToHomogeneousTransform(d, modulename);
  PyVTKAddFile_vtkMatrixToLinearTransform(d, modulename);
  PyVTKAddFile_vtkMinimalStandardRandomSequence(d, modulename);
  PyVTKAddFile_vtkMultiThreader(d, modulename);
  PyVTKAddFile_vtkMutexLock(d, modulename);
  PyVTKAddFile_vtkObject(d, modulename);
  PyVTKAddFile_vtkObjectBase(d, modulename);
  PyVTKAddFile_vtkObjectFactory(d, modulename);
  PyVTKAddFile_vtkObjectFactoryCollection(d, modulename);
  PyVTKAddFile_vtkOnePieceExtentTranslator(d, modulename);
  PyVTKAddFile_vtkOutputWindow(d, modulename);
  PyVTKAddFile_vtkOverrideInformation(d, modulename);
  PyVTKAddFile_vtkOverrideInformationCollection(d, modulename);
  PyVTKAddFile_vtkParametricBoy(d, modulename);
  PyVTKAddFile_vtkParametricConicSpiral(d, modulename);
  PyVTKAddFile_vtkParametricCrossCap(d, modulename);
  PyVTKAddFile_vtkParametricDini(d, modulename);
  PyVTKAddFile_vtkParametricEllipsoid(d, modulename);
  PyVTKAddFile_vtkParametricEnneper(d, modulename);
  PyVTKAddFile_vtkParametricFigure8Klein(d, modulename);
  PyVTKAddFile_vtkParametricFunction(d, modulename);
  PyVTKAddFile_vtkParametricKlein(d, modulename);
  PyVTKAddFile_vtkParametricMobius(d, modulename);
  PyVTKAddFile_vtkParametricRandomHills(d, modulename);
  PyVTKAddFile_vtkParametricRoman(d, modulename);
  PyVTKAddFile_vtkParametricSuperEllipsoid(d, modulename);
  PyVTKAddFile_vtkParametricSuperToroid(d, modulename);
  PyVTKAddFile_vtkParametricTorus(d, modulename);
  PyVTKAddFile_vtkPerspectiveTransform(d, modulename);
  PyVTKAddFile_vtkPlane(d, modulename);
  PyVTKAddFile_vtkPlaneCollection(d, modulename);
  PyVTKAddFile_vtkPlanes(d, modulename);
  PyVTKAddFile_vtkPoints(d, modulename);
  PyVTKAddFile_vtkPoints2D(d, modulename);
  PyVTKAddFile_vtkPolynomialSolversUnivariate(d, modulename);
  PyVTKAddFile_vtkPriorityQueue(d, modulename);
  PyVTKAddFile_vtkProp(d, modulename);
  PyVTKAddFile_vtkPropCollection(d, modulename);
  PyVTKAddFile_vtkProperty2D(d, modulename);
  PyVTKAddFile_vtkQuadratureSchemeDefinition(d, modulename);
  PyVTKAddFile_vtkQuadric(d, modulename);
  PyVTKAddFile_vtkRandomSequence(d, modulename);
  PyVTKAddFile_vtkRect(d, modulename);
  PyVTKAddFile_vtkReferenceCount(d, modulename);
  PyVTKAddFile_vtkRungeKutta2(d, modulename);
  PyVTKAddFile_vtkRungeKutta4(d, modulename);
  PyVTKAddFile_vtkRungeKutta45(d, modulename);
  PyVTKAddFile_vtkScalarsToColors(d, modulename);
  PyVTKAddFile_vtkServerSocket(d, modulename);
  PyVTKAddFile_vtkShortArray(d, modulename);
  PyVTKAddFile_vtkSignedCharArray(d, modulename);
  PyVTKAddFile_vtkSocket(d, modulename);
  PyVTKAddFile_vtkSocketCollection(d, modulename);
  PyVTKAddFile_vtkSortDataArray(d, modulename);
  PyVTKAddFile_vtkSphericalTransform(d, modulename);
  PyVTKAddFile_vtkStringArray(d, modulename);
  PyVTKAddFile_vtkStructuredData(d, modulename);
  PyVTKAddFile_vtkStructuredExtent(d, modulename);
  PyVTKAddFile_vtkStructuredVisibilityConstraint(d, modulename);
  PyVTKAddFile_vtkTableExtentTranslator(d, modulename);
  PyVTKAddFile_vtkTensor(d, modulename);
  PyVTKAddFile_vtkThreadMessager(d, modulename);
  PyVTKAddFile_vtkTimePointUtility(d, modulename);
  PyVTKAddFile_vtkTimeStamp(d, modulename);
  PyVTKAddFile_vtkTimerLog(d, modulename);
  PyVTKAddFile_vtkTransform2D(d, modulename);
  PyVTKAddFile_vtkTransform(d, modulename);
  PyVTKAddFile_vtkTransformCollection(d, modulename);
  PyVTKAddFile_vtkUnicodeStringArray(d, modulename);
  PyVTKAddFile_vtkUnsignedCharArray(d, modulename);
  PyVTKAddFile_vtkUnsignedIntArray(d, modulename);
  PyVTKAddFile_vtkUnsignedLongArray(d, modulename);
  PyVTKAddFile_vtkUnsignedShortArray(d, modulename);
  PyVTKAddFile_vtkVariant(d, modulename);
  PyVTKAddFile_vtkVariantArray(d, modulename);
  PyVTKAddFile_vtkVector(d, modulename);
  PyVTKAddFile_vtkVersion(d, modulename);
  PyVTKAddFile_vtkVoidArray(d, modulename);
  PyVTKAddFile_vtkWarpTransform(d, modulename);
  PyVTKAddFile_vtkWindow(d, modulename);
  PyVTKAddFile_vtkWindowLevelLookupTable(d, modulename);
  PyVTKAddFile_vtkXMLDataElement(d, modulename);
  PyVTKAddFile_vtkXMLFileOutputWindow(d, modulename);
  PyVTKAddFile_vtkLongLongArray(d, modulename);
  PyVTKAddFile_vtkUnsignedLongLongArray(d, modulename);
  PyVTKAddFile_vtkTypeInt8Array(d, modulename);
  PyVTKAddFile_vtkTypeInt16Array(d, modulename);
  PyVTKAddFile_vtkTypeInt32Array(d, modulename);
  PyVTKAddFile_vtkTypeInt64Array(d, modulename);
  PyVTKAddFile_vtkTypeUInt8Array(d, modulename);
  PyVTKAddFile_vtkTypeUInt16Array(d, modulename);
  PyVTKAddFile_vtkTypeUInt32Array(d, modulename);
  PyVTKAddFile_vtkTypeUInt64Array(d, modulename);
  PyVTKAddFile_vtkTypeFloat32Array(d, modulename);
  PyVTKAddFile_vtkTypeFloat64Array(d, modulename);
  PyVTKAddFile_vtkArray(d, modulename);
  PyVTKAddFile_vtkArrayCoordinates(d, modulename);
  PyVTKAddFile_vtkArrayExtents(d, modulename);
  PyVTKAddFile_vtkArrayExtentsList(d, modulename);
  PyVTKAddFile_vtkArrayRange(d, modulename);
  PyVTKAddFile_vtkArraySort(d, modulename);
  PyVTKAddFile_vtkArrayWeights(d, modulename);
  PyVTKAddFile_vtkDenseArray(d, modulename);
  PyVTKAddFile_vtkSparseArray(d, modulename);
  PyVTKAddFile_vtkTypedArray(d, modulename);
  PyVTKAddFile_vtkTypeTemplate(d, modulename);
  PyVTKAddFile_vtkSystemIncludes(d, modulename);
  PyVTKAddFile_vtkType(d, modulename);
  PyVTKAddFile_vtkMathConfigure(d, modulename);
  PyVTKAddFile_vtkConfigure(d, modulename);
  PyVTKAddFile_mutable(d, modulename);
}

