// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPython.h"

#include "vtkSystemIncludes.h"
#include <string.h>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings 

extern  "C" {PyObject *PyVTKAddFile_vtkConvertSelectionDomain(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataRepresentation(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEmptyRepresentation(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGraphLayoutView(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHierarchicalGraphPipeline(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHierarchicalGraphView(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkIcicleView(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorStyleAreaSelectHover(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorStyleTreeMapHover(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRenderedSurfaceRepresentation(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRenderedGraphRepresentation(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRenderedRepresentation(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRenderedTreeAreaRepresentation(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRenderedHierarchyRepresentation(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRenderView(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRenderViewBase(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTreeAreaView(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTreeMapView(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTreeRingView(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkView(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkViewUpdater(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParallelCoordinatesHistogramRepresentation(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParallelCoordinatesRepresentation(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParallelCoordinatesView(PyObject *, const char *); }

static PyMethodDef PyvtkViewsPython_ClassMethods[] = {
{NULL, NULL, 0, NULL}};

static void real_initvtkViewsPython(const char *modulename);

extern  "C" { void initvtkViewsPython(); }

void initvtkViewsPython()
{
  static const char modulename[] = "vtkViewsPython";
  real_initvtkViewsPython(modulename);
}

extern  "C" { void initlibvtkViewsPython(); }

void initlibvtkViewsPython()
{
  static const char modulename[] = "libvtkViewsPython";
  real_initvtkViewsPython(modulename);
}

void real_initvtkViewsPython(const char *modulename)
{
  PyObject *m, *d;

  m = Py_InitModule((char*)modulename, PyvtkViewsPython_ClassMethods);
  d = PyModule_GetDict(m);
  if (!d)
    {
    Py_FatalError((char*)"can't get dictionary for module vtkViewsPython");
    }
  PyVTKAddFile_vtkConvertSelectionDomain(d, modulename);
  PyVTKAddFile_vtkDataRepresentation(d, modulename);
  PyVTKAddFile_vtkEmptyRepresentation(d, modulename);
  PyVTKAddFile_vtkGraphLayoutView(d, modulename);
  PyVTKAddFile_vtkHierarchicalGraphPipeline(d, modulename);
  PyVTKAddFile_vtkHierarchicalGraphView(d, modulename);
  PyVTKAddFile_vtkIcicleView(d, modulename);
  PyVTKAddFile_vtkInteractorStyleAreaSelectHover(d, modulename);
  PyVTKAddFile_vtkInteractorStyleTreeMapHover(d, modulename);
  PyVTKAddFile_vtkRenderedSurfaceRepresentation(d, modulename);
  PyVTKAddFile_vtkRenderedGraphRepresentation(d, modulename);
  PyVTKAddFile_vtkRenderedRepresentation(d, modulename);
  PyVTKAddFile_vtkRenderedTreeAreaRepresentation(d, modulename);
  PyVTKAddFile_vtkRenderedHierarchyRepresentation(d, modulename);
  PyVTKAddFile_vtkRenderView(d, modulename);
  PyVTKAddFile_vtkRenderViewBase(d, modulename);
  PyVTKAddFile_vtkTreeAreaView(d, modulename);
  PyVTKAddFile_vtkTreeMapView(d, modulename);
  PyVTKAddFile_vtkTreeRingView(d, modulename);
  PyVTKAddFile_vtkView(d, modulename);
  PyVTKAddFile_vtkViewUpdater(d, modulename);
  PyVTKAddFile_vtkParallelCoordinatesHistogramRepresentation(d, modulename);
  PyVTKAddFile_vtkParallelCoordinatesRepresentation(d, modulename);
  PyVTKAddFile_vtkParallelCoordinatesView(d, modulename);
}

