// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPython.h"

#include "vtkSystemIncludes.h"
#include <string.h>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings 

extern  "C" {PyObject *PyVTKAddFile_vtkAbstractMapper3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAbstractPicker(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAbstractPropPicker(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAbstractVolumeMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkActorCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAreaPicker(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMapArrayValues(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAssembly(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAxisActor2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCamera(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCameraActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCameraInterpolator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCellCenterDepthSort(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCellPicker(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkChooserPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkClipPlanesPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCoincidentTopologyResolutionPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkColorMaterialHelper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCompositePainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCompositePolyDataMapper2(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCompositePolyDataMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCullerCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCuller(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataTransferHelper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDefaultPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDisplayListPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDistanceToCamera(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDynamic2DLabelMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDummyGPUInfoList(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExporter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFollower(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFrameBufferObject(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFreeTypeStringToImage(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFrustumCoverageCuller(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericRenderWindowInteractor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericVertexAttributeMapping(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGlyph3DMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGPUInfo(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGPUInfoList(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGraphicsFactory(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGraphMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGraphToGlyphs(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHardwareSelector(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHardwareSelectionPolyDataPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHierarchicalPolyDataMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageViewer2(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageViewer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImagingFactory(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImporter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorEventRecorder(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorObserver(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorStyle(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorStyleFlight(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorStyleImage(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorStyleJoystickActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorStyleJoystickCamera(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorStyleRubberBand2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorStyleRubberBand3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorStyleRubberBandPick(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorStyleRubberBandZoom(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorStyleSwitch(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorStyleTerrain(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorStyleTrackballActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorStyleTrackballCamera(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorStyleTrackball(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorStyleUnicam(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInteractorStyleUser(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkIVExporter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLabeledDataMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLabeledTreeMapDataMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLabelHierarchy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLabelHierarchyAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLabelHierarchyIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLabelHierarchyCompositeIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLabelPlacer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLabelPlacementMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLabelRenderStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLabelSizeCalculator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLeaderActor2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLightActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLightCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLight(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLightingPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLightKit(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLineIntegralConvolution2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLinesPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLODActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLODProp3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMapperCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOBJExporter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkObserverMediator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOOGLExporter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPainterDeviceAdapter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPainterPolyDataMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParallelCoordinatesActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParallelCoordinatesInteractorStyle(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPicker(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPixelBufferObject(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPointPicker(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPointSetToLabelHierarchy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPointsPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPOVExporter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyDataMapper2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyDataMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyDataPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolygonsPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPrimitivePainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProp3DCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProp3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProp3DFollower(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProperty(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPropPicker(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuadricLODActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuaternionInterpolator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRenderedAreaPicker(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRendererCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRenderer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRendererDelegate(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRendererSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRenderPass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRenderWindowCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRenderWindow(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRenderWindowInteractor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRepresentationPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkScalarBarActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkScalarsToColorsPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkScaledTextActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkScenePicker(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSelectVisiblePoints(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkShader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkShaderDeviceAdapter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkShaderProgram(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStandardPolyDataPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStringToImage(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSurfaceLICDefaultPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSurfaceLICPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTDxInteractorStyle(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTDxInteractorStyleCamera(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTDxInteractorStyleGeo(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTDxInteractorStyleSettings(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTesting(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTextActor3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTextActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTextMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTextProperty(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTexture(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTexturedActor2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTextureObject(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTransformInterpolator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTStripsPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTupleInterpolator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkViewTheme(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVisibilitySort(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumeCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolume(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumeProperty(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVRMLExporter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkWindowToImageFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkWorldPointPicker(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVisibleCellSelector(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkIdentColoredPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXGPUInfoList(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXRenderWindowInteractor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCameraPass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkClearZPass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDefaultPass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDepthPeelingPass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGaussianBlurPass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageProcessingPass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLightsPass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGLSLShaderDeviceAdapter2(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpaquePass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLCamera(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLClipPlanesPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLCoincidentTopologyResolutionPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLDisplayListPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLExtensionManager(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLGlyph3DMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLHardwareSupport(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLImageActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLImageMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLLight(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLLightingPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLPainterDeviceAdapter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLPolyDataMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLPolyDataMapper2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLProperty(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLRenderWindow(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLRenderer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLRepresentationPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLScalarsToColorsPainter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLTexture(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOverlayPass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRenderPassCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSequencePass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkShadowMapBakerPass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkShadowMapPass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSobelGradientMagnitudePass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTranslucentPass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUniformVariables(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumetricPass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGLSLShader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGLSLShaderDeviceAdapter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGLSLShaderProgram(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFreeTypeLabelRenderStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLFreeTypeTextMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericOpenGLRenderWindow(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXOpenGLRenderWindow(PyObject *, const char *); }

static PyMethodDef PyvtkRenderingPython_ClassMethods[] = {
{NULL, NULL, 0, NULL}};

static void real_initvtkRenderingPython(const char *modulename);

extern  "C" { void initvtkRenderingPython(); }

void initvtkRenderingPython()
{
  static const char modulename[] = "vtkRenderingPython";
  real_initvtkRenderingPython(modulename);
}

extern  "C" { void initlibvtkRenderingPython(); }

void initlibvtkRenderingPython()
{
  static const char modulename[] = "libvtkRenderingPython";
  real_initvtkRenderingPython(modulename);
}

void real_initvtkRenderingPython(const char *modulename)
{
  PyObject *m, *d;

  m = Py_InitModule((char*)modulename, PyvtkRenderingPython_ClassMethods);
  d = PyModule_GetDict(m);
  if (!d)
    {
    Py_FatalError((char*)"can't get dictionary for module vtkRenderingPython");
    }
  PyVTKAddFile_vtkAbstractMapper3D(d, modulename);
  PyVTKAddFile_vtkAbstractPicker(d, modulename);
  PyVTKAddFile_vtkAbstractPropPicker(d, modulename);
  PyVTKAddFile_vtkAbstractVolumeMapper(d, modulename);
  PyVTKAddFile_vtkActorCollection(d, modulename);
  PyVTKAddFile_vtkActor(d, modulename);
  PyVTKAddFile_vtkAreaPicker(d, modulename);
  PyVTKAddFile_vtkMapArrayValues(d, modulename);
  PyVTKAddFile_vtkAssembly(d, modulename);
  PyVTKAddFile_vtkAxisActor2D(d, modulename);
  PyVTKAddFile_vtkCamera(d, modulename);
  PyVTKAddFile_vtkCameraActor(d, modulename);
  PyVTKAddFile_vtkCameraInterpolator(d, modulename);
  PyVTKAddFile_vtkCellCenterDepthSort(d, modulename);
  PyVTKAddFile_vtkCellPicker(d, modulename);
  PyVTKAddFile_vtkChooserPainter(d, modulename);
  PyVTKAddFile_vtkClipPlanesPainter(d, modulename);
  PyVTKAddFile_vtkCoincidentTopologyResolutionPainter(d, modulename);
  PyVTKAddFile_vtkColorMaterialHelper(d, modulename);
  PyVTKAddFile_vtkCompositePainter(d, modulename);
  PyVTKAddFile_vtkCompositePolyDataMapper2(d, modulename);
  PyVTKAddFile_vtkCompositePolyDataMapper(d, modulename);
  PyVTKAddFile_vtkCullerCollection(d, modulename);
  PyVTKAddFile_vtkCuller(d, modulename);
  PyVTKAddFile_vtkDataSetMapper(d, modulename);
  PyVTKAddFile_vtkDataTransferHelper(d, modulename);
  PyVTKAddFile_vtkDefaultPainter(d, modulename);
  PyVTKAddFile_vtkDisplayListPainter(d, modulename);
  PyVTKAddFile_vtkDistanceToCamera(d, modulename);
  PyVTKAddFile_vtkDynamic2DLabelMapper(d, modulename);
  PyVTKAddFile_vtkDummyGPUInfoList(d, modulename);
  PyVTKAddFile_vtkExporter(d, modulename);
  PyVTKAddFile_vtkFollower(d, modulename);
  PyVTKAddFile_vtkFrameBufferObject(d, modulename);
  PyVTKAddFile_vtkFreeTypeStringToImage(d, modulename);
  PyVTKAddFile_vtkFrustumCoverageCuller(d, modulename);
  PyVTKAddFile_vtkGenericRenderWindowInteractor(d, modulename);
  PyVTKAddFile_vtkGenericVertexAttributeMapping(d, modulename);
  PyVTKAddFile_vtkGlyph3DMapper(d, modulename);
  PyVTKAddFile_vtkGPUInfo(d, modulename);
  PyVTKAddFile_vtkGPUInfoList(d, modulename);
  PyVTKAddFile_vtkGraphicsFactory(d, modulename);
  PyVTKAddFile_vtkGraphMapper(d, modulename);
  PyVTKAddFile_vtkGraphToGlyphs(d, modulename);
  PyVTKAddFile_vtkHardwareSelector(d, modulename);
  PyVTKAddFile_vtkHardwareSelectionPolyDataPainter(d, modulename);
  PyVTKAddFile_vtkHierarchicalPolyDataMapper(d, modulename);
  PyVTKAddFile_vtkImageActor(d, modulename);
  PyVTKAddFile_vtkImageMapper(d, modulename);
  PyVTKAddFile_vtkImageViewer2(d, modulename);
  PyVTKAddFile_vtkImageViewer(d, modulename);
  PyVTKAddFile_vtkImagingFactory(d, modulename);
  PyVTKAddFile_vtkImporter(d, modulename);
  PyVTKAddFile_vtkInteractorEventRecorder(d, modulename);
  PyVTKAddFile_vtkInteractorObserver(d, modulename);
  PyVTKAddFile_vtkInteractorStyle(d, modulename);
  PyVTKAddFile_vtkInteractorStyleFlight(d, modulename);
  PyVTKAddFile_vtkInteractorStyleImage(d, modulename);
  PyVTKAddFile_vtkInteractorStyleJoystickActor(d, modulename);
  PyVTKAddFile_vtkInteractorStyleJoystickCamera(d, modulename);
  PyVTKAddFile_vtkInteractorStyleRubberBand2D(d, modulename);
  PyVTKAddFile_vtkInteractorStyleRubberBand3D(d, modulename);
  PyVTKAddFile_vtkInteractorStyleRubberBandPick(d, modulename);
  PyVTKAddFile_vtkInteractorStyleRubberBandZoom(d, modulename);
  PyVTKAddFile_vtkInteractorStyleSwitch(d, modulename);
  PyVTKAddFile_vtkInteractorStyleTerrain(d, modulename);
  PyVTKAddFile_vtkInteractorStyleTrackballActor(d, modulename);
  PyVTKAddFile_vtkInteractorStyleTrackballCamera(d, modulename);
  PyVTKAddFile_vtkInteractorStyleTrackball(d, modulename);
  PyVTKAddFile_vtkInteractorStyleUnicam(d, modulename);
  PyVTKAddFile_vtkInteractorStyleUser(d, modulename);
  PyVTKAddFile_vtkIVExporter(d, modulename);
  PyVTKAddFile_vtkLabeledDataMapper(d, modulename);
  PyVTKAddFile_vtkLabeledTreeMapDataMapper(d, modulename);
  PyVTKAddFile_vtkLabelHierarchy(d, modulename);
  PyVTKAddFile_vtkLabelHierarchyAlgorithm(d, modulename);
  PyVTKAddFile_vtkLabelHierarchyIterator(d, modulename);
  PyVTKAddFile_vtkLabelHierarchyCompositeIterator(d, modulename);
  PyVTKAddFile_vtkLabelPlacer(d, modulename);
  PyVTKAddFile_vtkLabelPlacementMapper(d, modulename);
  PyVTKAddFile_vtkLabelRenderStrategy(d, modulename);
  PyVTKAddFile_vtkLabelSizeCalculator(d, modulename);
  PyVTKAddFile_vtkLeaderActor2D(d, modulename);
  PyVTKAddFile_vtkLightActor(d, modulename);
  PyVTKAddFile_vtkLightCollection(d, modulename);
  PyVTKAddFile_vtkLight(d, modulename);
  PyVTKAddFile_vtkLightingPainter(d, modulename);
  PyVTKAddFile_vtkLightKit(d, modulename);
  PyVTKAddFile_vtkLineIntegralConvolution2D(d, modulename);
  PyVTKAddFile_vtkLinesPainter(d, modulename);
  PyVTKAddFile_vtkLODActor(d, modulename);
  PyVTKAddFile_vtkLODProp3D(d, modulename);
  PyVTKAddFile_vtkMapperCollection(d, modulename);
  PyVTKAddFile_vtkMapper(d, modulename);
  PyVTKAddFile_vtkOBJExporter(d, modulename);
  PyVTKAddFile_vtkObserverMediator(d, modulename);
  PyVTKAddFile_vtkOOGLExporter(d, modulename);
  PyVTKAddFile_vtkPainter(d, modulename);
  PyVTKAddFile_vtkPainterDeviceAdapter(d, modulename);
  PyVTKAddFile_vtkPainterPolyDataMapper(d, modulename);
  PyVTKAddFile_vtkParallelCoordinatesActor(d, modulename);
  PyVTKAddFile_vtkParallelCoordinatesInteractorStyle(d, modulename);
  PyVTKAddFile_vtkPicker(d, modulename);
  PyVTKAddFile_vtkPixelBufferObject(d, modulename);
  PyVTKAddFile_vtkPointPicker(d, modulename);
  PyVTKAddFile_vtkPointSetToLabelHierarchy(d, modulename);
  PyVTKAddFile_vtkPointsPainter(d, modulename);
  PyVTKAddFile_vtkPOVExporter(d, modulename);
  PyVTKAddFile_vtkPolyDataMapper2D(d, modulename);
  PyVTKAddFile_vtkPolyDataMapper(d, modulename);
  PyVTKAddFile_vtkPolyDataPainter(d, modulename);
  PyVTKAddFile_vtkPolygonsPainter(d, modulename);
  PyVTKAddFile_vtkPrimitivePainter(d, modulename);
  PyVTKAddFile_vtkProp3DCollection(d, modulename);
  PyVTKAddFile_vtkProp3D(d, modulename);
  PyVTKAddFile_vtkProp3DFollower(d, modulename);
  PyVTKAddFile_vtkProperty(d, modulename);
  PyVTKAddFile_vtkPropPicker(d, modulename);
  PyVTKAddFile_vtkQuadricLODActor(d, modulename);
  PyVTKAddFile_vtkQuaternionInterpolator(d, modulename);
  PyVTKAddFile_vtkRenderedAreaPicker(d, modulename);
  PyVTKAddFile_vtkRendererCollection(d, modulename);
  PyVTKAddFile_vtkRenderer(d, modulename);
  PyVTKAddFile_vtkRendererDelegate(d, modulename);
  PyVTKAddFile_vtkRendererSource(d, modulename);
  PyVTKAddFile_vtkRenderPass(d, modulename);
  PyVTKAddFile_vtkRenderWindowCollection(d, modulename);
  PyVTKAddFile_vtkRenderWindow(d, modulename);
  PyVTKAddFile_vtkRenderWindowInteractor(d, modulename);
  PyVTKAddFile_vtkRepresentationPainter(d, modulename);
  PyVTKAddFile_vtkScalarBarActor(d, modulename);
  PyVTKAddFile_vtkScalarsToColorsPainter(d, modulename);
  PyVTKAddFile_vtkScaledTextActor(d, modulename);
  PyVTKAddFile_vtkScenePicker(d, modulename);
  PyVTKAddFile_vtkSelectVisiblePoints(d, modulename);
  PyVTKAddFile_vtkShader(d, modulename);
  PyVTKAddFile_vtkShaderDeviceAdapter(d, modulename);
  PyVTKAddFile_vtkShaderProgram(d, modulename);
  PyVTKAddFile_vtkStandardPolyDataPainter(d, modulename);
  PyVTKAddFile_vtkStringToImage(d, modulename);
  PyVTKAddFile_vtkSurfaceLICDefaultPainter(d, modulename);
  PyVTKAddFile_vtkSurfaceLICPainter(d, modulename);
  PyVTKAddFile_vtkTDxInteractorStyle(d, modulename);
  PyVTKAddFile_vtkTDxInteractorStyleCamera(d, modulename);
  PyVTKAddFile_vtkTDxInteractorStyleGeo(d, modulename);
  PyVTKAddFile_vtkTDxInteractorStyleSettings(d, modulename);
  PyVTKAddFile_vtkTesting(d, modulename);
  PyVTKAddFile_vtkTextActor3D(d, modulename);
  PyVTKAddFile_vtkTextActor(d, modulename);
  PyVTKAddFile_vtkTextMapper(d, modulename);
  PyVTKAddFile_vtkTextProperty(d, modulename);
  PyVTKAddFile_vtkTexture(d, modulename);
  PyVTKAddFile_vtkTexturedActor2D(d, modulename);
  PyVTKAddFile_vtkTextureObject(d, modulename);
  PyVTKAddFile_vtkTransformInterpolator(d, modulename);
  PyVTKAddFile_vtkTStripsPainter(d, modulename);
  PyVTKAddFile_vtkTupleInterpolator(d, modulename);
  PyVTKAddFile_vtkViewTheme(d, modulename);
  PyVTKAddFile_vtkVisibilitySort(d, modulename);
  PyVTKAddFile_vtkVolumeCollection(d, modulename);
  PyVTKAddFile_vtkVolume(d, modulename);
  PyVTKAddFile_vtkVolumeProperty(d, modulename);
  PyVTKAddFile_vtkVRMLExporter(d, modulename);
  PyVTKAddFile_vtkWindowToImageFilter(d, modulename);
  PyVTKAddFile_vtkWorldPointPicker(d, modulename);
  PyVTKAddFile_vtkVisibleCellSelector(d, modulename);
  PyVTKAddFile_vtkIdentColoredPainter(d, modulename);
  PyVTKAddFile_vtkXGPUInfoList(d, modulename);
  PyVTKAddFile_vtkXRenderWindowInteractor(d, modulename);
  PyVTKAddFile_vtkCameraPass(d, modulename);
  PyVTKAddFile_vtkClearZPass(d, modulename);
  PyVTKAddFile_vtkDefaultPass(d, modulename);
  PyVTKAddFile_vtkDepthPeelingPass(d, modulename);
  PyVTKAddFile_vtkGaussianBlurPass(d, modulename);
  PyVTKAddFile_vtkImageProcessingPass(d, modulename);
  PyVTKAddFile_vtkLightsPass(d, modulename);
  PyVTKAddFile_vtkGLSLShaderDeviceAdapter2(d, modulename);
  PyVTKAddFile_vtkOpaquePass(d, modulename);
  PyVTKAddFile_vtkOpenGLActor(d, modulename);
  PyVTKAddFile_vtkOpenGLCamera(d, modulename);
  PyVTKAddFile_vtkOpenGLClipPlanesPainter(d, modulename);
  PyVTKAddFile_vtkOpenGLCoincidentTopologyResolutionPainter(d, modulename);
  PyVTKAddFile_vtkOpenGLDisplayListPainter(d, modulename);
  PyVTKAddFile_vtkOpenGLExtensionManager(d, modulename);
  PyVTKAddFile_vtkOpenGLGlyph3DMapper(d, modulename);
  PyVTKAddFile_vtkOpenGLHardwareSupport(d, modulename);
  PyVTKAddFile_vtkOpenGLImageActor(d, modulename);
  PyVTKAddFile_vtkOpenGLImageMapper(d, modulename);
  PyVTKAddFile_vtkOpenGLLight(d, modulename);
  PyVTKAddFile_vtkOpenGLLightingPainter(d, modulename);
  PyVTKAddFile_vtkOpenGLPainterDeviceAdapter(d, modulename);
  PyVTKAddFile_vtkOpenGLPolyDataMapper(d, modulename);
  PyVTKAddFile_vtkOpenGLPolyDataMapper2D(d, modulename);
  PyVTKAddFile_vtkOpenGLProperty(d, modulename);
  PyVTKAddFile_vtkOpenGLRenderWindow(d, modulename);
  PyVTKAddFile_vtkOpenGLRenderer(d, modulename);
  PyVTKAddFile_vtkOpenGLRepresentationPainter(d, modulename);
  PyVTKAddFile_vtkOpenGLScalarsToColorsPainter(d, modulename);
  PyVTKAddFile_vtkOpenGLTexture(d, modulename);
  PyVTKAddFile_vtkOverlayPass(d, modulename);
  PyVTKAddFile_vtkRenderPassCollection(d, modulename);
  PyVTKAddFile_vtkSequencePass(d, modulename);
  PyVTKAddFile_vtkShadowMapBakerPass(d, modulename);
  PyVTKAddFile_vtkShadowMapPass(d, modulename);
  PyVTKAddFile_vtkSobelGradientMagnitudePass(d, modulename);
  PyVTKAddFile_vtkTranslucentPass(d, modulename);
  PyVTKAddFile_vtkUniformVariables(d, modulename);
  PyVTKAddFile_vtkVolumetricPass(d, modulename);
  PyVTKAddFile_vtkGLSLShader(d, modulename);
  PyVTKAddFile_vtkGLSLShaderDeviceAdapter(d, modulename);
  PyVTKAddFile_vtkGLSLShaderProgram(d, modulename);
  PyVTKAddFile_vtkFreeTypeLabelRenderStrategy(d, modulename);
  PyVTKAddFile_vtkOpenGLFreeTypeTextMapper(d, modulename);
  PyVTKAddFile_vtkGenericOpenGLRenderWindow(d, modulename);
  PyVTKAddFile_vtkXOpenGLRenderWindow(d, modulename);
}

