// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPython.h"

#include "vtkSystemIncludes.h"
#include <string.h>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings 

extern  "C" {PyObject *PyVTKAddFile_vtkGenericContourFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericGeometryFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericClip(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericProbeFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericDataSetTessellator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericCutter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericGlyph3DFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericStreamTracer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericOutlineFilter(PyObject *, const char *); }

static PyMethodDef PyvtkGenericFilteringPython_ClassMethods[] = {
{NULL, NULL, 0, NULL}};

static void real_initvtkGenericFilteringPython(const char *modulename);

extern  "C" { void initvtkGenericFilteringPython(); }

void initvtkGenericFilteringPython()
{
  static const char modulename[] = "vtkGenericFilteringPython";
  real_initvtkGenericFilteringPython(modulename);
}

extern  "C" { void initlibvtkGenericFilteringPython(); }

void initlibvtkGenericFilteringPython()
{
  static const char modulename[] = "libvtkGenericFilteringPython";
  real_initvtkGenericFilteringPython(modulename);
}

void real_initvtkGenericFilteringPython(const char *modulename)
{
  PyObject *m, *d;

  m = Py_InitModule((char*)modulename, PyvtkGenericFilteringPython_ClassMethods);
  d = PyModule_GetDict(m);
  if (!d)
    {
    Py_FatalError((char*)"can't get dictionary for module vtkGenericFilteringPython");
    }
  PyVTKAddFile_vtkGenericContourFilter(d, modulename);
  PyVTKAddFile_vtkGenericGeometryFilter(d, modulename);
  PyVTKAddFile_vtkGenericClip(d, modulename);
  PyVTKAddFile_vtkGenericProbeFilter(d, modulename);
  PyVTKAddFile_vtkGenericDataSetTessellator(d, modulename);
  PyVTKAddFile_vtkGenericCutter(d, modulename);
  PyVTKAddFile_vtkGenericGlyph3DFilter(d, modulename);
  PyVTKAddFile_vtkGenericStreamTracer(d, modulename);
  PyVTKAddFile_vtkGenericOutlineFilter(d, modulename);
}

