# CMake generated Testfile for 
# Source directory: /home/lakers/Downloads/VTK/Common/Testing/Cxx
# Build directory: /home/lakers/Downloads/VTK/Common/Testing/Cxx
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(TestObjectFactory "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestObjectFactory")
ADD_TEST(otherArrays "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "otherArrays")
ADD_TEST(otherTimerLog "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "otherTimerLog")
ADD_TEST(otherLookupTable "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "otherLookupTable")
ADD_TEST(otherLookupTableWithEnabling "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "otherLookupTableWithEnabling")
ADD_TEST(otherByteSwap "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "otherByteSwap")
ADD_TEST(otherStringArray "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "otherStringArray")
ADD_TEST(TestAmoebaMinimizer "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestAmoebaMinimizer")
ADD_TEST(TestArrayLookup "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestArrayLookup")
ADD_TEST(TestConditionVariable "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestConditionVariable")
SET_TESTS_PROPERTIES(TestConditionVariable PROPERTIES  RUN_SERIAL "ON")
ADD_TEST(TestGarbageCollector "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestGarbageCollector")
ADD_TEST(TestDataArray "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestDataArray")
ADD_TEST(TestDataArrayComponentNames "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestDataArrayComponentNames")
ADD_TEST(TestDirectory "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestDirectory")
ADD_TEST(TestFastNumericConversion "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestFastNumericConversion")
ADD_TEST(TestMath "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestMath")
ADD_TEST(TestMatrix3x3 "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestMatrix3x3")
ADD_TEST(TestMinimalStandardRandomSequence "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestMinimalStandardRandomSequence")
ADD_TEST(TestNew "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestNew")
ADD_TEST(TestObservers "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestObservers")
ADD_TEST(TestPolynomialSolversUnivariate "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestPolynomialSolversUnivariate")
ADD_TEST(TestSmartPointer "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestSmartPointer")
ADD_TEST(TestSortDataArray "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestSortDataArray")
ADD_TEST(TestUnicodeStringAPI "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestUnicodeStringAPI")
ADD_TEST(TestUnicodeStringArrayAPI "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestUnicodeStringArrayAPI")
ADD_TEST(TestVariantComparison "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestVariantComparison")
ADD_TEST(TestWeakPointer "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestWeakPointer")
ADD_TEST(TestSystemInformation "/home/lakers/Downloads/VTK/bin/CommonCxxTests" "TestSystemInformation")
ADD_TEST(TestCxxFeatures "/home/lakers/Downloads/VTK/bin/TestCxxFeatures")
ADD_TEST(TestInstantiator "/home/lakers/Downloads/VTK/bin/TestInstantiator")
ADD_TEST(Array-TestArrayAPI "/home/lakers/Downloads/VTK/bin/ArrayCxxTests" "TestArrayAPI")
ADD_TEST(Array-TestArrayAPIConvenience "/home/lakers/Downloads/VTK/bin/ArrayCxxTests" "TestArrayAPIConvenience")
ADD_TEST(Array-TestArrayAPIDense "/home/lakers/Downloads/VTK/bin/ArrayCxxTests" "TestArrayAPIDense")
ADD_TEST(Array-TestArrayAPISparse "/home/lakers/Downloads/VTK/bin/ArrayCxxTests" "TestArrayAPISparse")
ADD_TEST(Array-TestArrayBool "/home/lakers/Downloads/VTK/bin/ArrayCxxTests" "TestArrayBool")
ADD_TEST(Array-TestArrayInterpolationDense "/home/lakers/Downloads/VTK/bin/ArrayCxxTests" "TestArrayInterpolationDense")
ADD_TEST(Array-TestArrayNullValues "/home/lakers/Downloads/VTK/bin/ArrayCxxTests" "TestArrayNullValues")
ADD_TEST(Array-TestArrayExtents "/home/lakers/Downloads/VTK/bin/ArrayCxxTests" "TestArrayExtents")
ADD_TEST(Array-TestArrayUserTypes "/home/lakers/Downloads/VTK/bin/ArrayCxxTests" "TestArrayUserTypes")
ADD_TEST(Array-TestArrayVariants "/home/lakers/Downloads/VTK/bin/ArrayCxxTests" "TestArrayVariants")
ADD_TEST(Array-TestArraySize "/home/lakers/Downloads/VTK/bin/ArrayCxxTests" "TestArraySize")
ADD_TEST(Array-TestSparseArrayValidation "/home/lakers/Downloads/VTK/bin/ArrayCxxTests" "TestSparseArrayValidation")
