# CMake generated Testfile for 
# Source directory: /home/lakers/Downloads/VTK/Widgets/Testing/Cxx
# Build directory: /home/lakers/Downloads/VTK/Widgets/Testing/Cxx
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(BoxWidget "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "BoxWidget")
ADD_TEST(BoxWidget2 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "BoxWidget2")
ADD_TEST(TestAffineWidget "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestAffineWidget")
ADD_TEST(TestAngleWidget2D "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestAngleWidget2D")
ADD_TEST(TestAngleWidget3D "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestAngleWidget3D")
ADD_TEST(TestBalloonWidget "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestBalloonWidget")
ADD_TEST(TestBorderWidget "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestBorderWidget")
ADD_TEST(TestButtonWidget "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestButtonWidget")
ADD_TEST(TestCameraWidget "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestCameraWidget")
ADD_TEST(TestCenteredSliderWidget2D "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestCenteredSliderWidget2D")
ADD_TEST(TestCheckerboardWidget "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestCheckerboardWidget")
ADD_TEST(TestContourWidget2 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestContourWidget2")
ADD_TEST(TestDistanceWidget "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestDistanceWidget")
ADD_TEST(TestDistanceWidget3D "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestDistanceWidget3D")
ADD_TEST(TestHandleWidget2D "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestHandleWidget2D")
ADD_TEST(TestImplicitPlaneWidget "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestImplicitPlaneWidget")
ADD_TEST(TestImplicitPlaneWidget2 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestImplicitPlaneWidget2")
ADD_TEST(TestImplicitPlaneWidget2b "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestImplicitPlaneWidget2b")
ADD_TEST(TestLogoWidget "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestLogoWidget")
ADD_TEST(TestOrientationMarkerWidget "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestOrientationMarkerWidget")
ADD_TEST(TestPlaybackWidget "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestPlaybackWidget")
ADD_TEST(TestProgrammaticPlacement "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestProgrammaticPlacement")
ADD_TEST(TestSeedWidget "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestSeedWidget")
ADD_TEST(TestSliderWidget "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestSliderWidget")
ADD_TEST(TestSliderWidget2D "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestSliderWidget2D")
ADD_TEST(TestTextWidget "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestTextWidget")
ADD_TEST(TestParallelopipedWidget "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestParallelopipedWidget")
ADD_TEST(TestSeedWidgetNonUniformRepresentations "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "TestSeedWidgetNonUniformRepresentations")
ADD_TEST(vtkAngleWidgetTest1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkAngleWidgetTest1")
ADD_TEST(vtkBiDimensionalWidgetTest1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkBiDimensionalWidgetTest1")
ADD_TEST(vtkImplicitPlaneWidget2Test1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkImplicitPlaneWidget2Test1")
ADD_TEST(vtkLineWidget2Test1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkLineWidget2Test1")
ADD_TEST(vtkSeedWidgetTest1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkSeedWidgetTest1")
ADD_TEST(vtkSplineWidget2Test1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkSplineWidget2Test1")
ADD_TEST(vtkBorderWidgetTest1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkBorderWidgetTest1")
ADD_TEST(vtkCaptionWidgetTest1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkCaptionWidgetTest1")
ADD_TEST(vtkTextWidgetTest1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkTextWidgetTest1")
ADD_TEST(vtkHoverWidgetTest1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkHoverWidgetTest1")
ADD_TEST(vtkBalloonWidgetTest1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkBalloonWidgetTest1")
ADD_TEST(vtkAngleRepresentation2DTest1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkAngleRepresentation2DTest1")
ADD_TEST(vtkAngleRepresentation3DTest1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkAngleRepresentation3DTest1")
ADD_TEST(vtkBalloonRepresentationTest1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkBalloonRepresentationTest1")
ADD_TEST(vtkBiDimensionalRepresentation2DTest1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkBiDimensionalRepresentation2DTest1")
ADD_TEST(vtkCaptionRepresentationTest1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkCaptionRepresentationTest1")
ADD_TEST(vtkTextRepresentationTest1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkTextRepresentationTest1")
ADD_TEST(vtkLineRepresentationTest1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkLineRepresentationTest1")
ADD_TEST(vtkSeedRepresentationTest1 "/home/lakers/Downloads/VTK/bin/WidgetsCxxTests" "vtkSeedRepresentationTest1")
