// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPython.h"

#include "vtkSystemIncludes.h"
#include <string.h>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings 

extern  "C" {PyObject *PyVTKAddFile_vtkAbstractCellLocator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAbstractInterpolatedVelocityField(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAbstractMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAbstractPointLocator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkActor2DCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkActor2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAdjacentVertexIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAlgorithmOutput(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAnnotation(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAnnotationLayers(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAnnotationLayersAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAttributesErrorMetric(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBiQuadraticQuad(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBiQuadraticQuadraticHexahedron(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBiQuadraticQuadraticWedge(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBiQuadraticTriangle(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBSPCuts(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBSPIntersections(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCachedStreamingDemandDrivenPipeline(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCardinalSpline(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCastToConcrete(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCell3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCellArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCell(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCellData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCellLinks(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCellLocator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCellTypes(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkColorTransferFunction(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCompositeDataIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCompositeDataPipeline(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCompositeDataSetAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCompositeDataSet(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkComputingResources(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCone(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkConvexPointSet(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCoordinate(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCubicLine(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCylinder(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataObjectAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataObjectCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataObject(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataObjectSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataObjectTypes(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetAttributes(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSet(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetToDataSetFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetToImageFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetToPolyDataFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetToStructuredGridFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetToStructuredPointsFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetToUnstructuredGridFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDemandDrivenPipeline(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDirectedAcyclicGraph(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDirectedGraphAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDirectedGraph(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDiscretizableColorTransferFunction(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDistributedGraphHelper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEdgeListIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEmptyCell(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExecutionScheduler(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExecutive(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExecutiveCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExplicitCell(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFieldData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericAdaptorCell(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericAttributeCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericAttribute(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericCell(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericCellIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericCellTessellator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericDataSetAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericDataSet(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericEdgeTable(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericInterpolatedVelocityField(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericPointIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericSubdivisionErrorMetric(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGeometricErrorMetric(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGraphAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGraph(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGraphEdge(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGraphInternals(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHexagonalPrism(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHexahedron(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHierarchicalBoxDataIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHierarchicalBoxDataSetAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHierarchicalBoxDataSet(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHyperOctreeAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHyperOctreeCursor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHyperOctree(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHyperOctreePointsGrabber(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageInPlaceFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageMultipleInputFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageMultipleInputOutputFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageToImageFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageToStructuredPoints(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageTwoInputFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImplicitBoolean(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImplicitDataSet(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImplicitHalo(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImplicitSelectionLoop(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImplicitSum(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImplicitVolume(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImplicitWindowFunction(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkIncrementalOctreeNode(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkIncrementalOctreePointLocator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkIncrementalPointLocator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInEdgeIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationExecutivePortKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInformationExecutivePortVectorKey(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInterpolatedVelocityField(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkKdNode(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkKdTree(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkKdTreePointLocator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkKochanekSpline(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLine(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLocator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMapper2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMeanValueCoordinatesInterpolator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMergePoints(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMultiBlockDataSetAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMultiBlockDataSet(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMultiPieceDataSet(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMutableDirectedGraph(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMutableUndirectedGraph(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkNonLinearCell(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkNonMergingPointLocator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOctreePointLocator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOctreePointLocatorNode(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOrderedTriangulator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOutEdgeIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParametricSpline(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPassInputTypeAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPentagonalPrism(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPerlinNoise(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPiecewiseFunctionAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPiecewiseFunction(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPiecewiseFunctionShiftScale(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPixel(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPlanesIntersection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPointData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPointLocator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPointSetAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPointSet(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPointSetSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPointSetToPointSetFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPointsProjectedHull(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyDataAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyDataCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyDataSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyDataToPolyDataFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolygon(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyhedron(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyLine(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyVertex(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProcessObject(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPropAssembly(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPyramid(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuad(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuadraticEdge(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuadraticHexahedron(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuadraticLinearQuad(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuadraticLinearWedge(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuadraticPyramid(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuadraticQuad(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuadraticTetra(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuadraticTriangle(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkQuadraticWedge(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRectilinearGridAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRectilinearGrid(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRectilinearGridSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRectilinearGridToPolyDataFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkReebGraph(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkReebGraphSimplificationMetric(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkScalarTree(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSelectionAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSelection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSelectionNode(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSimpleCellTessellator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSimpleImageToImageFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSimpleScalarTree(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSmoothErrorMetric(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSphere(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSpline(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStreamingDemandDrivenPipeline(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredGridAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredGrid(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredGridSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredGridToPolyDataFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredGridToStructuredGridFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredPointsCollection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredPoints(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredPointsSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredPointsToPolyDataFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredPointsToStructuredPointsFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredPointsToUnstructuredGridFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSuperquadric(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTableAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTable(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTemporalDataSetAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTemporalDataSet(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTetra(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkThreadedImageAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkThreadedStreamingPipeline(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTreeAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTree(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTreeBFSIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTreeDFSIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTriangle(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTriangleStrip(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTriQuadraticHexahedron(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTrivialProducer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUndirectedGraphAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUndirectedGraph(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUniformGrid(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGrid(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridToPolyDataFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridToUnstructuredGridFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVertex(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVertexListIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkViewDependentErrorMetric(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkViewport(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVoxel(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkWedge(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArrayData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArrayDataAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCellType(PyObject *, const char *); }

static PyMethodDef PyvtkFilteringPython_ClassMethods[] = {
{NULL, NULL, 0, NULL}};

static void real_initvtkFilteringPython(const char *modulename);

extern  "C" { void initvtkFilteringPython(); }

void initvtkFilteringPython()
{
  static const char modulename[] = "vtkFilteringPython";
  real_initvtkFilteringPython(modulename);
}

extern  "C" { void initlibvtkFilteringPython(); }

void initlibvtkFilteringPython()
{
  static const char modulename[] = "libvtkFilteringPython";
  real_initvtkFilteringPython(modulename);
}

void real_initvtkFilteringPython(const char *modulename)
{
  PyObject *m, *d;

  m = Py_InitModule((char*)modulename, PyvtkFilteringPython_ClassMethods);
  d = PyModule_GetDict(m);
  if (!d)
    {
    Py_FatalError((char*)"can't get dictionary for module vtkFilteringPython");
    }
  PyVTKAddFile_vtkAbstractCellLocator(d, modulename);
  PyVTKAddFile_vtkAbstractInterpolatedVelocityField(d, modulename);
  PyVTKAddFile_vtkAbstractMapper(d, modulename);
  PyVTKAddFile_vtkAbstractPointLocator(d, modulename);
  PyVTKAddFile_vtkActor2DCollection(d, modulename);
  PyVTKAddFile_vtkActor2D(d, modulename);
  PyVTKAddFile_vtkAdjacentVertexIterator(d, modulename);
  PyVTKAddFile_vtkAlgorithm(d, modulename);
  PyVTKAddFile_vtkAlgorithmOutput(d, modulename);
  PyVTKAddFile_vtkAnnotation(d, modulename);
  PyVTKAddFile_vtkAnnotationLayers(d, modulename);
  PyVTKAddFile_vtkAnnotationLayersAlgorithm(d, modulename);
  PyVTKAddFile_vtkAttributesErrorMetric(d, modulename);
  PyVTKAddFile_vtkBiQuadraticQuad(d, modulename);
  PyVTKAddFile_vtkBiQuadraticQuadraticHexahedron(d, modulename);
  PyVTKAddFile_vtkBiQuadraticQuadraticWedge(d, modulename);
  PyVTKAddFile_vtkBiQuadraticTriangle(d, modulename);
  PyVTKAddFile_vtkBSPCuts(d, modulename);
  PyVTKAddFile_vtkBSPIntersections(d, modulename);
  PyVTKAddFile_vtkCachedStreamingDemandDrivenPipeline(d, modulename);
  PyVTKAddFile_vtkCardinalSpline(d, modulename);
  PyVTKAddFile_vtkCastToConcrete(d, modulename);
  PyVTKAddFile_vtkCell3D(d, modulename);
  PyVTKAddFile_vtkCellArray(d, modulename);
  PyVTKAddFile_vtkCell(d, modulename);
  PyVTKAddFile_vtkCellData(d, modulename);
  PyVTKAddFile_vtkCellLinks(d, modulename);
  PyVTKAddFile_vtkCellLocator(d, modulename);
  PyVTKAddFile_vtkCellTypes(d, modulename);
  PyVTKAddFile_vtkColorTransferFunction(d, modulename);
  PyVTKAddFile_vtkCompositeDataIterator(d, modulename);
  PyVTKAddFile_vtkCompositeDataPipeline(d, modulename);
  PyVTKAddFile_vtkCompositeDataSetAlgorithm(d, modulename);
  PyVTKAddFile_vtkCompositeDataSet(d, modulename);
  PyVTKAddFile_vtkComputingResources(d, modulename);
  PyVTKAddFile_vtkCone(d, modulename);
  PyVTKAddFile_vtkConvexPointSet(d, modulename);
  PyVTKAddFile_vtkCoordinate(d, modulename);
  PyVTKAddFile_vtkCubicLine(d, modulename);
  PyVTKAddFile_vtkCylinder(d, modulename);
  PyVTKAddFile_vtkDataObjectAlgorithm(d, modulename);
  PyVTKAddFile_vtkDataObjectCollection(d, modulename);
  PyVTKAddFile_vtkDataObject(d, modulename);
  PyVTKAddFile_vtkDataObjectSource(d, modulename);
  PyVTKAddFile_vtkDataObjectTypes(d, modulename);
  PyVTKAddFile_vtkDataSetAlgorithm(d, modulename);
  PyVTKAddFile_vtkDataSetAttributes(d, modulename);
  PyVTKAddFile_vtkDataSetCollection(d, modulename);
  PyVTKAddFile_vtkDataSet(d, modulename);
  PyVTKAddFile_vtkDataSetSource(d, modulename);
  PyVTKAddFile_vtkDataSetToDataSetFilter(d, modulename);
  PyVTKAddFile_vtkDataSetToImageFilter(d, modulename);
  PyVTKAddFile_vtkDataSetToPolyDataFilter(d, modulename);
  PyVTKAddFile_vtkDataSetToStructuredGridFilter(d, modulename);
  PyVTKAddFile_vtkDataSetToStructuredPointsFilter(d, modulename);
  PyVTKAddFile_vtkDataSetToUnstructuredGridFilter(d, modulename);
  PyVTKAddFile_vtkDemandDrivenPipeline(d, modulename);
  PyVTKAddFile_vtkDirectedAcyclicGraph(d, modulename);
  PyVTKAddFile_vtkDirectedGraphAlgorithm(d, modulename);
  PyVTKAddFile_vtkDirectedGraph(d, modulename);
  PyVTKAddFile_vtkDiscretizableColorTransferFunction(d, modulename);
  PyVTKAddFile_vtkDistributedGraphHelper(d, modulename);
  PyVTKAddFile_vtkEdgeListIterator(d, modulename);
  PyVTKAddFile_vtkEmptyCell(d, modulename);
  PyVTKAddFile_vtkExecutionScheduler(d, modulename);
  PyVTKAddFile_vtkExecutive(d, modulename);
  PyVTKAddFile_vtkExecutiveCollection(d, modulename);
  PyVTKAddFile_vtkExplicitCell(d, modulename);
  PyVTKAddFile_vtkFieldData(d, modulename);
  PyVTKAddFile_vtkGenericAdaptorCell(d, modulename);
  PyVTKAddFile_vtkGenericAttributeCollection(d, modulename);
  PyVTKAddFile_vtkGenericAttribute(d, modulename);
  PyVTKAddFile_vtkGenericCell(d, modulename);
  PyVTKAddFile_vtkGenericCellIterator(d, modulename);
  PyVTKAddFile_vtkGenericCellTessellator(d, modulename);
  PyVTKAddFile_vtkGenericDataSetAlgorithm(d, modulename);
  PyVTKAddFile_vtkGenericDataSet(d, modulename);
  PyVTKAddFile_vtkGenericEdgeTable(d, modulename);
  PyVTKAddFile_vtkGenericInterpolatedVelocityField(d, modulename);
  PyVTKAddFile_vtkGenericPointIterator(d, modulename);
  PyVTKAddFile_vtkGenericSubdivisionErrorMetric(d, modulename);
  PyVTKAddFile_vtkGeometricErrorMetric(d, modulename);
  PyVTKAddFile_vtkGraphAlgorithm(d, modulename);
  PyVTKAddFile_vtkGraph(d, modulename);
  PyVTKAddFile_vtkGraphEdge(d, modulename);
  PyVTKAddFile_vtkGraphInternals(d, modulename);
  PyVTKAddFile_vtkHexagonalPrism(d, modulename);
  PyVTKAddFile_vtkHexahedron(d, modulename);
  PyVTKAddFile_vtkHierarchicalBoxDataIterator(d, modulename);
  PyVTKAddFile_vtkHierarchicalBoxDataSetAlgorithm(d, modulename);
  PyVTKAddFile_vtkHierarchicalBoxDataSet(d, modulename);
  PyVTKAddFile_vtkHyperOctreeAlgorithm(d, modulename);
  PyVTKAddFile_vtkHyperOctreeCursor(d, modulename);
  PyVTKAddFile_vtkHyperOctree(d, modulename);
  PyVTKAddFile_vtkHyperOctreePointsGrabber(d, modulename);
  PyVTKAddFile_vtkImageAlgorithm(d, modulename);
  PyVTKAddFile_vtkImageData(d, modulename);
  PyVTKAddFile_vtkImageInPlaceFilter(d, modulename);
  PyVTKAddFile_vtkImageMultipleInputFilter(d, modulename);
  PyVTKAddFile_vtkImageMultipleInputOutputFilter(d, modulename);
  PyVTKAddFile_vtkImageSource(d, modulename);
  PyVTKAddFile_vtkImageToImageFilter(d, modulename);
  PyVTKAddFile_vtkImageToStructuredPoints(d, modulename);
  PyVTKAddFile_vtkImageTwoInputFilter(d, modulename);
  PyVTKAddFile_vtkImplicitBoolean(d, modulename);
  PyVTKAddFile_vtkImplicitDataSet(d, modulename);
  PyVTKAddFile_vtkImplicitHalo(d, modulename);
  PyVTKAddFile_vtkImplicitSelectionLoop(d, modulename);
  PyVTKAddFile_vtkImplicitSum(d, modulename);
  PyVTKAddFile_vtkImplicitVolume(d, modulename);
  PyVTKAddFile_vtkImplicitWindowFunction(d, modulename);
  PyVTKAddFile_vtkIncrementalOctreeNode(d, modulename);
  PyVTKAddFile_vtkIncrementalOctreePointLocator(d, modulename);
  PyVTKAddFile_vtkIncrementalPointLocator(d, modulename);
  PyVTKAddFile_vtkInEdgeIterator(d, modulename);
  PyVTKAddFile_vtkInformationExecutivePortKey(d, modulename);
  PyVTKAddFile_vtkInformationExecutivePortVectorKey(d, modulename);
  PyVTKAddFile_vtkInterpolatedVelocityField(d, modulename);
  PyVTKAddFile_vtkKdNode(d, modulename);
  PyVTKAddFile_vtkKdTree(d, modulename);
  PyVTKAddFile_vtkKdTreePointLocator(d, modulename);
  PyVTKAddFile_vtkKochanekSpline(d, modulename);
  PyVTKAddFile_vtkLine(d, modulename);
  PyVTKAddFile_vtkLocator(d, modulename);
  PyVTKAddFile_vtkMapper2D(d, modulename);
  PyVTKAddFile_vtkMeanValueCoordinatesInterpolator(d, modulename);
  PyVTKAddFile_vtkMergePoints(d, modulename);
  PyVTKAddFile_vtkMultiBlockDataSetAlgorithm(d, modulename);
  PyVTKAddFile_vtkMultiBlockDataSet(d, modulename);
  PyVTKAddFile_vtkMultiPieceDataSet(d, modulename);
  PyVTKAddFile_vtkMutableDirectedGraph(d, modulename);
  PyVTKAddFile_vtkMutableUndirectedGraph(d, modulename);
  PyVTKAddFile_vtkNonLinearCell(d, modulename);
  PyVTKAddFile_vtkNonMergingPointLocator(d, modulename);
  PyVTKAddFile_vtkOctreePointLocator(d, modulename);
  PyVTKAddFile_vtkOctreePointLocatorNode(d, modulename);
  PyVTKAddFile_vtkOrderedTriangulator(d, modulename);
  PyVTKAddFile_vtkOutEdgeIterator(d, modulename);
  PyVTKAddFile_vtkParametricSpline(d, modulename);
  PyVTKAddFile_vtkPassInputTypeAlgorithm(d, modulename);
  PyVTKAddFile_vtkPentagonalPrism(d, modulename);
  PyVTKAddFile_vtkPerlinNoise(d, modulename);
  PyVTKAddFile_vtkPiecewiseFunctionAlgorithm(d, modulename);
  PyVTKAddFile_vtkPiecewiseFunction(d, modulename);
  PyVTKAddFile_vtkPiecewiseFunctionShiftScale(d, modulename);
  PyVTKAddFile_vtkPixel(d, modulename);
  PyVTKAddFile_vtkPlanesIntersection(d, modulename);
  PyVTKAddFile_vtkPointData(d, modulename);
  PyVTKAddFile_vtkPointLocator(d, modulename);
  PyVTKAddFile_vtkPointSetAlgorithm(d, modulename);
  PyVTKAddFile_vtkPointSet(d, modulename);
  PyVTKAddFile_vtkPointSetSource(d, modulename);
  PyVTKAddFile_vtkPointSetToPointSetFilter(d, modulename);
  PyVTKAddFile_vtkPointsProjectedHull(d, modulename);
  PyVTKAddFile_vtkPolyDataAlgorithm(d, modulename);
  PyVTKAddFile_vtkPolyDataCollection(d, modulename);
  PyVTKAddFile_vtkPolyData(d, modulename);
  PyVTKAddFile_vtkPolyDataSource(d, modulename);
  PyVTKAddFile_vtkPolyDataToPolyDataFilter(d, modulename);
  PyVTKAddFile_vtkPolygon(d, modulename);
  PyVTKAddFile_vtkPolyhedron(d, modulename);
  PyVTKAddFile_vtkPolyLine(d, modulename);
  PyVTKAddFile_vtkPolyVertex(d, modulename);
  PyVTKAddFile_vtkProcessObject(d, modulename);
  PyVTKAddFile_vtkPropAssembly(d, modulename);
  PyVTKAddFile_vtkPyramid(d, modulename);
  PyVTKAddFile_vtkQuad(d, modulename);
  PyVTKAddFile_vtkQuadraticEdge(d, modulename);
  PyVTKAddFile_vtkQuadraticHexahedron(d, modulename);
  PyVTKAddFile_vtkQuadraticLinearQuad(d, modulename);
  PyVTKAddFile_vtkQuadraticLinearWedge(d, modulename);
  PyVTKAddFile_vtkQuadraticPyramid(d, modulename);
  PyVTKAddFile_vtkQuadraticQuad(d, modulename);
  PyVTKAddFile_vtkQuadraticTetra(d, modulename);
  PyVTKAddFile_vtkQuadraticTriangle(d, modulename);
  PyVTKAddFile_vtkQuadraticWedge(d, modulename);
  PyVTKAddFile_vtkRectilinearGridAlgorithm(d, modulename);
  PyVTKAddFile_vtkRectilinearGrid(d, modulename);
  PyVTKAddFile_vtkRectilinearGridSource(d, modulename);
  PyVTKAddFile_vtkRectilinearGridToPolyDataFilter(d, modulename);
  PyVTKAddFile_vtkReebGraph(d, modulename);
  PyVTKAddFile_vtkReebGraphSimplificationMetric(d, modulename);
  PyVTKAddFile_vtkScalarTree(d, modulename);
  PyVTKAddFile_vtkSelectionAlgorithm(d, modulename);
  PyVTKAddFile_vtkSelection(d, modulename);
  PyVTKAddFile_vtkSelectionNode(d, modulename);
  PyVTKAddFile_vtkSimpleCellTessellator(d, modulename);
  PyVTKAddFile_vtkSimpleImageToImageFilter(d, modulename);
  PyVTKAddFile_vtkSimpleScalarTree(d, modulename);
  PyVTKAddFile_vtkSmoothErrorMetric(d, modulename);
  PyVTKAddFile_vtkSource(d, modulename);
  PyVTKAddFile_vtkSphere(d, modulename);
  PyVTKAddFile_vtkSpline(d, modulename);
  PyVTKAddFile_vtkStreamingDemandDrivenPipeline(d, modulename);
  PyVTKAddFile_vtkStructuredGridAlgorithm(d, modulename);
  PyVTKAddFile_vtkStructuredGrid(d, modulename);
  PyVTKAddFile_vtkStructuredGridSource(d, modulename);
  PyVTKAddFile_vtkStructuredGridToPolyDataFilter(d, modulename);
  PyVTKAddFile_vtkStructuredGridToStructuredGridFilter(d, modulename);
  PyVTKAddFile_vtkStructuredPointsCollection(d, modulename);
  PyVTKAddFile_vtkStructuredPoints(d, modulename);
  PyVTKAddFile_vtkStructuredPointsSource(d, modulename);
  PyVTKAddFile_vtkStructuredPointsToPolyDataFilter(d, modulename);
  PyVTKAddFile_vtkStructuredPointsToStructuredPointsFilter(d, modulename);
  PyVTKAddFile_vtkStructuredPointsToUnstructuredGridFilter(d, modulename);
  PyVTKAddFile_vtkSuperquadric(d, modulename);
  PyVTKAddFile_vtkTableAlgorithm(d, modulename);
  PyVTKAddFile_vtkTable(d, modulename);
  PyVTKAddFile_vtkTemporalDataSetAlgorithm(d, modulename);
  PyVTKAddFile_vtkTemporalDataSet(d, modulename);
  PyVTKAddFile_vtkTetra(d, modulename);
  PyVTKAddFile_vtkThreadedImageAlgorithm(d, modulename);
  PyVTKAddFile_vtkThreadedStreamingPipeline(d, modulename);
  PyVTKAddFile_vtkTreeAlgorithm(d, modulename);
  PyVTKAddFile_vtkTree(d, modulename);
  PyVTKAddFile_vtkTreeBFSIterator(d, modulename);
  PyVTKAddFile_vtkTreeDFSIterator(d, modulename);
  PyVTKAddFile_vtkTriangle(d, modulename);
  PyVTKAddFile_vtkTriangleStrip(d, modulename);
  PyVTKAddFile_vtkTriQuadraticHexahedron(d, modulename);
  PyVTKAddFile_vtkTrivialProducer(d, modulename);
  PyVTKAddFile_vtkUndirectedGraphAlgorithm(d, modulename);
  PyVTKAddFile_vtkUndirectedGraph(d, modulename);
  PyVTKAddFile_vtkUniformGrid(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridAlgorithm(d, modulename);
  PyVTKAddFile_vtkUnstructuredGrid(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridSource(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridToPolyDataFilter(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridToUnstructuredGridFilter(d, modulename);
  PyVTKAddFile_vtkVertex(d, modulename);
  PyVTKAddFile_vtkVertexListIterator(d, modulename);
  PyVTKAddFile_vtkViewDependentErrorMetric(d, modulename);
  PyVTKAddFile_vtkViewport(d, modulename);
  PyVTKAddFile_vtkVoxel(d, modulename);
  PyVTKAddFile_vtkWedge(d, modulename);
  PyVTKAddFile_vtkArrayData(d, modulename);
  PyVTKAddFile_vtkArrayDataAlgorithm(d, modulename);
  PyVTKAddFile_vtkCellType(d, modulename);
}

