# Generated by CMake 2.8.7

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target vtkhdf5
ADD_LIBRARY(vtkhdf5 SHARED IMPORTED)

# Create imported target vtkWrapHierarchy
ADD_EXECUTABLE(vtkWrapHierarchy IMPORTED)

# Create imported target vtkWrapPython
ADD_EXECUTABLE(vtkWrapPython IMPORTED)

# Create imported target vtkWrapPythonInit
ADD_EXECUTABLE(vtkWrapPythonInit IMPORTED)

# Create imported target vtksys
ADD_LIBRARY(vtksys SHARED IMPORTED)

# Create imported target vtkzlib
ADD_LIBRARY(vtkzlib SHARED IMPORTED)

# Create imported target vtkjpeg
ADD_LIBRARY(vtkjpeg SHARED IMPORTED)

# Create imported target vtkpng
ADD_LIBRARY(vtkpng SHARED IMPORTED)

# Create imported target vtktiff
ADD_LIBRARY(vtktiff SHARED IMPORTED)

# Create imported target vtkexpat
ADD_LIBRARY(vtkexpat SHARED IMPORTED)

# Create imported target vtkfreetype
ADD_LIBRARY(vtkfreetype SHARED IMPORTED)

# Create imported target vtklibxml2
ADD_LIBRARY(vtklibxml2 SHARED IMPORTED)

# Create imported target vtkDICOMParser
ADD_LIBRARY(vtkDICOMParser SHARED IMPORTED)

# Create imported target vtkproj4
ADD_LIBRARY(vtkproj4 SHARED IMPORTED)

# Create imported target MapReduceMPI
ADD_LIBRARY(MapReduceMPI SHARED IMPORTED)

# Create imported target vtkverdict
ADD_LIBRARY(vtkverdict SHARED IMPORTED)

# Create imported target vtkNetCDF
ADD_LIBRARY(vtkNetCDF SHARED IMPORTED)

# Create imported target vtkNetCDF_cxx
ADD_LIBRARY(vtkNetCDF_cxx SHARED IMPORTED)

# Create imported target vtkmetaio
ADD_LIBRARY(vtkmetaio SHARED IMPORTED)

# Create imported target vtksqlite
ADD_LIBRARY(vtksqlite SHARED IMPORTED)

# Create imported target vtkexoIIc
ADD_LIBRARY(vtkexoIIc SHARED IMPORTED)

# Create imported target vtkalglib
ADD_LIBRARY(vtkalglib SHARED IMPORTED)

# Create imported target vtkEncodeString
ADD_EXECUTABLE(vtkEncodeString IMPORTED)

# Create imported target VPIC
ADD_LIBRARY(VPIC SHARED IMPORTED)

# Create imported target Cosmo
ADD_LIBRARY(Cosmo SHARED IMPORTED)

# Create imported target vtkftgl
ADD_LIBRARY(vtkftgl SHARED IMPORTED)

# Create imported target vtkCommon
ADD_LIBRARY(vtkCommon SHARED IMPORTED)

# Create imported target vtkCommonPythonD
ADD_LIBRARY(vtkCommonPythonD SHARED IMPORTED)

# Create imported target vtkFiltering
ADD_LIBRARY(vtkFiltering SHARED IMPORTED)

# Create imported target vtkFilteringPythonD
ADD_LIBRARY(vtkFilteringPythonD SHARED IMPORTED)

# Create imported target vtkImaging
ADD_LIBRARY(vtkImaging SHARED IMPORTED)

# Create imported target vtkImagingPythonD
ADD_LIBRARY(vtkImagingPythonD SHARED IMPORTED)

# Create imported target vtkGraphics
ADD_LIBRARY(vtkGraphics SHARED IMPORTED)

# Create imported target vtkGraphicsPythonD
ADD_LIBRARY(vtkGraphicsPythonD SHARED IMPORTED)

# Create imported target vtkGenericFiltering
ADD_LIBRARY(vtkGenericFiltering SHARED IMPORTED)

# Create imported target vtkGenericFilteringPythonD
ADD_LIBRARY(vtkGenericFilteringPythonD SHARED IMPORTED)

# Create imported target vtkIO
ADD_LIBRARY(vtkIO SHARED IMPORTED)

# Create imported target vtkIOPythonD
ADD_LIBRARY(vtkIOPythonD SHARED IMPORTED)

# Create imported target vtkRendering
ADD_LIBRARY(vtkRendering SHARED IMPORTED)

# Create imported target vtkRenderingPythonD
ADD_LIBRARY(vtkRenderingPythonD SHARED IMPORTED)

# Create imported target vtkVolumeRendering
ADD_LIBRARY(vtkVolumeRendering SHARED IMPORTED)

# Create imported target vtkVolumeRenderingPythonD
ADD_LIBRARY(vtkVolumeRenderingPythonD SHARED IMPORTED)

# Create imported target vtkHybrid
ADD_LIBRARY(vtkHybrid SHARED IMPORTED)

# Create imported target vtkHybridPythonD
ADD_LIBRARY(vtkHybridPythonD SHARED IMPORTED)

# Create imported target vtkWidgets
ADD_LIBRARY(vtkWidgets SHARED IMPORTED)

# Create imported target vtkWidgetsPythonD
ADD_LIBRARY(vtkWidgetsPythonD SHARED IMPORTED)

# Create imported target vtkParallel
ADD_LIBRARY(vtkParallel SHARED IMPORTED)

# Create imported target vtkParallelPythonD
ADD_LIBRARY(vtkParallelPythonD SHARED IMPORTED)

# Create imported target vtkInfovis
ADD_LIBRARY(vtkInfovis SHARED IMPORTED)

# Create imported target vtkInfovisPythonD
ADD_LIBRARY(vtkInfovisPythonD SHARED IMPORTED)

# Create imported target vtkGeovis
ADD_LIBRARY(vtkGeovis SHARED IMPORTED)

# Create imported target vtkGeovisPythonD
ADD_LIBRARY(vtkGeovisPythonD SHARED IMPORTED)

# Create imported target vtkViews
ADD_LIBRARY(vtkViews SHARED IMPORTED)

# Create imported target vtkViewsPythonD
ADD_LIBRARY(vtkViewsPythonD SHARED IMPORTED)

# Create imported target vtkCharts
ADD_LIBRARY(vtkCharts SHARED IMPORTED)

# Create imported target vtkChartsPythonD
ADD_LIBRARY(vtkChartsPythonD SHARED IMPORTED)

# Create imported target vtkPythonCore
ADD_LIBRARY(vtkPythonCore SHARED IMPORTED)

# Create imported target vtkpython
ADD_EXECUTABLE(vtkpython IMPORTED)

# Create imported target pvtkpython
ADD_EXECUTABLE(pvtkpython IMPORTED)

# Import target "vtkhdf5" for configuration "Release"
SET_PROPERTY(TARGET vtkhdf5 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkhdf5 PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "m;vtkzlib"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkhdf5.so.1.8.5"
  IMPORTED_SONAME_RELEASE "libvtkhdf5.so.1.8.5"
  )

# Import target "vtkWrapHierarchy" for configuration "Release"
SET_PROPERTY(TARGET vtkWrapHierarchy APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkWrapHierarchy PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/vtkWrapHierarchy"
  )

# Import target "vtkWrapPython" for configuration "Release"
SET_PROPERTY(TARGET vtkWrapPython APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkWrapPython PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/vtkWrapPython"
  )

# Import target "vtkWrapPythonInit" for configuration "Release"
SET_PROPERTY(TARGET vtkWrapPythonInit APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkWrapPythonInit PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/vtkWrapPythonInit"
  )

# Import target "vtksys" for configuration "Release"
SET_PROPERTY(TARGET vtksys APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtksys PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "dl"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtksys.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtksys.so.5.8"
  )

# Import target "vtkzlib" for configuration "Release"
SET_PROPERTY(TARGET vtkzlib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkzlib PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkzlib.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkzlib.so.5.8"
  )

# Import target "vtkjpeg" for configuration "Release"
SET_PROPERTY(TARGET vtkjpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkjpeg PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkjpeg.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkjpeg.so.5.8"
  )

# Import target "vtkpng" for configuration "Release"
SET_PROPERTY(TARGET vtkpng APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkpng PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkzlib;-lm"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkpng.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkpng.so.5.8"
  )

# Import target "vtktiff" for configuration "Release"
SET_PROPERTY(TARGET vtktiff APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtktiff PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkzlib;vtkjpeg;-lm"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtktiff.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtktiff.so.5.8"
  )

# Import target "vtkexpat" for configuration "Release"
SET_PROPERTY(TARGET vtkexpat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkexpat PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkexpat.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkexpat.so.5.8"
  )

# Import target "vtkfreetype" for configuration "Release"
SET_PROPERTY(TARGET vtkfreetype APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkfreetype PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkfreetype.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkfreetype.so.5.8"
  )

# Import target "vtklibxml2" for configuration "Release"
SET_PROPERTY(TARGET vtklibxml2 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtklibxml2 PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkzlib;dl;-lpthread;dl;m"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtklibxml2.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtklibxml2.so.5.8"
  )

# Import target "vtkDICOMParser" for configuration "Release"
SET_PROPERTY(TARGET vtkDICOMParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkDICOMParser PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkDICOMParser.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkDICOMParser.so.5.8"
  )

# Import target "vtkproj4" for configuration "Release"
SET_PROPERTY(TARGET vtkproj4 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkproj4 PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "m"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkproj4.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkproj4.so.5.8"
  )

# Import target "MapReduceMPI" for configuration "Release"
SET_PROPERTY(TARGET MapReduceMPI APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(MapReduceMPI PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "/usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so;/usr/lib/openmpi/lib/libopen-rte.so;/usr/lib/openmpi/lib/libopen-pal.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libnsl.so;/usr/lib/x86_64-linux-gnu/libutil.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libMapReduceMPI.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libMapReduceMPI.so.5.8"
  )

# Import target "vtkverdict" for configuration "Release"
SET_PROPERTY(TARGET vtkverdict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkverdict PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkverdict.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkverdict.so.5.8"
  )

# Import target "vtkNetCDF" for configuration "Release"
SET_PROPERTY(TARGET vtkNetCDF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkNetCDF PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkNetCDF.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkNetCDF.so.5.8"
  )

# Import target "vtkNetCDF_cxx" for configuration "Release"
SET_PROPERTY(TARGET vtkNetCDF_cxx APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkNetCDF_cxx PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkNetCDF"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkNetCDF_cxx.so"
  IMPORTED_SONAME_RELEASE "libvtkNetCDF_cxx.so"
  )

# Import target "vtkmetaio" for configuration "Release"
SET_PROPERTY(TARGET vtkmetaio APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkmetaio PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkzlib;vtksys"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkmetaio.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkmetaio.so.5.8"
  )

# Import target "vtksqlite" for configuration "Release"
SET_PROPERTY(TARGET vtksqlite APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtksqlite PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "-lpthread"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtksqlite.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtksqlite.so.5.8"
  )

# Import target "vtkexoIIc" for configuration "Release"
SET_PROPERTY(TARGET vtkexoIIc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkexoIIc PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkNetCDF"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkexoIIc.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkexoIIc.so.5.8"
  )

# Import target "vtkalglib" for configuration "Release"
SET_PROPERTY(TARGET vtkalglib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkalglib PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkalglib.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkalglib.so.5.8"
  )

# Import target "vtkEncodeString" for configuration "Release"
SET_PROPERTY(TARGET vtkEncodeString APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkEncodeString PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/vtkEncodeString"
  )

# Import target "VPIC" for configuration "Release"
SET_PROPERTY(TARGET VPIC APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(VPIC PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtksys;/usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so;/usr/lib/openmpi/lib/libopen-rte.so;/usr/lib/openmpi/lib/libopen-pal.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libnsl.so;/usr/lib/x86_64-linux-gnu/libutil.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libVPIC.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libVPIC.so.5.8"
  )

# Import target "Cosmo" for configuration "Release"
SET_PROPERTY(TARGET Cosmo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(Cosmo PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtksys;vtkCommon;/usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so;/usr/lib/openmpi/lib/libopen-rte.so;/usr/lib/openmpi/lib/libopen-pal.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libnsl.so;/usr/lib/x86_64-linux-gnu/libutil.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libCosmo.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libCosmo.so.5.8"
  )

# Import target "vtkftgl" for configuration "Release"
SET_PROPERTY(TARGET vtkftgl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkftgl PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "/usr/lib/x86_64-linux-gnu/libGL.so;vtkfreetype"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkftgl.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkftgl.so.5.8"
  )

# Import target "vtkCommon" for configuration "Release"
SET_PROPERTY(TARGET vtkCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkCommon PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtksys;-lm"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkCommon.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkCommon.so.5.8"
  )

# Import target "vtkCommonPythonD" for configuration "Release"
SET_PROPERTY(TARGET vtkCommonPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkCommonPythonD PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkCommon;vtkPythonCore"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkCommonPythonD.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkCommonPythonD.so.5.8"
  )

# Import target "vtkFiltering" for configuration "Release"
SET_PROPERTY(TARGET vtkFiltering APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkFiltering PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkCommon"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkFiltering.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkFiltering.so.5.8"
  )

# Import target "vtkFilteringPythonD" for configuration "Release"
SET_PROPERTY(TARGET vtkFilteringPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkFilteringPythonD PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkFiltering;vtkPythonCore;vtkCommonPythonD"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkFilteringPythonD.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkFilteringPythonD.so.5.8"
  )

# Import target "vtkImaging" for configuration "Release"
SET_PROPERTY(TARGET vtkImaging APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkImaging PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkFiltering"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkImaging.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkImaging.so.5.8"
  )

# Import target "vtkImagingPythonD" for configuration "Release"
SET_PROPERTY(TARGET vtkImagingPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkImagingPythonD PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkImaging;vtkPythonCore;vtkFilteringPythonD"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkImagingPythonD.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkImagingPythonD.so.5.8"
  )

# Import target "vtkGraphics" for configuration "Release"
SET_PROPERTY(TARGET vtkGraphics APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkGraphics PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "vtkverdict"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkFiltering"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkGraphics.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkGraphics.so.5.8"
  )

# Import target "vtkGraphicsPythonD" for configuration "Release"
SET_PROPERTY(TARGET vtkGraphicsPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkGraphicsPythonD PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkGraphics;vtkPythonCore;vtkFilteringPythonD"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkGraphicsPythonD.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkGraphicsPythonD.so.5.8"
  )

# Import target "vtkGenericFiltering" for configuration "Release"
SET_PROPERTY(TARGET vtkGenericFiltering APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkGenericFiltering PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkFiltering;vtkGraphics"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkGenericFiltering.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkGenericFiltering.so.5.8"
  )

# Import target "vtkGenericFilteringPythonD" for configuration "Release"
SET_PROPERTY(TARGET vtkGenericFilteringPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkGenericFilteringPythonD PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkGenericFiltering;vtkPythonCore;vtkFilteringPythonD;vtkGraphicsPythonD"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkGenericFilteringPythonD.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkGenericFilteringPythonD.so.5.8"
  )

# Import target "vtkIO" for configuration "Release"
SET_PROPERTY(TARGET vtkIO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkIO PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "vtkDICOMParser;vtkNetCDF;vtkNetCDF_cxx;vtkmetaio;vtksqlite;vtkpng;vtkzlib;vtkjpeg;vtktiff;vtkexpat;vtksys"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkFiltering"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkIO.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkIO.so.5.8"
  )

# Import target "vtkIOPythonD" for configuration "Release"
SET_PROPERTY(TARGET vtkIOPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkIOPythonD PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkIO;vtkPythonCore;vtkFilteringPythonD"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkIOPythonD.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkIOPythonD.so.5.8"
  )

# Import target "vtkRendering" for configuration "Release"
SET_PROPERTY(TARGET vtkRendering APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkRendering PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "vtkIO;vtkftgl;vtkfreetype"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkGraphics;vtkImaging"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkRendering.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkRendering.so.5.8"
  )

# Import target "vtkRenderingPythonD" for configuration "Release"
SET_PROPERTY(TARGET vtkRenderingPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkRenderingPythonD PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkRendering;vtkPythonCore;vtkGraphicsPythonD;vtkImagingPythonD"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkRenderingPythonD.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkRenderingPythonD.so.5.8"
  )

# Import target "vtkVolumeRendering" for configuration "Release"
SET_PROPERTY(TARGET vtkVolumeRendering APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkVolumeRendering PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkRendering;vtkIO"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkVolumeRendering.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkVolumeRendering.so.5.8"
  )

# Import target "vtkVolumeRenderingPythonD" for configuration "Release"
SET_PROPERTY(TARGET vtkVolumeRenderingPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkVolumeRenderingPythonD PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkVolumeRendering;vtkPythonCore;vtkRenderingPythonD;vtkIOPythonD"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkVolumeRenderingPythonD.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkVolumeRenderingPythonD.so.5.8"
  )

# Import target "vtkHybrid" for configuration "Release"
SET_PROPERTY(TARGET vtkHybrid APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkHybrid PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "vtkexoIIc;vtkftgl"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkRendering;vtkIO;vtkParallel"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkHybrid.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkHybrid.so.5.8"
  )

# Import target "vtkHybridPythonD" for configuration "Release"
SET_PROPERTY(TARGET vtkHybridPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkHybridPythonD PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkHybrid;vtkPythonCore;vtkRenderingPythonD;vtkIOPythonD"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkHybridPythonD.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkHybridPythonD.so.5.8"
  )

# Import target "vtkWidgets" for configuration "Release"
SET_PROPERTY(TARGET vtkWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkWidgets PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkRendering;vtkHybrid;vtkVolumeRendering"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkWidgets.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkWidgets.so.5.8"
  )

# Import target "vtkWidgetsPythonD" for configuration "Release"
SET_PROPERTY(TARGET vtkWidgetsPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkWidgetsPythonD PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkWidgets;vtkPythonCore;vtkRenderingPythonD;vtkHybridPythonD"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkWidgetsPythonD.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkWidgetsPythonD.so.5.8"
  )

# Import target "vtkParallel" for configuration "Release"
SET_PROPERTY(TARGET vtkParallel APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkParallel PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "VPIC;Cosmo;vtkexoIIc"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkRendering;vtkIO"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkParallel.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkParallel.so.5.8"
  )

# Import target "vtkParallelPythonD" for configuration "Release"
SET_PROPERTY(TARGET vtkParallelPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkParallelPythonD PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkParallel;vtkPythonCore;vtkRenderingPythonD;vtkIOPythonD"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkParallelPythonD.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkParallelPythonD.so.5.8"
  )

# Import target "vtkInfovis" for configuration "Release"
SET_PROPERTY(TARGET vtkInfovis APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkInfovis PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "vtklibxml2;vtkalglib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkWidgets;vtkParallel"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkInfovis.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkInfovis.so.5.8"
  )

# Import target "vtkInfovisPythonD" for configuration "Release"
SET_PROPERTY(TARGET vtkInfovisPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkInfovisPythonD PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkInfovis;vtkPythonCore;vtkWidgetsPythonD"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkInfovisPythonD.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkInfovisPythonD.so.5.8"
  )

# Import target "vtkGeovis" for configuration "Release"
SET_PROPERTY(TARGET vtkGeovis APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkGeovis PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "vtkproj4"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkWidgets;vtkViews"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkGeovis.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkGeovis.so.5.8"
  )

# Import target "vtkGeovisPythonD" for configuration "Release"
SET_PROPERTY(TARGET vtkGeovisPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkGeovisPythonD PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkGeovis;vtkPythonCore;vtkWidgetsPythonD;vtkViewsPythonD"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkGeovisPythonD.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkGeovisPythonD.so.5.8"
  )

# Import target "vtkViews" for configuration "Release"
SET_PROPERTY(TARGET vtkViews APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkViews PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkInfovis"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkViews.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkViews.so.5.8"
  )

# Import target "vtkViewsPythonD" for configuration "Release"
SET_PROPERTY(TARGET vtkViewsPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkViewsPythonD PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkViews;vtkPythonCore;vtkInfovisPythonD"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkViewsPythonD.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkViewsPythonD.so.5.8"
  )

# Import target "vtkCharts" for configuration "Release"
SET_PROPERTY(TARGET vtkCharts APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkCharts PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "vtkftgl"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkViews"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkCharts.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkCharts.so.5.8"
  )

# Import target "vtkChartsPythonD" for configuration "Release"
SET_PROPERTY(TARGET vtkChartsPythonD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkChartsPythonD PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkCharts;vtkPythonCore;vtkViewsPythonD"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkChartsPythonD.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkChartsPythonD.so.5.8"
  )

# Import target "vtkPythonCore" for configuration "Release"
SET_PROPERTY(TARGET vtkPythonCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkPythonCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkCommon"
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/libvtkPythonCore.so.5.8.0"
  IMPORTED_SONAME_RELEASE "libvtkPythonCore.so.5.8"
  )

# Import target "vtkpython" for configuration "Release"
SET_PROPERTY(TARGET vtkpython APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkpython PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/vtkpython"
  )

# Import target "pvtkpython" for configuration "Release"
SET_PROPERTY(TARGET pvtkpython APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(pvtkpython PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/lakers/Downloads/VTK/bin/pvtkpython"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
