// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPython.h"

#include "vtkSystemIncludes.h"
#include <string.h>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings 

extern  "C" {PyObject *PyVTKAddFile_vtkAddMembershipArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAppendPoints(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkApplyColors(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkApplyIcons(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArcParallelEdgeStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAreaLayout(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAreaLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAssignCoordinates(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAssignCoordinatesLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBivariateLinearTableThreshold(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBivariateStatisticsAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBoxLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkChacoGraphReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCircularLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkClustering2DLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCollapseGraph(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCollapseVerticesByArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCommunity2DLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkConeLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkConstrained2DLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkContingencyStatistics(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCorrelativeStatistics(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCosmicTreeLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataObjectToTable(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDelimitedTextReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDescriptiveStatistics(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDIMACSGraphReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDIMACSGraphWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEdgeCenters(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEdgeLayout(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEdgeLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExpandSelectedGraph(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractSelectedGraph(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFast2DLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFixedWidthTextReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkForceDirectedLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenerateIndexArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGeoEdgeStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGeoMath(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGraphHierarchicalBundle(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGraphHierarchicalBundleEdges(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGraphLayout(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGraphLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGroupLeafVertices(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkISIReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkKMeansDistanceFunctor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkKMeansDistanceFunctorCalculator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkKMeansStatistics(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMergeColumns(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMergeGraphs(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMergeTables(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMultiCorrelativeStatistics(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMutableGraphHelper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkNetworkHierarchy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOrderStatistics(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPassArrays(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPassThrough(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPassThroughEdgeStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPassThroughLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPerturbCoincidentVertices(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPCAStatistics(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPruneTreeFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRISReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRandomGraphSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRandomLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRemoveIsolatedVertices(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRemoveHiddenData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSCurveSpline(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSimple2DLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSimple3DCirclesStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSliceAndDiceLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSplineGraphEdges(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSplitColumnComponents(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSquarifyLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSpanTreeLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStackedTreeLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStatisticsAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStrahlerMetric(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStreamGraph(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStreamingStatistics(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStringToCategory(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStringToNumeric(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTableToGraph(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTableToTreeFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkThresholdGraph(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkThresholdTable(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTransferAttributes(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTreeFieldAggregator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTreeLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTreeOrbitLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTreeLevelsFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTreeMapLayout(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTreeMapLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTreeMapToPolyData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTreeRingToPolyData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTulipReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnivariateStatisticsAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAttributeClustering2DLayoutStrategy(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVertexDegree(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXGMLReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLTreeReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAdjacencyMatrixToEdgeTable(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArrayNorm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArrayToTable(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkComputeHistogram2DOutliers(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDiagonalMatrixSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDotProductSimilarity(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractHistogram2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMatricizeArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkNormalizeMatrixVectors(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPairwiseExtractHistogram2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSparseArrayToTable(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTableToArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTableToSparseArray(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTransposeMatrix(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPBivariateLinearTableThreshold(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPCorrelativeStatistics(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPContingencyStatistics(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPDescriptiveStatistics(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPKMeansStatistics(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPMultiCorrelativeStatistics(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPOrderStatistics(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPPCAStatistics(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPComputeHistogram2DOutliers(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPExtractHistogram2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPPairwiseExtractHistogram2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSQLDatabaseGraphSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSQLDatabaseTableSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSQLGraphReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStringToTimePoint(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTimePointToString(PyObject *, const char *); }

static PyMethodDef PyvtkInfovisPython_ClassMethods[] = {
{NULL, NULL, 0, NULL}};

static void real_initvtkInfovisPython(const char *modulename);

extern  "C" { void initvtkInfovisPython(); }

void initvtkInfovisPython()
{
  static const char modulename[] = "vtkInfovisPython";
  real_initvtkInfovisPython(modulename);
}

extern  "C" { void initlibvtkInfovisPython(); }

void initlibvtkInfovisPython()
{
  static const char modulename[] = "libvtkInfovisPython";
  real_initvtkInfovisPython(modulename);
}

void real_initvtkInfovisPython(const char *modulename)
{
  PyObject *m, *d;

  m = Py_InitModule((char*)modulename, PyvtkInfovisPython_ClassMethods);
  d = PyModule_GetDict(m);
  if (!d)
    {
    Py_FatalError((char*)"can't get dictionary for module vtkInfovisPython");
    }
  PyVTKAddFile_vtkAddMembershipArray(d, modulename);
  PyVTKAddFile_vtkAppendPoints(d, modulename);
  PyVTKAddFile_vtkApplyColors(d, modulename);
  PyVTKAddFile_vtkApplyIcons(d, modulename);
  PyVTKAddFile_vtkArcParallelEdgeStrategy(d, modulename);
  PyVTKAddFile_vtkAreaLayout(d, modulename);
  PyVTKAddFile_vtkAreaLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkAssignCoordinates(d, modulename);
  PyVTKAddFile_vtkAssignCoordinatesLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkBivariateLinearTableThreshold(d, modulename);
  PyVTKAddFile_vtkBivariateStatisticsAlgorithm(d, modulename);
  PyVTKAddFile_vtkBoxLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkChacoGraphReader(d, modulename);
  PyVTKAddFile_vtkCircularLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkClustering2DLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkCollapseGraph(d, modulename);
  PyVTKAddFile_vtkCollapseVerticesByArray(d, modulename);
  PyVTKAddFile_vtkCommunity2DLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkConeLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkConstrained2DLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkContingencyStatistics(d, modulename);
  PyVTKAddFile_vtkCorrelativeStatistics(d, modulename);
  PyVTKAddFile_vtkCosmicTreeLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkDataObjectToTable(d, modulename);
  PyVTKAddFile_vtkDelimitedTextReader(d, modulename);
  PyVTKAddFile_vtkDescriptiveStatistics(d, modulename);
  PyVTKAddFile_vtkDIMACSGraphReader(d, modulename);
  PyVTKAddFile_vtkDIMACSGraphWriter(d, modulename);
  PyVTKAddFile_vtkEdgeCenters(d, modulename);
  PyVTKAddFile_vtkEdgeLayout(d, modulename);
  PyVTKAddFile_vtkEdgeLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkExpandSelectedGraph(d, modulename);
  PyVTKAddFile_vtkExtractSelectedGraph(d, modulename);
  PyVTKAddFile_vtkFast2DLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkFixedWidthTextReader(d, modulename);
  PyVTKAddFile_vtkForceDirectedLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkGenerateIndexArray(d, modulename);
  PyVTKAddFile_vtkGeoEdgeStrategy(d, modulename);
  PyVTKAddFile_vtkGeoMath(d, modulename);
  PyVTKAddFile_vtkGraphHierarchicalBundle(d, modulename);
  PyVTKAddFile_vtkGraphHierarchicalBundleEdges(d, modulename);
  PyVTKAddFile_vtkGraphLayout(d, modulename);
  PyVTKAddFile_vtkGraphLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkGroupLeafVertices(d, modulename);
  PyVTKAddFile_vtkISIReader(d, modulename);
  PyVTKAddFile_vtkKMeansDistanceFunctor(d, modulename);
  PyVTKAddFile_vtkKMeansDistanceFunctorCalculator(d, modulename);
  PyVTKAddFile_vtkKMeansStatistics(d, modulename);
  PyVTKAddFile_vtkMergeColumns(d, modulename);
  PyVTKAddFile_vtkMergeGraphs(d, modulename);
  PyVTKAddFile_vtkMergeTables(d, modulename);
  PyVTKAddFile_vtkMultiCorrelativeStatistics(d, modulename);
  PyVTKAddFile_vtkMutableGraphHelper(d, modulename);
  PyVTKAddFile_vtkNetworkHierarchy(d, modulename);
  PyVTKAddFile_vtkOrderStatistics(d, modulename);
  PyVTKAddFile_vtkPassArrays(d, modulename);
  PyVTKAddFile_vtkPassThrough(d, modulename);
  PyVTKAddFile_vtkPassThroughEdgeStrategy(d, modulename);
  PyVTKAddFile_vtkPassThroughLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkPerturbCoincidentVertices(d, modulename);
  PyVTKAddFile_vtkPCAStatistics(d, modulename);
  PyVTKAddFile_vtkPruneTreeFilter(d, modulename);
  PyVTKAddFile_vtkRISReader(d, modulename);
  PyVTKAddFile_vtkRandomGraphSource(d, modulename);
  PyVTKAddFile_vtkRandomLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkRemoveIsolatedVertices(d, modulename);
  PyVTKAddFile_vtkRemoveHiddenData(d, modulename);
  PyVTKAddFile_vtkSCurveSpline(d, modulename);
  PyVTKAddFile_vtkSimple2DLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkSimple3DCirclesStrategy(d, modulename);
  PyVTKAddFile_vtkSliceAndDiceLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkSplineGraphEdges(d, modulename);
  PyVTKAddFile_vtkSplitColumnComponents(d, modulename);
  PyVTKAddFile_vtkSquarifyLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkSpanTreeLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkStackedTreeLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkStatisticsAlgorithm(d, modulename);
  PyVTKAddFile_vtkStrahlerMetric(d, modulename);
  PyVTKAddFile_vtkStreamGraph(d, modulename);
  PyVTKAddFile_vtkStreamingStatistics(d, modulename);
  PyVTKAddFile_vtkStringToCategory(d, modulename);
  PyVTKAddFile_vtkStringToNumeric(d, modulename);
  PyVTKAddFile_vtkTableToGraph(d, modulename);
  PyVTKAddFile_vtkTableToTreeFilter(d, modulename);
  PyVTKAddFile_vtkThresholdGraph(d, modulename);
  PyVTKAddFile_vtkThresholdTable(d, modulename);
  PyVTKAddFile_vtkTransferAttributes(d, modulename);
  PyVTKAddFile_vtkTreeFieldAggregator(d, modulename);
  PyVTKAddFile_vtkTreeLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkTreeOrbitLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkTreeLevelsFilter(d, modulename);
  PyVTKAddFile_vtkTreeMapLayout(d, modulename);
  PyVTKAddFile_vtkTreeMapLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkTreeMapToPolyData(d, modulename);
  PyVTKAddFile_vtkTreeRingToPolyData(d, modulename);
  PyVTKAddFile_vtkTulipReader(d, modulename);
  PyVTKAddFile_vtkUnivariateStatisticsAlgorithm(d, modulename);
  PyVTKAddFile_vtkAttributeClustering2DLayoutStrategy(d, modulename);
  PyVTKAddFile_vtkVertexDegree(d, modulename);
  PyVTKAddFile_vtkXGMLReader(d, modulename);
  PyVTKAddFile_vtkXMLTreeReader(d, modulename);
  PyVTKAddFile_vtkAdjacencyMatrixToEdgeTable(d, modulename);
  PyVTKAddFile_vtkArrayNorm(d, modulename);
  PyVTKAddFile_vtkArrayToTable(d, modulename);
  PyVTKAddFile_vtkComputeHistogram2DOutliers(d, modulename);
  PyVTKAddFile_vtkDiagonalMatrixSource(d, modulename);
  PyVTKAddFile_vtkDotProductSimilarity(d, modulename);
  PyVTKAddFile_vtkExtractArray(d, modulename);
  PyVTKAddFile_vtkExtractHistogram2D(d, modulename);
  PyVTKAddFile_vtkMatricizeArray(d, modulename);
  PyVTKAddFile_vtkNormalizeMatrixVectors(d, modulename);
  PyVTKAddFile_vtkPairwiseExtractHistogram2D(d, modulename);
  PyVTKAddFile_vtkSparseArrayToTable(d, modulename);
  PyVTKAddFile_vtkTableToArray(d, modulename);
  PyVTKAddFile_vtkTableToSparseArray(d, modulename);
  PyVTKAddFile_vtkTransposeMatrix(d, modulename);
  PyVTKAddFile_vtkPBivariateLinearTableThreshold(d, modulename);
  PyVTKAddFile_vtkPCorrelativeStatistics(d, modulename);
  PyVTKAddFile_vtkPContingencyStatistics(d, modulename);
  PyVTKAddFile_vtkPDescriptiveStatistics(d, modulename);
  PyVTKAddFile_vtkPKMeansStatistics(d, modulename);
  PyVTKAddFile_vtkPMultiCorrelativeStatistics(d, modulename);
  PyVTKAddFile_vtkPOrderStatistics(d, modulename);
  PyVTKAddFile_vtkPPCAStatistics(d, modulename);
  PyVTKAddFile_vtkPComputeHistogram2DOutliers(d, modulename);
  PyVTKAddFile_vtkPExtractHistogram2D(d, modulename);
  PyVTKAddFile_vtkPPairwiseExtractHistogram2D(d, modulename);
  PyVTKAddFile_vtkSQLDatabaseGraphSource(d, modulename);
  PyVTKAddFile_vtkSQLDatabaseTableSource(d, modulename);
  PyVTKAddFile_vtkSQLGraphReader(d, modulename);
  PyVTKAddFile_vtkStringToTimePoint(d, modulename);
  PyVTKAddFile_vtkTimePointToString(d, modulename);
}

