// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPython.h"

#include "vtkSystemIncludes.h"
#include <string.h>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings 

extern  "C" {PyObject *PyVTKAddFile_vtkBooleanTexture(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExtractVOI(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFastSplatter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGaussianSplatter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageAccumulate(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageAnisotropicDiffusion2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageAnisotropicDiffusion3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageAppend(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageAppendComponents(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageBlend(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageButterworthHighPass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageButterworthLowPass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageCacheFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageCanvasSource2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageCast(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageChangeInformation(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageCheckerboard(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageCityBlockDistance(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageClip(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageConnector(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageConstantPad(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageContinuousDilate3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageContinuousErode3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageConvolve(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageCorrelation(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageCursor3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageDataStreamer(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageDecomposeFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageDifference(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageDilateErode3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageDivergence(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageDotProduct(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageEllipsoidSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageEuclideanDistance(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageEuclideanToPolar(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageExport(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageExtractComponents(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageFFT(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageFlip(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageFourierCenter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageFourierFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageGaussianSmooth(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageGaussianSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageGradient(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageGradientMagnitude(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageGridSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageHSIToRGB(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageHSVToRGB(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageHybridMedian2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageIdealHighPass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageIdealLowPass(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageImport(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageImportExecutive(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageIslandRemoval2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageIterateFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageLaplacian(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageLogarithmicScale(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageLogic(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageLuminance(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageMagnify(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageMagnitude(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageMandelbrotSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageMapToColors(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageMapToRGBA(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageMapToWindowLevelColors(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageMask(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageMaskBits(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageMathematics(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageMedian3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageMirrorPad(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageNoiseSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageNonMaximumSuppression(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageNormalize(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageOpenClose3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImagePadFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImagePermute(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageSlab(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageQuantizeRGBToIndex(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageRFFT(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageRGBToHSI(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageRGBToHSV(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageRange3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageRectilinearWipe(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageResample(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageReslice(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageSeedConnectivity(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageSeparableConvolution(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageShiftScale(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageShrink3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageSinusoidSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageSkeleton2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageSobel2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageSobel3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageSpatialAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageStencil(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageStencilToImage(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageStencilAlgorithm(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageStencilData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageStencilSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageThreshold(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageToImageStencil(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageTranslateExtent(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageVariance3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageWrapPad(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageWeightedSum(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImplicitFunctionToImageStencil(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLassoStencilSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPointLoad(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkROIStencilSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRTAnalyticSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSampleFunction(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkShepardMethod(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSimpleImageFilterExample(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSurfaceReconstructionFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTriangularTexture(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVoxelModeller(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageSpatialFilter(PyObject *, const char *); }

static PyMethodDef PyvtkImagingPython_ClassMethods[] = {
{NULL, NULL, 0, NULL}};

static void real_initvtkImagingPython(const char *modulename);

extern  "C" { void initvtkImagingPython(); }

void initvtkImagingPython()
{
  static const char modulename[] = "vtkImagingPython";
  real_initvtkImagingPython(modulename);
}

extern  "C" { void initlibvtkImagingPython(); }

void initlibvtkImagingPython()
{
  static const char modulename[] = "libvtkImagingPython";
  real_initvtkImagingPython(modulename);
}

void real_initvtkImagingPython(const char *modulename)
{
  PyObject *m, *d;

  m = Py_InitModule((char*)modulename, PyvtkImagingPython_ClassMethods);
  d = PyModule_GetDict(m);
  if (!d)
    {
    Py_FatalError((char*)"can't get dictionary for module vtkImagingPython");
    }
  PyVTKAddFile_vtkBooleanTexture(d, modulename);
  PyVTKAddFile_vtkExtractVOI(d, modulename);
  PyVTKAddFile_vtkFastSplatter(d, modulename);
  PyVTKAddFile_vtkGaussianSplatter(d, modulename);
  PyVTKAddFile_vtkImageAccumulate(d, modulename);
  PyVTKAddFile_vtkImageAnisotropicDiffusion2D(d, modulename);
  PyVTKAddFile_vtkImageAnisotropicDiffusion3D(d, modulename);
  PyVTKAddFile_vtkImageAppend(d, modulename);
  PyVTKAddFile_vtkImageAppendComponents(d, modulename);
  PyVTKAddFile_vtkImageBlend(d, modulename);
  PyVTKAddFile_vtkImageButterworthHighPass(d, modulename);
  PyVTKAddFile_vtkImageButterworthLowPass(d, modulename);
  PyVTKAddFile_vtkImageCacheFilter(d, modulename);
  PyVTKAddFile_vtkImageCanvasSource2D(d, modulename);
  PyVTKAddFile_vtkImageCast(d, modulename);
  PyVTKAddFile_vtkImageChangeInformation(d, modulename);
  PyVTKAddFile_vtkImageCheckerboard(d, modulename);
  PyVTKAddFile_vtkImageCityBlockDistance(d, modulename);
  PyVTKAddFile_vtkImageClip(d, modulename);
  PyVTKAddFile_vtkImageConnector(d, modulename);
  PyVTKAddFile_vtkImageConstantPad(d, modulename);
  PyVTKAddFile_vtkImageContinuousDilate3D(d, modulename);
  PyVTKAddFile_vtkImageContinuousErode3D(d, modulename);
  PyVTKAddFile_vtkImageConvolve(d, modulename);
  PyVTKAddFile_vtkImageCorrelation(d, modulename);
  PyVTKAddFile_vtkImageCursor3D(d, modulename);
  PyVTKAddFile_vtkImageDataStreamer(d, modulename);
  PyVTKAddFile_vtkImageDecomposeFilter(d, modulename);
  PyVTKAddFile_vtkImageDifference(d, modulename);
  PyVTKAddFile_vtkImageDilateErode3D(d, modulename);
  PyVTKAddFile_vtkImageDivergence(d, modulename);
  PyVTKAddFile_vtkImageDotProduct(d, modulename);
  PyVTKAddFile_vtkImageEllipsoidSource(d, modulename);
  PyVTKAddFile_vtkImageEuclideanDistance(d, modulename);
  PyVTKAddFile_vtkImageEuclideanToPolar(d, modulename);
  PyVTKAddFile_vtkImageExport(d, modulename);
  PyVTKAddFile_vtkImageExtractComponents(d, modulename);
  PyVTKAddFile_vtkImageFFT(d, modulename);
  PyVTKAddFile_vtkImageFlip(d, modulename);
  PyVTKAddFile_vtkImageFourierCenter(d, modulename);
  PyVTKAddFile_vtkImageFourierFilter(d, modulename);
  PyVTKAddFile_vtkImageGaussianSmooth(d, modulename);
  PyVTKAddFile_vtkImageGaussianSource(d, modulename);
  PyVTKAddFile_vtkImageGradient(d, modulename);
  PyVTKAddFile_vtkImageGradientMagnitude(d, modulename);
  PyVTKAddFile_vtkImageGridSource(d, modulename);
  PyVTKAddFile_vtkImageHSIToRGB(d, modulename);
  PyVTKAddFile_vtkImageHSVToRGB(d, modulename);
  PyVTKAddFile_vtkImageHybridMedian2D(d, modulename);
  PyVTKAddFile_vtkImageIdealHighPass(d, modulename);
  PyVTKAddFile_vtkImageIdealLowPass(d, modulename);
  PyVTKAddFile_vtkImageImport(d, modulename);
  PyVTKAddFile_vtkImageImportExecutive(d, modulename);
  PyVTKAddFile_vtkImageIslandRemoval2D(d, modulename);
  PyVTKAddFile_vtkImageIterateFilter(d, modulename);
  PyVTKAddFile_vtkImageLaplacian(d, modulename);
  PyVTKAddFile_vtkImageLogarithmicScale(d, modulename);
  PyVTKAddFile_vtkImageLogic(d, modulename);
  PyVTKAddFile_vtkImageLuminance(d, modulename);
  PyVTKAddFile_vtkImageMagnify(d, modulename);
  PyVTKAddFile_vtkImageMagnitude(d, modulename);
  PyVTKAddFile_vtkImageMandelbrotSource(d, modulename);
  PyVTKAddFile_vtkImageMapToColors(d, modulename);
  PyVTKAddFile_vtkImageMapToRGBA(d, modulename);
  PyVTKAddFile_vtkImageMapToWindowLevelColors(d, modulename);
  PyVTKAddFile_vtkImageMask(d, modulename);
  PyVTKAddFile_vtkImageMaskBits(d, modulename);
  PyVTKAddFile_vtkImageMathematics(d, modulename);
  PyVTKAddFile_vtkImageMedian3D(d, modulename);
  PyVTKAddFile_vtkImageMirrorPad(d, modulename);
  PyVTKAddFile_vtkImageNoiseSource(d, modulename);
  PyVTKAddFile_vtkImageNonMaximumSuppression(d, modulename);
  PyVTKAddFile_vtkImageNormalize(d, modulename);
  PyVTKAddFile_vtkImageOpenClose3D(d, modulename);
  PyVTKAddFile_vtkImagePadFilter(d, modulename);
  PyVTKAddFile_vtkImagePermute(d, modulename);
  PyVTKAddFile_vtkImageSlab(d, modulename);
  PyVTKAddFile_vtkImageQuantizeRGBToIndex(d, modulename);
  PyVTKAddFile_vtkImageRFFT(d, modulename);
  PyVTKAddFile_vtkImageRGBToHSI(d, modulename);
  PyVTKAddFile_vtkImageRGBToHSV(d, modulename);
  PyVTKAddFile_vtkImageRange3D(d, modulename);
  PyVTKAddFile_vtkImageRectilinearWipe(d, modulename);
  PyVTKAddFile_vtkImageResample(d, modulename);
  PyVTKAddFile_vtkImageReslice(d, modulename);
  PyVTKAddFile_vtkImageSeedConnectivity(d, modulename);
  PyVTKAddFile_vtkImageSeparableConvolution(d, modulename);
  PyVTKAddFile_vtkImageShiftScale(d, modulename);
  PyVTKAddFile_vtkImageShrink3D(d, modulename);
  PyVTKAddFile_vtkImageSinusoidSource(d, modulename);
  PyVTKAddFile_vtkImageSkeleton2D(d, modulename);
  PyVTKAddFile_vtkImageSobel2D(d, modulename);
  PyVTKAddFile_vtkImageSobel3D(d, modulename);
  PyVTKAddFile_vtkImageSpatialAlgorithm(d, modulename);
  PyVTKAddFile_vtkImageStencil(d, modulename);
  PyVTKAddFile_vtkImageStencilToImage(d, modulename);
  PyVTKAddFile_vtkImageStencilAlgorithm(d, modulename);
  PyVTKAddFile_vtkImageStencilData(d, modulename);
  PyVTKAddFile_vtkImageStencilSource(d, modulename);
  PyVTKAddFile_vtkImageThreshold(d, modulename);
  PyVTKAddFile_vtkImageToImageStencil(d, modulename);
  PyVTKAddFile_vtkImageTranslateExtent(d, modulename);
  PyVTKAddFile_vtkImageVariance3D(d, modulename);
  PyVTKAddFile_vtkImageWrapPad(d, modulename);
  PyVTKAddFile_vtkImageWeightedSum(d, modulename);
  PyVTKAddFile_vtkImplicitFunctionToImageStencil(d, modulename);
  PyVTKAddFile_vtkLassoStencilSource(d, modulename);
  PyVTKAddFile_vtkPointLoad(d, modulename);
  PyVTKAddFile_vtkROIStencilSource(d, modulename);
  PyVTKAddFile_vtkRTAnalyticSource(d, modulename);
  PyVTKAddFile_vtkSampleFunction(d, modulename);
  PyVTKAddFile_vtkShepardMethod(d, modulename);
  PyVTKAddFile_vtkSimpleImageFilterExample(d, modulename);
  PyVTKAddFile_vtkSurfaceReconstructionFilter(d, modulename);
  PyVTKAddFile_vtkTriangularTexture(d, modulename);
  PyVTKAddFile_vtkVoxelModeller(d, modulename);
  PyVTKAddFile_vtkImageSpatialFilter(d, modulename);
}

