# CMake generated Testfile for 
# Source directory: /home/lakers/Downloads/VTK/Graphics/Testing/Cxx
# Build directory: /home/lakers/Downloads/VTK/Graphics/Testing/Cxx
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(Mace "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "Mace")
ADD_TEST(expCos "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "expCos")
ADD_TEST(BoxClipTriangulate "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "BoxClipTriangulate")
ADD_TEST(CellLocator "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "CellLocator")
ADD_TEST(PointLocator "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "PointLocator")
ADD_TEST(FrustumClip "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "FrustumClip")
ADD_TEST(RGrid "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "RGrid")
ADD_TEST(TestAppendSelection "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestAppendSelection")
ADD_TEST(TestAssignAttribute "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestAssignAttribute")
ADD_TEST(TestBSPTree "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestBSPTree")
ADD_TEST(TestCellDataToPointData "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestCellDataToPointData")
ADD_TEST(TestDensifyPolyData "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestDensifyPolyData")
ADD_TEST(TestClipHyperOctree "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestClipHyperOctree")
ADD_TEST(TestConvertSelection "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestConvertSelection")
ADD_TEST(TestDelaunay2D "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestDelaunay2D")
ADD_TEST(TestExtraction "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestExtraction")
ADD_TEST(TestExtractSelection "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestExtractSelection")
ADD_TEST(TestHyperOctreeContourFilter "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestHyperOctreeContourFilter")
ADD_TEST(TestHyperOctreeCutter "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestHyperOctreeCutter")
ADD_TEST(TestHyperOctreeDual "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestHyperOctreeDual")
ADD_TEST(TestHyperOctreeSurfaceFilter "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestHyperOctreeSurfaceFilter")
ADD_TEST(TestHyperOctreeToUniformGrid "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestHyperOctreeToUniformGrid")
ADD_TEST(TestNamedComponents "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestNamedComponents")
ADD_TEST(TestMeanValueCoordinatesInterpolation1 "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestMeanValueCoordinatesInterpolation1")
ADD_TEST(TestMeanValueCoordinatesInterpolation2 "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestMeanValueCoordinatesInterpolation2")
ADD_TEST(TestPolyDataPointSampler "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestPolyDataPointSampler")
ADD_TEST(TestPolyhedron0 "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestPolyhedron0")
ADD_TEST(TestPolyhedron1 "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestPolyhedron1")
ADD_TEST(TestSelectEnclosedPoints "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestSelectEnclosedPoints")
ADD_TEST(TestTessellatedBoxSource "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestTessellatedBoxSource")
ADD_TEST(TestTessellator "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestTessellator")
ADD_TEST(TestUncertaintyTubeFilter "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestUncertaintyTubeFilter")
ADD_TEST(TestDecimatePolylineFilter "/home/lakers/Downloads/VTK/bin/GraphicsCxxTests" "TestDecimatePolylineFilter")
