# CMake generated Testfile for 
# Source directory: /home/lakers/Downloads/VTK/Rendering/Testing/Cxx
# Build directory: /home/lakers/Downloads/VTK/Rendering/Testing/Cxx
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(otherCoordinate "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "otherCoordinate" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestPriorityStreaming "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestPriorityStreaming" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(LoadOpenGLExtension "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "LoadOpenGLExtension" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestActorLightingFlag "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestActorLightingFlag" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestAnimationScene "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestAnimationScene" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestBlurAndSobelPasses "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestBlurAndSobelPasses" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestDynamic2DLabelMapper "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestDynamic2DLabelMapper" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestFBO "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestFBO" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestFollowerPicking "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestFollowerPicking" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestGaussianBlurPass "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestGaussianBlurPass" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestGlyph3DMapper "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestGlyph3DMapper" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestGlyph3DMapperMasking "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestGlyph3DMapperMasking" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestGlyph3DMapperOrientationArray "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestGlyph3DMapperOrientationArray" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestGlyph3DMapperPicking "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestGlyph3DMapperPicking" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestGPUInfo "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestGPUInfo" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestGradientBackground "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestGradientBackground" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestHomogeneousTransformOfActor "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestHomogeneousTransformOfActor" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestInteractorTimers "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestInteractorTimers" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestLabelPlacer "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestLabelPlacer" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestLabelPlacer2D "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestLabelPlacer2D" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestLabelPlacerCoincidentPoints "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestLabelPlacerCoincidentPoints" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestLabelPlacementMapper2D "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestLabelPlacementMapper2D" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestLabelPlacementMapperCoincidentPoints "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestLabelPlacementMapperCoincidentPoints" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestLightActor "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestLightActor" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestLODActor "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestLODActor" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestManyActors "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestManyActors" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestOrderedTriangulator "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestOrderedTriangulator" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestOpacity "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestOpacity" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestOpenGLPolyDataMapper "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestOpenGLPolyDataMapper" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestOSConeCxx "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestOSConeCxx" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestPOVExporter "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestPOVExporter" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestResetCameraVerticalAspectRatio "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestResetCameraVerticalAspectRatio" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestResetCameraVerticalAspectRatioParallel "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestResetCameraVerticalAspectRatioParallel" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestSobelGradientMagnitudePass "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestSobelGradientMagnitudePass" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestShadowMapPass "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestShadowMapPass" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestTextActorAlphaBlending "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestTextActorAlphaBlending" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestTextActorDepthPeeling "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestTextActorDepthPeeling" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestTextActor3DAlphaBlending "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestTextActor3DAlphaBlending" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestTextActor3DDepthPeeling "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestTextActor3DDepthPeeling" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestTexturedBackground "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestTexturedBackground" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestTextureSize "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestTextureSize" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestTDx "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestTDx" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestTilingCxx "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestTilingCxx" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestTranslucentLUTAlphaBlending "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestTranslucentLUTAlphaBlending" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestTranslucentLUTDepthPeeling "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestTranslucentLUTDepthPeeling" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestTranslucentLUTDepthPeelingPass "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestTranslucentLUTDepthPeelingPass" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestTranslucentLUTTextureAlphaBlending "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestTranslucentLUTTextureAlphaBlending" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestTranslucentLUTTextureDepthPeeling "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestTranslucentLUTTextureDepthPeeling" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestGenericVertexAttributesGLSLCxx "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestGenericVertexAttributesGLSLCxx" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestGenericVertexAttributesGLSLAlphaBlending "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestGenericVertexAttributesGLSLAlphaBlending" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
ADD_TEST(TestGenericVertexAttributesGLSLDepthPeelingPass "/home/lakers/Downloads/VTK/bin/RenderingCxxTests" "TestGenericVertexAttributesGLSLDepthPeelingPass" "-T" "/home/lakers/Downloads/VTK/Testing/Temporary")
SET_TESTS_PROPERTIES(TestGenericVertexAttributesGLSLDepthPeelingPass PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR:.*vtkOpenGLProperty.*Couldn't build the shader program. At this point , it can be an error in a shader or a driver bug.")
