// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPython.h"

#include "vtkSystemIncludes.h"
#include <string.h>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings 

extern  "C" {PyObject *PyVTKAddFile_vtk3DSImporter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArcPlotter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAnnotatedCubeActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAxisActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAxesActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBarChartActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCaptionActor2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCornerAnnotation(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCubeAxesActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCubeAxesActor2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDepthSortPolyData(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEarthSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFacetReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGreedyTerrainDecimation(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGridTransform(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageDataLIC2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageDataLIC2DExtentTranslator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageToPolyDataFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImplicitModeller(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkIterativeClosestPointTransform(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLandmarkTransform(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLegendBoxActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLegendScaleActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkLSDynaReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMNIObjectReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMNIObjectWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMNITagPointReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMNITagPointWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMNITransformReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMNITransformWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPCAAnalysisFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPieChartActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyDataSilhouette(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyDataToImageStencil(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProcrustesAlignmentFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProjectedTerrainPath(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRIBExporter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRIBLight(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRIBProperty(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRenderLargeImage(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSpiderPlotActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTemporalDataSetCache(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTemporalInterpolator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTemporalShiftScale(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTemporalSnapToTimeStep(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkThinPlateSplineTransform(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTransformToGrid(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVRMLImporter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVectorText(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVideoSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkWeightedTransformFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXYPlotActor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkX3DExporter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExodusIICache(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExodusIIReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExodusReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDSPFilterDefinition(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkExodusModel(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDSPFilterGroup(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPExodusIIReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPExodusReader(PyObject *, const char *); }

static PyMethodDef PyvtkHybridPython_ClassMethods[] = {
{NULL, NULL, 0, NULL}};

static void real_initvtkHybridPython(const char *modulename);

extern  "C" { void initvtkHybridPython(); }

void initvtkHybridPython()
{
  static const char modulename[] = "vtkHybridPython";
  real_initvtkHybridPython(modulename);
}

extern  "C" { void initlibvtkHybridPython(); }

void initlibvtkHybridPython()
{
  static const char modulename[] = "libvtkHybridPython";
  real_initvtkHybridPython(modulename);
}

void real_initvtkHybridPython(const char *modulename)
{
  PyObject *m, *d;

  m = Py_InitModule((char*)modulename, PyvtkHybridPython_ClassMethods);
  d = PyModule_GetDict(m);
  if (!d)
    {
    Py_FatalError((char*)"can't get dictionary for module vtkHybridPython");
    }
  PyVTKAddFile_vtk3DSImporter(d, modulename);
  PyVTKAddFile_vtkArcPlotter(d, modulename);
  PyVTKAddFile_vtkAnnotatedCubeActor(d, modulename);
  PyVTKAddFile_vtkAxisActor(d, modulename);
  PyVTKAddFile_vtkAxesActor(d, modulename);
  PyVTKAddFile_vtkBarChartActor(d, modulename);
  PyVTKAddFile_vtkCaptionActor2D(d, modulename);
  PyVTKAddFile_vtkCornerAnnotation(d, modulename);
  PyVTKAddFile_vtkCubeAxesActor(d, modulename);
  PyVTKAddFile_vtkCubeAxesActor2D(d, modulename);
  PyVTKAddFile_vtkDepthSortPolyData(d, modulename);
  PyVTKAddFile_vtkEarthSource(d, modulename);
  PyVTKAddFile_vtkFacetReader(d, modulename);
  PyVTKAddFile_vtkGreedyTerrainDecimation(d, modulename);
  PyVTKAddFile_vtkGridTransform(d, modulename);
  PyVTKAddFile_vtkImageDataLIC2D(d, modulename);
  PyVTKAddFile_vtkImageDataLIC2DExtentTranslator(d, modulename);
  PyVTKAddFile_vtkImageToPolyDataFilter(d, modulename);
  PyVTKAddFile_vtkImplicitModeller(d, modulename);
  PyVTKAddFile_vtkIterativeClosestPointTransform(d, modulename);
  PyVTKAddFile_vtkLandmarkTransform(d, modulename);
  PyVTKAddFile_vtkLegendBoxActor(d, modulename);
  PyVTKAddFile_vtkLegendScaleActor(d, modulename);
  PyVTKAddFile_vtkLSDynaReader(d, modulename);
  PyVTKAddFile_vtkMNIObjectReader(d, modulename);
  PyVTKAddFile_vtkMNIObjectWriter(d, modulename);
  PyVTKAddFile_vtkMNITagPointReader(d, modulename);
  PyVTKAddFile_vtkMNITagPointWriter(d, modulename);
  PyVTKAddFile_vtkMNITransformReader(d, modulename);
  PyVTKAddFile_vtkMNITransformWriter(d, modulename);
  PyVTKAddFile_vtkPCAAnalysisFilter(d, modulename);
  PyVTKAddFile_vtkPieChartActor(d, modulename);
  PyVTKAddFile_vtkPolyDataSilhouette(d, modulename);
  PyVTKAddFile_vtkPolyDataToImageStencil(d, modulename);
  PyVTKAddFile_vtkProcrustesAlignmentFilter(d, modulename);
  PyVTKAddFile_vtkProjectedTerrainPath(d, modulename);
  PyVTKAddFile_vtkRIBExporter(d, modulename);
  PyVTKAddFile_vtkRIBLight(d, modulename);
  PyVTKAddFile_vtkRIBProperty(d, modulename);
  PyVTKAddFile_vtkRenderLargeImage(d, modulename);
  PyVTKAddFile_vtkSpiderPlotActor(d, modulename);
  PyVTKAddFile_vtkTemporalDataSetCache(d, modulename);
  PyVTKAddFile_vtkTemporalInterpolator(d, modulename);
  PyVTKAddFile_vtkTemporalShiftScale(d, modulename);
  PyVTKAddFile_vtkTemporalSnapToTimeStep(d, modulename);
  PyVTKAddFile_vtkThinPlateSplineTransform(d, modulename);
  PyVTKAddFile_vtkTransformToGrid(d, modulename);
  PyVTKAddFile_vtkVRMLImporter(d, modulename);
  PyVTKAddFile_vtkVectorText(d, modulename);
  PyVTKAddFile_vtkVideoSource(d, modulename);
  PyVTKAddFile_vtkWeightedTransformFilter(d, modulename);
  PyVTKAddFile_vtkXYPlotActor(d, modulename);
  PyVTKAddFile_vtkX3DExporter(d, modulename);
  PyVTKAddFile_vtkExodusIICache(d, modulename);
  PyVTKAddFile_vtkExodusIIReader(d, modulename);
  PyVTKAddFile_vtkExodusReader(d, modulename);
  PyVTKAddFile_vtkDSPFilterDefinition(d, modulename);
  PyVTKAddFile_vtkExodusModel(d, modulename);
  PyVTKAddFile_vtkDSPFilterGroup(d, modulename);
  PyVTKAddFile_vtkPExodusIIReader(d, modulename);
  PyVTKAddFile_vtkPExodusReader(d, modulename);
}

