// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPython.h"

#include "vtkSystemIncludes.h"
#include <string.h>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings 

extern  "C" {PyObject *PyVTKAddFile_vtkAbstractParticleWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkASCIITextCodec(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkAVSucdReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBMPReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBMPWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBYUReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBYUWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBase64InputStream(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBase64OutputStream(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkBase64Utilities(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCGMWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkChacoReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCompositeDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkCompositeDataWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDatabaseToTableReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDEMReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDICOMImageReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataCompressor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataObjectReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataObjectWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataSetWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDataWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkDelimitedTextWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEnSight6BinaryReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEnSight6Reader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEnSightGoldBinaryReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEnSightGoldReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEnSightMasterServerReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEnSightReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFLUENTReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFacetWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGESignaReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGAMBITReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGaussianCubeReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericDataObjectReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericDataObjectWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericEnSightReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGenericMovieWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGlobFileNames(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGraphReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGraphWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkIVWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageReader2(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageReader2Collection(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageReader2Factory(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkImageWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkInputStream(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkJavaScriptDataWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkJPEGReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkJPEGWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMFIXReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMaterialLibrary(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMCubesReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMCubesWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMedicalImageProperties(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMedicalImageReader2(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMetaImageReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMetaImageWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMINCImageAttributes(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMINCImageReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMINCImageWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMPASReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMultiBlockPLOT3DReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkMoleculeReaderBase(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkNetCDFCFReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkNetCDFPOPReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkNetCDFReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOBJReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenFOAMReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOutputStream(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPDBReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPLOT3DReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPLYReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPLYWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPNGReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPNGWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPNMReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPNMWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkParticleReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPolyDataWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkPostScriptWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProStarReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRectilinearGridReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRectilinearGridWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRTXMLPolyDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRowQuery(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSESAMEReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkShaderCodeLibrary(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSLACParticleReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSLACReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSQLDatabase(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSQLDatabaseSchema(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSQLiteDatabase(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSQLiteToTableReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSQLiteQuery(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSQLQuery(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSLCReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSTLReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSTLWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSimplePointsReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSortFileNames(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredGridReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredGridWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredPointsReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkStructuredPointsWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTableReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTableWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTableToDatabaseWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTableToSQLiteWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTecplotReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTextCodec(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTextCodecFactory(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTIFFReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTIFFWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTreeReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkTreeWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUGFacetReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUTF8TextCodec(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUTF16TextCodec(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolume16Reader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumeReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLCompositeDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLDataParser(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLDataSetWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLFileReadTester(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLGenericDataObjectReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLHierarchicalBoxDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLHierarchicalDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLImageDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLImageDataWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLHyperOctreeReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLHyperOctreeWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLMaterial(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLMaterialParser(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLMaterialReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLMultiBlockDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLMultiGroupDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLCompositeDataWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLMultiBlockDataWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLHierarchicalBoxDataWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPDataSetWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPDataWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPImageDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPImageDataWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPPolyDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPPolyDataWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPRectilinearGridReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPRectilinearGridWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPStructuredDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPStructuredDataWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPStructuredGridReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPStructuredGridWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPUnstructuredDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPUnstructuredDataWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPUnstructuredGridReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPUnstructuredGridWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLParser(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPolyDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLPolyDataWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLRectilinearGridReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLRectilinearGridWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLShader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLStructuredDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLStructuredDataWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLStructuredGridReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLStructuredGridWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLUnstructuredDataReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLUnstructuredDataWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLUnstructuredGridReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLUnstructuredGridWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLUtilities(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXMLWriter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkXYZMolReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkZLibDataCompressor(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRowQueryToTable(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArrayReader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkArrayWriter(PyObject *, const char *); }

static PyMethodDef PyvtkIOPython_ClassMethods[] = {
{NULL, NULL, 0, NULL}};

static void real_initvtkIOPython(const char *modulename);

extern  "C" { void initvtkIOPython(); }

void initvtkIOPython()
{
  static const char modulename[] = "vtkIOPython";
  real_initvtkIOPython(modulename);
}

extern  "C" { void initlibvtkIOPython(); }

void initlibvtkIOPython()
{
  static const char modulename[] = "libvtkIOPython";
  real_initvtkIOPython(modulename);
}

void real_initvtkIOPython(const char *modulename)
{
  PyObject *m, *d;

  m = Py_InitModule((char*)modulename, PyvtkIOPython_ClassMethods);
  d = PyModule_GetDict(m);
  if (!d)
    {
    Py_FatalError((char*)"can't get dictionary for module vtkIOPython");
    }
  PyVTKAddFile_vtkAbstractParticleWriter(d, modulename);
  PyVTKAddFile_vtkASCIITextCodec(d, modulename);
  PyVTKAddFile_vtkAVSucdReader(d, modulename);
  PyVTKAddFile_vtkBMPReader(d, modulename);
  PyVTKAddFile_vtkBMPWriter(d, modulename);
  PyVTKAddFile_vtkBYUReader(d, modulename);
  PyVTKAddFile_vtkBYUWriter(d, modulename);
  PyVTKAddFile_vtkBase64InputStream(d, modulename);
  PyVTKAddFile_vtkBase64OutputStream(d, modulename);
  PyVTKAddFile_vtkBase64Utilities(d, modulename);
  PyVTKAddFile_vtkCGMWriter(d, modulename);
  PyVTKAddFile_vtkChacoReader(d, modulename);
  PyVTKAddFile_vtkCompositeDataReader(d, modulename);
  PyVTKAddFile_vtkCompositeDataWriter(d, modulename);
  PyVTKAddFile_vtkDatabaseToTableReader(d, modulename);
  PyVTKAddFile_vtkDEMReader(d, modulename);
  PyVTKAddFile_vtkDICOMImageReader(d, modulename);
  PyVTKAddFile_vtkDataCompressor(d, modulename);
  PyVTKAddFile_vtkDataObjectReader(d, modulename);
  PyVTKAddFile_vtkDataObjectWriter(d, modulename);
  PyVTKAddFile_vtkDataReader(d, modulename);
  PyVTKAddFile_vtkDataSetReader(d, modulename);
  PyVTKAddFile_vtkDataSetWriter(d, modulename);
  PyVTKAddFile_vtkDataWriter(d, modulename);
  PyVTKAddFile_vtkDelimitedTextWriter(d, modulename);
  PyVTKAddFile_vtkEnSight6BinaryReader(d, modulename);
  PyVTKAddFile_vtkEnSight6Reader(d, modulename);
  PyVTKAddFile_vtkEnSightGoldBinaryReader(d, modulename);
  PyVTKAddFile_vtkEnSightGoldReader(d, modulename);
  PyVTKAddFile_vtkEnSightMasterServerReader(d, modulename);
  PyVTKAddFile_vtkEnSightReader(d, modulename);
  PyVTKAddFile_vtkFLUENTReader(d, modulename);
  PyVTKAddFile_vtkFacetWriter(d, modulename);
  PyVTKAddFile_vtkGESignaReader(d, modulename);
  PyVTKAddFile_vtkGAMBITReader(d, modulename);
  PyVTKAddFile_vtkGaussianCubeReader(d, modulename);
  PyVTKAddFile_vtkGenericDataObjectReader(d, modulename);
  PyVTKAddFile_vtkGenericDataObjectWriter(d, modulename);
  PyVTKAddFile_vtkGenericEnSightReader(d, modulename);
  PyVTKAddFile_vtkGenericMovieWriter(d, modulename);
  PyVTKAddFile_vtkGlobFileNames(d, modulename);
  PyVTKAddFile_vtkGraphReader(d, modulename);
  PyVTKAddFile_vtkGraphWriter(d, modulename);
  PyVTKAddFile_vtkIVWriter(d, modulename);
  PyVTKAddFile_vtkImageReader(d, modulename);
  PyVTKAddFile_vtkImageReader2(d, modulename);
  PyVTKAddFile_vtkImageReader2Collection(d, modulename);
  PyVTKAddFile_vtkImageReader2Factory(d, modulename);
  PyVTKAddFile_vtkImageWriter(d, modulename);
  PyVTKAddFile_vtkInputStream(d, modulename);
  PyVTKAddFile_vtkJavaScriptDataWriter(d, modulename);
  PyVTKAddFile_vtkJPEGReader(d, modulename);
  PyVTKAddFile_vtkJPEGWriter(d, modulename);
  PyVTKAddFile_vtkMFIXReader(d, modulename);
  PyVTKAddFile_vtkMaterialLibrary(d, modulename);
  PyVTKAddFile_vtkMCubesReader(d, modulename);
  PyVTKAddFile_vtkMCubesWriter(d, modulename);
  PyVTKAddFile_vtkMedicalImageProperties(d, modulename);
  PyVTKAddFile_vtkMedicalImageReader2(d, modulename);
  PyVTKAddFile_vtkMetaImageReader(d, modulename);
  PyVTKAddFile_vtkMetaImageWriter(d, modulename);
  PyVTKAddFile_vtkMINCImageAttributes(d, modulename);
  PyVTKAddFile_vtkMINCImageReader(d, modulename);
  PyVTKAddFile_vtkMINCImageWriter(d, modulename);
  PyVTKAddFile_vtkMPASReader(d, modulename);
  PyVTKAddFile_vtkMultiBlockPLOT3DReader(d, modulename);
  PyVTKAddFile_vtkMoleculeReaderBase(d, modulename);
  PyVTKAddFile_vtkNetCDFCFReader(d, modulename);
  PyVTKAddFile_vtkNetCDFPOPReader(d, modulename);
  PyVTKAddFile_vtkNetCDFReader(d, modulename);
  PyVTKAddFile_vtkOBJReader(d, modulename);
  PyVTKAddFile_vtkOpenFOAMReader(d, modulename);
  PyVTKAddFile_vtkOutputStream(d, modulename);
  PyVTKAddFile_vtkPDBReader(d, modulename);
  PyVTKAddFile_vtkPLOT3DReader(d, modulename);
  PyVTKAddFile_vtkPLYReader(d, modulename);
  PyVTKAddFile_vtkPLYWriter(d, modulename);
  PyVTKAddFile_vtkPNGReader(d, modulename);
  PyVTKAddFile_vtkPNGWriter(d, modulename);
  PyVTKAddFile_vtkPNMReader(d, modulename);
  PyVTKAddFile_vtkPNMWriter(d, modulename);
  PyVTKAddFile_vtkParticleReader(d, modulename);
  PyVTKAddFile_vtkPolyDataReader(d, modulename);
  PyVTKAddFile_vtkPolyDataWriter(d, modulename);
  PyVTKAddFile_vtkPostScriptWriter(d, modulename);
  PyVTKAddFile_vtkProStarReader(d, modulename);
  PyVTKAddFile_vtkRectilinearGridReader(d, modulename);
  PyVTKAddFile_vtkRectilinearGridWriter(d, modulename);
  PyVTKAddFile_vtkRTXMLPolyDataReader(d, modulename);
  PyVTKAddFile_vtkRowQuery(d, modulename);
  PyVTKAddFile_vtkSESAMEReader(d, modulename);
  PyVTKAddFile_vtkShaderCodeLibrary(d, modulename);
  PyVTKAddFile_vtkSLACParticleReader(d, modulename);
  PyVTKAddFile_vtkSLACReader(d, modulename);
  PyVTKAddFile_vtkSQLDatabase(d, modulename);
  PyVTKAddFile_vtkSQLDatabaseSchema(d, modulename);
  PyVTKAddFile_vtkSQLiteDatabase(d, modulename);
  PyVTKAddFile_vtkSQLiteToTableReader(d, modulename);
  PyVTKAddFile_vtkSQLiteQuery(d, modulename);
  PyVTKAddFile_vtkSQLQuery(d, modulename);
  PyVTKAddFile_vtkSLCReader(d, modulename);
  PyVTKAddFile_vtkSTLReader(d, modulename);
  PyVTKAddFile_vtkSTLWriter(d, modulename);
  PyVTKAddFile_vtkSimplePointsReader(d, modulename);
  PyVTKAddFile_vtkSortFileNames(d, modulename);
  PyVTKAddFile_vtkStructuredGridReader(d, modulename);
  PyVTKAddFile_vtkStructuredGridWriter(d, modulename);
  PyVTKAddFile_vtkStructuredPointsReader(d, modulename);
  PyVTKAddFile_vtkStructuredPointsWriter(d, modulename);
  PyVTKAddFile_vtkTableReader(d, modulename);
  PyVTKAddFile_vtkTableWriter(d, modulename);
  PyVTKAddFile_vtkTableToDatabaseWriter(d, modulename);
  PyVTKAddFile_vtkTableToSQLiteWriter(d, modulename);
  PyVTKAddFile_vtkTecplotReader(d, modulename);
  PyVTKAddFile_vtkTextCodec(d, modulename);
  PyVTKAddFile_vtkTextCodecFactory(d, modulename);
  PyVTKAddFile_vtkTIFFReader(d, modulename);
  PyVTKAddFile_vtkTIFFWriter(d, modulename);
  PyVTKAddFile_vtkTreeReader(d, modulename);
  PyVTKAddFile_vtkTreeWriter(d, modulename);
  PyVTKAddFile_vtkUGFacetReader(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridReader(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridWriter(d, modulename);
  PyVTKAddFile_vtkUTF8TextCodec(d, modulename);
  PyVTKAddFile_vtkUTF16TextCodec(d, modulename);
  PyVTKAddFile_vtkVolume16Reader(d, modulename);
  PyVTKAddFile_vtkVolumeReader(d, modulename);
  PyVTKAddFile_vtkWriter(d, modulename);
  PyVTKAddFile_vtkXMLCompositeDataReader(d, modulename);
  PyVTKAddFile_vtkXMLDataParser(d, modulename);
  PyVTKAddFile_vtkXMLDataReader(d, modulename);
  PyVTKAddFile_vtkXMLDataSetWriter(d, modulename);
  PyVTKAddFile_vtkXMLFileReadTester(d, modulename);
  PyVTKAddFile_vtkXMLGenericDataObjectReader(d, modulename);
  PyVTKAddFile_vtkXMLHierarchicalBoxDataReader(d, modulename);
  PyVTKAddFile_vtkXMLHierarchicalDataReader(d, modulename);
  PyVTKAddFile_vtkXMLImageDataReader(d, modulename);
  PyVTKAddFile_vtkXMLImageDataWriter(d, modulename);
  PyVTKAddFile_vtkXMLHyperOctreeReader(d, modulename);
  PyVTKAddFile_vtkXMLHyperOctreeWriter(d, modulename);
  PyVTKAddFile_vtkXMLMaterial(d, modulename);
  PyVTKAddFile_vtkXMLMaterialParser(d, modulename);
  PyVTKAddFile_vtkXMLMaterialReader(d, modulename);
  PyVTKAddFile_vtkXMLMultiBlockDataReader(d, modulename);
  PyVTKAddFile_vtkXMLMultiGroupDataReader(d, modulename);
  PyVTKAddFile_vtkXMLCompositeDataWriter(d, modulename);
  PyVTKAddFile_vtkXMLMultiBlockDataWriter(d, modulename);
  PyVTKAddFile_vtkXMLHierarchicalBoxDataWriter(d, modulename);
  PyVTKAddFile_vtkXMLPDataReader(d, modulename);
  PyVTKAddFile_vtkXMLPDataSetWriter(d, modulename);
  PyVTKAddFile_vtkXMLPDataWriter(d, modulename);
  PyVTKAddFile_vtkXMLPImageDataReader(d, modulename);
  PyVTKAddFile_vtkXMLPImageDataWriter(d, modulename);
  PyVTKAddFile_vtkXMLPPolyDataReader(d, modulename);
  PyVTKAddFile_vtkXMLPPolyDataWriter(d, modulename);
  PyVTKAddFile_vtkXMLPRectilinearGridReader(d, modulename);
  PyVTKAddFile_vtkXMLPRectilinearGridWriter(d, modulename);
  PyVTKAddFile_vtkXMLPStructuredDataReader(d, modulename);
  PyVTKAddFile_vtkXMLPStructuredDataWriter(d, modulename);
  PyVTKAddFile_vtkXMLPStructuredGridReader(d, modulename);
  PyVTKAddFile_vtkXMLPStructuredGridWriter(d, modulename);
  PyVTKAddFile_vtkXMLPUnstructuredDataReader(d, modulename);
  PyVTKAddFile_vtkXMLPUnstructuredDataWriter(d, modulename);
  PyVTKAddFile_vtkXMLPUnstructuredGridReader(d, modulename);
  PyVTKAddFile_vtkXMLPUnstructuredGridWriter(d, modulename);
  PyVTKAddFile_vtkXMLParser(d, modulename);
  PyVTKAddFile_vtkXMLPolyDataReader(d, modulename);
  PyVTKAddFile_vtkXMLPolyDataWriter(d, modulename);
  PyVTKAddFile_vtkXMLReader(d, modulename);
  PyVTKAddFile_vtkXMLRectilinearGridReader(d, modulename);
  PyVTKAddFile_vtkXMLRectilinearGridWriter(d, modulename);
  PyVTKAddFile_vtkXMLShader(d, modulename);
  PyVTKAddFile_vtkXMLStructuredDataReader(d, modulename);
  PyVTKAddFile_vtkXMLStructuredDataWriter(d, modulename);
  PyVTKAddFile_vtkXMLStructuredGridReader(d, modulename);
  PyVTKAddFile_vtkXMLStructuredGridWriter(d, modulename);
  PyVTKAddFile_vtkXMLUnstructuredDataReader(d, modulename);
  PyVTKAddFile_vtkXMLUnstructuredDataWriter(d, modulename);
  PyVTKAddFile_vtkXMLUnstructuredGridReader(d, modulename);
  PyVTKAddFile_vtkXMLUnstructuredGridWriter(d, modulename);
  PyVTKAddFile_vtkXMLUtilities(d, modulename);
  PyVTKAddFile_vtkXMLWriter(d, modulename);
  PyVTKAddFile_vtkXYZMolReader(d, modulename);
  PyVTKAddFile_vtkZLibDataCompressor(d, modulename);
  PyVTKAddFile_vtkRowQueryToTable(d, modulename);
  PyVTKAddFile_vtkArrayReader(d, modulename);
  PyVTKAddFile_vtkArrayWriter(d, modulename);
}

