// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPython.h"

#include "vtkSystemIncludes.h"
#include <string.h>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings 

extern  "C" {PyObject *PyVTKAddFile_vtkDirectionEncoder(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEncodedGradientEstimator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkEncodedGradientShader(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFiniteDifferenceGradientEstimator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFixedPointRayCastImage(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFixedPointVolumeRayCastCompositeGOHelper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFixedPointVolumeRayCastCompositeGOShadeHelper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFixedPointVolumeRayCastCompositeHelper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFixedPointVolumeRayCastCompositeShadeHelper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFixedPointVolumeRayCastHelper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFixedPointVolumeRayCastMIPHelper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkFixedPointVolumeRayCastMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumeRayCastSpaceLeapingImageFilter(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkGPUVolumeRayCastMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkHAVSVolumeMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProjectedAAHexahedraMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkProjectedTetrahedraMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRayCastImageDisplayHelper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkRecursiveSphereDirectionEncoder(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSmartVolumeMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkSphericalDirectionEncoder(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumeMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumeOutlineSource(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumePicker(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumeProMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumeRayCastCompositeFunction(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumeRayCastFunction(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumeRayCastIsosurfaceFunction(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumeRayCastMIPFunction(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumeRayCastMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumeRenderingFactory(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumeTextureMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumeTextureMapper2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkVolumeTextureMapper3D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridBunykRayCastFunction(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridHomogeneousRayIntegrator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridLinearRayIntegrator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridPartialPreIntegration(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridPreIntegration(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridVolumeMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridVolumeRayCastFunction(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridVolumeRayCastIterator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridVolumeRayIntegrator(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridVolumeRayCastMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkUnstructuredGridVolumeZSweepMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLGPUVolumeRayCastMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLHAVSVolumeMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLProjectedAAHexahedraMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLProjectedTetrahedraMapper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLRayCastImageDisplayHelper(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLVolumeTextureMapper2D(PyObject *, const char *); }
extern  "C" {PyObject *PyVTKAddFile_vtkOpenGLVolumeTextureMapper3D(PyObject *, const char *); }

static PyMethodDef PyvtkVolumeRenderingPython_ClassMethods[] = {
{NULL, NULL, 0, NULL}};

static void real_initvtkVolumeRenderingPython(const char *modulename);

extern  "C" { void initvtkVolumeRenderingPython(); }

void initvtkVolumeRenderingPython()
{
  static const char modulename[] = "vtkVolumeRenderingPython";
  real_initvtkVolumeRenderingPython(modulename);
}

extern  "C" { void initlibvtkVolumeRenderingPython(); }

void initlibvtkVolumeRenderingPython()
{
  static const char modulename[] = "libvtkVolumeRenderingPython";
  real_initvtkVolumeRenderingPython(modulename);
}

void real_initvtkVolumeRenderingPython(const char *modulename)
{
  PyObject *m, *d;

  m = Py_InitModule((char*)modulename, PyvtkVolumeRenderingPython_ClassMethods);
  d = PyModule_GetDict(m);
  if (!d)
    {
    Py_FatalError((char*)"can't get dictionary for module vtkVolumeRenderingPython");
    }
  PyVTKAddFile_vtkDirectionEncoder(d, modulename);
  PyVTKAddFile_vtkEncodedGradientEstimator(d, modulename);
  PyVTKAddFile_vtkEncodedGradientShader(d, modulename);
  PyVTKAddFile_vtkFiniteDifferenceGradientEstimator(d, modulename);
  PyVTKAddFile_vtkFixedPointRayCastImage(d, modulename);
  PyVTKAddFile_vtkFixedPointVolumeRayCastCompositeGOHelper(d, modulename);
  PyVTKAddFile_vtkFixedPointVolumeRayCastCompositeGOShadeHelper(d, modulename);
  PyVTKAddFile_vtkFixedPointVolumeRayCastCompositeHelper(d, modulename);
  PyVTKAddFile_vtkFixedPointVolumeRayCastCompositeShadeHelper(d, modulename);
  PyVTKAddFile_vtkFixedPointVolumeRayCastHelper(d, modulename);
  PyVTKAddFile_vtkFixedPointVolumeRayCastMIPHelper(d, modulename);
  PyVTKAddFile_vtkFixedPointVolumeRayCastMapper(d, modulename);
  PyVTKAddFile_vtkVolumeRayCastSpaceLeapingImageFilter(d, modulename);
  PyVTKAddFile_vtkGPUVolumeRayCastMapper(d, modulename);
  PyVTKAddFile_vtkHAVSVolumeMapper(d, modulename);
  PyVTKAddFile_vtkProjectedAAHexahedraMapper(d, modulename);
  PyVTKAddFile_vtkProjectedTetrahedraMapper(d, modulename);
  PyVTKAddFile_vtkRayCastImageDisplayHelper(d, modulename);
  PyVTKAddFile_vtkRecursiveSphereDirectionEncoder(d, modulename);
  PyVTKAddFile_vtkSmartVolumeMapper(d, modulename);
  PyVTKAddFile_vtkSphericalDirectionEncoder(d, modulename);
  PyVTKAddFile_vtkVolumeMapper(d, modulename);
  PyVTKAddFile_vtkVolumeOutlineSource(d, modulename);
  PyVTKAddFile_vtkVolumePicker(d, modulename);
  PyVTKAddFile_vtkVolumeProMapper(d, modulename);
  PyVTKAddFile_vtkVolumeRayCastCompositeFunction(d, modulename);
  PyVTKAddFile_vtkVolumeRayCastFunction(d, modulename);
  PyVTKAddFile_vtkVolumeRayCastIsosurfaceFunction(d, modulename);
  PyVTKAddFile_vtkVolumeRayCastMIPFunction(d, modulename);
  PyVTKAddFile_vtkVolumeRayCastMapper(d, modulename);
  PyVTKAddFile_vtkVolumeRenderingFactory(d, modulename);
  PyVTKAddFile_vtkVolumeTextureMapper(d, modulename);
  PyVTKAddFile_vtkVolumeTextureMapper2D(d, modulename);
  PyVTKAddFile_vtkVolumeTextureMapper3D(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridBunykRayCastFunction(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridHomogeneousRayIntegrator(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridLinearRayIntegrator(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridPartialPreIntegration(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridPreIntegration(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridVolumeMapper(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridVolumeRayCastFunction(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridVolumeRayCastIterator(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridVolumeRayIntegrator(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridVolumeRayCastMapper(d, modulename);
  PyVTKAddFile_vtkUnstructuredGridVolumeZSweepMapper(d, modulename);
  PyVTKAddFile_vtkOpenGLGPUVolumeRayCastMapper(d, modulename);
  PyVTKAddFile_vtkOpenGLHAVSVolumeMapper(d, modulename);
  PyVTKAddFile_vtkOpenGLProjectedAAHexahedraMapper(d, modulename);
  PyVTKAddFile_vtkOpenGLProjectedTetrahedraMapper(d, modulename);
  PyVTKAddFile_vtkOpenGLRayCastImageDisplayHelper(d, modulename);
  PyVTKAddFile_vtkOpenGLVolumeTextureMapper2D(d, modulename);
  PyVTKAddFile_vtkOpenGLVolumeTextureMapper3D(d, modulename);
}

